package com.metabuild.app.config;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.metabuild.app.security.RedisAuthorizationSnapshotStore;
import com.metabuild.modules.admin.auth.application.AuthorizationCommandExecutor;
import com.metabuild.modules.admin.auth.application.AuthorizationSnapshotCompiler;
import com.metabuild.modules.admin.auth.persistence.JdbcAuthorizationGraphRepository;
import com.metabuild.modules.admin.auth.persistence.JdbcAuthorizationRefreshRepository;
import com.metabuild.modules.admin.menus.persistence.JdbcMenuRepository;
import com.metabuild.modules.admin.menus.controller.MenuController;
import com.metabuild.schema.platform.PlatformFlywayRunner;
import com.metabuild.shared.kernel.UuidV7Generator;
import java.time.Clock;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class PermissionCatalogPostgresRedisTest {
  static JdbcTemplate jdbc;static LettuceConnectionFactory redisConnection;static RedisAuthorizationSnapshotStore states;
  static final UUID ADMIN=UUID.fromString("01900000-0000-7000-8000-000000000010");
  @BeforeAll static void setup(){String url=System.getProperty("task18.pg.url");Assumptions.assumeTrue(url!=null,"set task18.pg.url to a disposable PostgreSQL database");var ds=new DriverManagerDataSource(url,System.getProperty("task18.pg.user","ocean"),System.getProperty("task18.pg.password",""));PlatformFlywayRunner.migrate(ds);jdbc=new JdbcTemplate(ds);redisConnection=new LettuceConnectionFactory(System.getProperty("task18.redis.host","127.0.0.1"),Integer.getInteger("task18.redis.port",6379));redisConnection.afterPropertiesSet();var redis=new StringRedisTemplate(redisConnection);redis.afterPropertiesSet();states=new RedisAuthorizationSnapshotStore(redis,new ObjectMapper().findAndRegisterModules());states.delete(ADMIN);}
  @AfterAll static void close(){if(redisConnection!=null){states.delete(ADMIN);redisConnection.destroy();}}

  @Test void freshRenameDeprecateAndCustomizationUpgradeUseRealFenceProtocol(){var ids=new UuidV7Generator();var graph=new JdbcAuthorizationGraphRepository(jdbc);var compiler=new AuthorizationSnapshotCompiler();var port=new JdbcAuthorizationRefreshRepository(jdbc,new DataSourceTransactionManager(jdbc.getDataSource()),graph,compiler,ids,Clock.systemUTC());var executor=new AuthorizationCommandExecutor(port,states,ids::generate,Clock.systemUTC());var base=PermissionCatalogSynchronizer.readCatalog(new ObjectMapper(),"permissions/permission-catalog.json","permissions/menu-seed.json");new PermissionCatalogSynchronizer(jdbc,executor,ids,base).synchronize();var snapshot=compiler.compile(graph.load(ADMIN),Clock.systemUTC().instant());states.delete(ADMIN);assertThat(states.initializeReady(snapshot)).isTrue();
    String oldCode=jdbc.queryForObject("select p.code from mb_permission p join mb_role_permission rp on rp.permission_id=p.id join mb_user_role ur on ur.role_id=rp.role_id where ur.user_id=? and p.status='ACTIVE' order by p.code limit 1",String.class,ADMIN);var old=base.permissions().stream().filter(p->p.code().equals(oldCode)).findFirst().orElseThrow();UUID permissionId=jdbc.queryForObject("select id from mb_permission where code=?",UUID.class,oldCode);String renamed=oldCode+"-renamed";var invalidPermissions=new ArrayList<>(base.permissions());invalidPermissions.set(invalidPermissions.indexOf(old),new PermissionCatalogSynchronizer.Permission(old.sourceKey(),renamed,old.kind(),List.of()));var invalidV2=new PermissionCatalogSynchronizer.Catalog(2,"c".repeat(64),List.copyOf(invalidPermissions),base.menus());assertThatThrownBy(()->new PermissionCatalogSynchronizer(jdbc,executor,ids,invalidV2).synchronize()).isInstanceOf(IllegalStateException.class).hasMessageContaining("explicit alias");assertThat(jdbc.queryForObject("select count(*) from mb_permission_catalog_version where version=2",Integer.class)).isZero();assertThat(states.load(ADMIN)).isNotNull();var renamedPermissions=new ArrayList<>(base.permissions());renamedPermissions.set(renamedPermissions.indexOf(old),new PermissionCatalogSynchronizer.Permission(old.sourceKey(),renamed,old.kind(),List.of(oldCode)));var renamedMenus=base.menus().stream().map(m->oldCode.equals(m.permission())?new PermissionCatalogSynchronizer.Menu(m.sourceKey(),m.subsystemKey(),m.routeKey(),m.path(),m.type(),renamed,m.parentSourceKey(),m.labelKey(),m.icon(),m.sort(),m.visible()):m).toList();var v2=new PermissionCatalogSynchronizer.Catalog(2,"a".repeat(64),List.copyOf(renamedPermissions),renamedMenus);new PermissionCatalogSynchronizer(jdbc,executor,ids,v2).synchronize();assertThat(jdbc.queryForObject("select id from mb_permission where code=?",UUID.class,renamed)).isEqualTo(permissionId);assertThat(jdbc.queryForObject("select count(*) from mb_role_permission where permission_id=?",Integer.class,permissionId)).isPositive();assertThat(jdbc.queryForObject("select count(*) from mb_permission_alias where old_code=?",Integer.class,oldCode)).isOne();
    UUID menu=jdbc.queryForObject("select id from mb_menu where source_key='/_auth/admin/users#page'",UUID.class);jdbc.update("insert into mb_menu_customization(menu_id,label_zh_cn,label_en_us,visible) values (?,?,?,false) on conflict(menu_id) do update set label_zh_cn=excluded.label_zh_cn,label_en_us=excluded.label_en_us,visible=false",menu,"运营中文","Operator English");String removedCode=jdbc.queryForObject("select p.code from mb_permission p join mb_role_permission rp on rp.permission_id=p.id join mb_user_role ur on ur.role_id=rp.role_id where ur.user_id=? and p.code<>? and p.status='ACTIVE' order by p.code limit 1",String.class,ADMIN,renamed);var removed=renamedPermissions.stream().filter(p->p.code().equals(removedCode)).findFirst().orElseThrow();UUID historical=UUID.fromString("01900000-0000-7000-8000-00000000d001");UUID role=jdbc.queryForObject("select role_id from mb_user_role where user_id=?",UUID.class,ADMIN);jdbc.update("insert into mb_user(id,dept_id,username,password_hash,display_name,status,deleted_at) values (?,(select id from mb_dept limit 1),'historical-task18','x','Historical','DISABLED',current_timestamp)",historical);jdbc.update("insert into mb_user_role(user_id,role_id) values (?,?)",historical,role);var v3=new PermissionCatalogSynchronizer.Catalog(3,"b".repeat(64),renamedPermissions.stream().filter(p->p!=removed).toList(),renamedMenus.stream().filter(m->!removed.code().equals(m.permission())).toList());new PermissionCatalogSynchronizer(jdbc,executor,ids,v3).synchronize();assertThat(jdbc.queryForObject("select status from mb_permission where source_key=?",String.class,removed.sourceKey())).isEqualTo("DEPRECATED");assertThat(jdbc.queryForObject("select label_zh_cn||'|'||label_en_us||'|'||visible from mb_menu_customization where menu_id=?",String.class,menu)).isEqualTo("运营中文|Operator English|false");assertThat(jdbc.queryForObject("select count(*) from mb_authz_refresh_outbox where status='DONE'",Integer.class)).isPositive();assertThat(states.load(ADMIN)).isNotNull();var v4=new PermissionCatalogSynchronizer.Catalog(4,"d".repeat(64),v3.permissions(),v3.menus());try(var pool=Executors.newFixedThreadPool(2)){var one=pool.submit(()->new PermissionCatalogSynchronizer(jdbc,executor,ids,v4).synchronize());var two=pool.submit(()->new PermissionCatalogSynchronizer(jdbc,executor,ids,v4).synchronize());one.get();two.get();}catch(Exception failure){throw new AssertionError(failure);}assertThat(jdbc.queryForObject("select count(*) from mb_permission_catalog_version where version=4",Integer.class)).isOne();
    var menuRepository=new JdbcMenuRepository(jdbc,new ObjectMapper());var menuApi=new MenuController(subsystem->List.of(),menuRepository,ids);var created=menuApi.create(new MenuController.Write("admin","dir",null,java.util.Map.of("zh-CN","仅中文"),"folder",90,true,null,null));assertThat(menuRepository.findActive("admin").stream().filter(row->row.id().equals(created.id())).findFirst().orElseThrow().localizedLabel()).containsExactlyEntriesOf(java.util.Map.of("zh-CN","仅中文"));menuApi.update(created.id(),new MenuController.Write("admin","dir",null,java.util.Map.of("en-US","English only"),"folder",91,true,null,null));assertThat(menuRepository.findActive("admin").stream().filter(row->row.id().equals(created.id())).findFirst().orElseThrow().localizedLabel()).containsExactlyEntriesOf(java.util.Map.of("en-US","English only"));UUID catalogA=ids.generate(),catalogB=ids.generate();jdbc.update("insert into mb_menu(id,source_key,origin,subsystem_key,default_label_key,default_type) values (?,'/task18/a#page','CATALOG','admin','a','dir'),(?,'/task18/b#page','CATALOG','admin','b','dir')",catalogA,catalogB);jdbc.update("update mb_menu set default_parent_source_key='/task18/a#page' where id=?",catalogB);assertThatThrownBy(()->jdbc.update("update mb_menu set default_parent_source_key='/task18/b#page' where id=?",catalogA)).isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
  }
}
