/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform;


import com.metabuild.schema.platform.routines.MbNonEmptyStringMap;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.JSONB;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.mb_non_empty_string_map</code>
     */
    public static Boolean mbNonEmptyStringMap(
          Configuration configuration
        , JSONB candidate
    ) {
        MbNonEmptyStringMap f = new MbNonEmptyStringMap();
        f.setCandidate(candidate);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.mb_non_empty_string_map</code> as a field.
     */
    public static Field<Boolean> mbNonEmptyStringMap(
          JSONB candidate
    ) {
        MbNonEmptyStringMap f = new MbNonEmptyStringMap();
        f.setCandidate(candidate);

        return f.asField();
    }

    /**
     * Get <code>public.mb_non_empty_string_map</code> as a field.
     */
    public static Field<Boolean> mbNonEmptyStringMap(
          Field<JSONB> candidate
    ) {
        MbNonEmptyStringMap f = new MbNonEmptyStringMap();
        f.setCandidate(candidate);

        return f.asField();
    }
}
