/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform;


import com.metabuild.schema.platform.tables.MbAuthzRefreshOutbox;
import com.metabuild.schema.platform.tables.MbCompany;
import com.metabuild.schema.platform.tables.MbCredentialRevocationOutbox;
import com.metabuild.schema.platform.tables.MbDept;
import com.metabuild.schema.platform.tables.MbDictionary;
import com.metabuild.schema.platform.tables.MbDictionaryItem;
import com.metabuild.schema.platform.tables.MbInboxMessage;
import com.metabuild.schema.platform.tables.MbInboxPublishOutbox;
import com.metabuild.schema.platform.tables.MbLoginAuditOutbox;
import com.metabuild.schema.platform.tables.MbLoginLog;
import com.metabuild.schema.platform.tables.MbMenu;
import com.metabuild.schema.platform.tables.MbMenuCustomization;
import com.metabuild.schema.platform.tables.MbOperationLog;
import com.metabuild.schema.platform.tables.MbPermission;
import com.metabuild.schema.platform.tables.MbPermissionAlias;
import com.metabuild.schema.platform.tables.MbPermissionCatalogVersion;
import com.metabuild.schema.platform.tables.MbRefreshToken;
import com.metabuild.schema.platform.tables.MbRole;
import com.metabuild.schema.platform.tables.MbRoleCustomDept;
import com.metabuild.schema.platform.tables.MbRolePermission;
import com.metabuild.schema.platform.tables.MbSchemaProbe;
import com.metabuild.schema.platform.tables.MbUser;
import com.metabuild.schema.platform.tables.MbUserProfile;
import com.metabuild.schema.platform.tables.MbUserRole;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.mb_authz_refresh_outbox</code>.
     */
    public static final MbAuthzRefreshOutbox MB_AUTHZ_REFRESH_OUTBOX = MbAuthzRefreshOutbox.MB_AUTHZ_REFRESH_OUTBOX;

    /**
     * The table <code>public.mb_company</code>.
     */
    public static final MbCompany MB_COMPANY = MbCompany.MB_COMPANY;

    /**
     * The table <code>public.mb_credential_revocation_outbox</code>.
     */
    public static final MbCredentialRevocationOutbox MB_CREDENTIAL_REVOCATION_OUTBOX = MbCredentialRevocationOutbox.MB_CREDENTIAL_REVOCATION_OUTBOX;

    /**
     * The table <code>public.mb_dept</code>.
     */
    public static final MbDept MB_DEPT = MbDept.MB_DEPT;

    /**
     * The table <code>public.mb_dictionary</code>.
     */
    public static final MbDictionary MB_DICTIONARY = MbDictionary.MB_DICTIONARY;

    /**
     * The table <code>public.mb_dictionary_item</code>.
     */
    public static final MbDictionaryItem MB_DICTIONARY_ITEM = MbDictionaryItem.MB_DICTIONARY_ITEM;

    /**
     * The table <code>public.mb_inbox_message</code>.
     */
    public static final MbInboxMessage MB_INBOX_MESSAGE = MbInboxMessage.MB_INBOX_MESSAGE;

    /**
     * The table <code>public.mb_inbox_publish_outbox</code>.
     */
    public static final MbInboxPublishOutbox MB_INBOX_PUBLISH_OUTBOX = MbInboxPublishOutbox.MB_INBOX_PUBLISH_OUTBOX;

    /**
     * The table <code>public.mb_login_audit_outbox</code>.
     */
    public static final MbLoginAuditOutbox MB_LOGIN_AUDIT_OUTBOX = MbLoginAuditOutbox.MB_LOGIN_AUDIT_OUTBOX;

    /**
     * The table <code>public.mb_login_log</code>.
     */
    public static final MbLoginLog MB_LOGIN_LOG = MbLoginLog.MB_LOGIN_LOG;

    /**
     * The table <code>public.mb_menu</code>.
     */
    public static final MbMenu MB_MENU = MbMenu.MB_MENU;

    /**
     * The table <code>public.mb_menu_customization</code>.
     */
    public static final MbMenuCustomization MB_MENU_CUSTOMIZATION = MbMenuCustomization.MB_MENU_CUSTOMIZATION;

    /**
     * The table <code>public.mb_operation_log</code>.
     */
    public static final MbOperationLog MB_OPERATION_LOG = MbOperationLog.MB_OPERATION_LOG;

    /**
     * The table <code>public.mb_permission</code>.
     */
    public static final MbPermission MB_PERMISSION = MbPermission.MB_PERMISSION;

    /**
     * The table <code>public.mb_permission_alias</code>.
     */
    public static final MbPermissionAlias MB_PERMISSION_ALIAS = MbPermissionAlias.MB_PERMISSION_ALIAS;

    /**
     * The table <code>public.mb_permission_catalog_version</code>.
     */
    public static final MbPermissionCatalogVersion MB_PERMISSION_CATALOG_VERSION = MbPermissionCatalogVersion.MB_PERMISSION_CATALOG_VERSION;

    /**
     * The table <code>public.mb_refresh_token</code>.
     */
    public static final MbRefreshToken MB_REFRESH_TOKEN = MbRefreshToken.MB_REFRESH_TOKEN;

    /**
     * The table <code>public.mb_role</code>.
     */
    public static final MbRole MB_ROLE = MbRole.MB_ROLE;

    /**
     * The table <code>public.mb_role_custom_dept</code>.
     */
    public static final MbRoleCustomDept MB_ROLE_CUSTOM_DEPT = MbRoleCustomDept.MB_ROLE_CUSTOM_DEPT;

    /**
     * The table <code>public.mb_role_permission</code>.
     */
    public static final MbRolePermission MB_ROLE_PERMISSION = MbRolePermission.MB_ROLE_PERMISSION;

    /**
     * The table <code>public.mb_schema_probe</code>.
     */
    public static final MbSchemaProbe MB_SCHEMA_PROBE = MbSchemaProbe.MB_SCHEMA_PROBE;

    /**
     * The table <code>public.mb_user</code>.
     */
    public static final MbUser MB_USER = MbUser.MB_USER;

    /**
     * The table <code>public.mb_user_profile</code>.
     */
    public static final MbUserProfile MB_USER_PROFILE = MbUserProfile.MB_USER_PROFILE;

    /**
     * The table <code>public.mb_user_role</code>.
     */
    public static final MbUserRole MB_USER_ROLE = MbUserRole.MB_USER_ROLE;
}
