/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform;


import com.metabuild.schema.platform.tables.MbSchemaProbe;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.mb_schema_probe</code>.
     */
    public static final MbSchemaProbe MB_SCHEMA_PROBE = MbSchemaProbe.MB_SCHEMA_PROBE;
}
