package com.metabuild.modules.admin.dictionaries.persistence;
import com.metabuild.modules.admin.dictionaries.application.*;import com.metabuild.shared.kernel.*;import java.util.*;import org.jooq.*;import org.jooq.exception.IntegrityConstraintViolationException;import org.springframework.dao.DuplicateKeyException;
public final class JooqDictionaryRepository implements DictionaryRepository {private final DSLContext db;public JooqDictionaryRepository(DSLContext db){this.db=db;}
 private static DictionaryView dictionary(org.jooq.Record r){return new DictionaryView(r.get("id",UUID.class),r.get("name",String.class),r.get("code",String.class),r.get("remark",String.class),Boolean.TRUE.equals(r.get("builtin",Boolean.class)));}
 private static DictionaryItemView item(org.jooq.Record r){return new DictionaryItemView(r.get("id",UUID.class),r.get("dictionary_id",UUID.class),r.get("label",String.class),r.get("value",String.class),r.get("sort",Integer.class),Boolean.TRUE.equals(r.get("enabled",Boolean.class)),r.get("color",String.class),r.get("remark",String.class));}
 public List<DictionaryView> list(){return db.fetch("select id,name,code,remark,builtin from mb_dictionary order by code").map(JooqDictionaryRepository::dictionary);}public Optional<DictionaryView> find(UUID id){return db.fetchOptional("select id,name,code,remark,builtin from mb_dictionary where id=?",id).map(JooqDictionaryRepository::dictionary);}
 public DictionaryView insert(DictionaryView x){try{db.execute("insert into mb_dictionary(id,name,code,remark,builtin) values(?,?,?,?,?)",x.id(),x.name(),x.code(),x.remark(),x.builtin());return x;}catch(IntegrityConstraintViolationException | DuplicateKeyException e){throw new Conflict(()->"dictionary.code.conflict","Dictionary code already exists");}}
 public DictionaryView update(UUID id,String name,String remark){if(db.execute("update mb_dictionary set name=?,remark=?,updated_at=current_timestamp where id=?",name,remark,id)==0)throw missing();return find(id).orElseThrow();}public boolean delete(UUID id){return db.execute("delete from mb_dictionary where id=?",id)>0;}
 public List<DictionaryItemView> items(UUID d){return db.fetch("select id,dictionary_id,label,value,sort,enabled,color,remark from mb_dictionary_item where dictionary_id=? order by sort,id",d).map(JooqDictionaryRepository::item);}public Optional<DictionaryItemView> findItem(UUID d,UUID id){return db.fetchOptional("select id,dictionary_id,label,value,sort,enabled,color,remark from mb_dictionary_item where dictionary_id=? and id=?",d,id).map(JooqDictionaryRepository::item);}
 public DictionaryItemView insertItem(DictionaryItemView x){try{db.execute("insert into mb_dictionary_item(id,dictionary_id,label,value,sort,enabled,color,remark) values(?,?,?,?,?,?,?,?)",x.id(),x.dictionaryId(),x.label(),x.value(),x.sort(),x.enabled(),x.color(),x.remark());return x;}catch(IntegrityConstraintViolationException | DuplicateKeyException e){throw new Conflict(()->"dictionary.item.value-conflict","Dictionary item value already exists");}}
 public DictionaryItemView updateItem(DictionaryItemView x){try{if(db.execute("update mb_dictionary_item set label=?,value=?,sort=?,enabled=?,color=?,remark=?,updated_at=current_timestamp where dictionary_id=? and id=?",x.label(),x.value(),x.sort(),x.enabled(),x.color(),x.remark(),x.dictionaryId(),x.id())==0)throw new NotFound(()->"dictionary.item.not-found","Dictionary item not found");return x;}catch(IntegrityConstraintViolationException | DuplicateKeyException e){throw new Conflict(()->"dictionary.item.value-conflict","Dictionary item value already exists");}}
 public boolean deleteItem(UUID d,UUID id){return db.execute("delete from mb_dictionary_item where dictionary_id=? and id=?",d,id)>0;}private static NotFound missing(){return new NotFound(()->"dictionary.not-found","Dictionary not found");}}
