/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.lastmile.tables;


import com.metabuild.schema.lastmile.Keys;
import com.metabuild.schema.lastmile.Public;
import com.metabuild.schema.lastmile.tables.records.BizSchemaProbeRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizSchemaProbe extends TableImpl<BizSchemaProbeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.biz_schema_probe</code>
     */
    public static final BizSchemaProbe BIZ_SCHEMA_PROBE = new BizSchemaProbe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizSchemaProbeRecord> getRecordType() {
        return BizSchemaProbeRecord.class;
    }

    /**
     * The column <code>public.biz_schema_probe.id</code>.
     */
    public final TableField<BizSchemaProbeRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.biz_schema_probe.owner_name</code>.
     */
    public final TableField<BizSchemaProbeRecord, String> OWNER_NAME = createField(DSL.name("owner_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.biz_schema_probe.created_at</code>.
     */
    public final TableField<BizSchemaProbeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private BizSchemaProbe(Name alias, Table<BizSchemaProbeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BizSchemaProbe(Name alias, Table<BizSchemaProbeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.biz_schema_probe</code> table reference
     */
    public BizSchemaProbe(String alias) {
        this(DSL.name(alias), BIZ_SCHEMA_PROBE);
    }

    /**
     * Create an aliased <code>public.biz_schema_probe</code> table reference
     */
    public BizSchemaProbe(Name alias) {
        this(alias, BIZ_SCHEMA_PROBE);
    }

    /**
     * Create a <code>public.biz_schema_probe</code> table reference
     */
    public BizSchemaProbe() {
        this(DSL.name("biz_schema_probe"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BizSchemaProbeRecord> getPrimaryKey() {
        return Keys.BIZ_SCHEMA_PROBE_PKEY;
    }

    @Override
    public List<Check<BizSchemaProbeRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("biz_schema_probe_owner_name_check"), "(((owner_name)::text = 'lastmile'::text))", true)
        );
    }

    @Override
    public BizSchemaProbe as(String alias) {
        return new BizSchemaProbe(DSL.name(alias), this);
    }

    @Override
    public BizSchemaProbe as(Name alias) {
        return new BizSchemaProbe(alias, this);
    }

    @Override
    public BizSchemaProbe as(Table<?> alias) {
        return new BizSchemaProbe(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizSchemaProbe rename(String name) {
        return new BizSchemaProbe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizSchemaProbe rename(Name name) {
        return new BizSchemaProbe(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizSchemaProbe rename(Table<?> name) {
        return new BizSchemaProbe(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizSchemaProbe where(Condition condition) {
        return new BizSchemaProbe(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizSchemaProbe where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizSchemaProbe where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizSchemaProbe where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizSchemaProbe where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizSchemaProbe where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizSchemaProbe where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizSchemaProbe where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizSchemaProbe whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizSchemaProbe whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
