/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.routines;


import com.metabuild.schema.platform.Public;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNonEmptyStringMap extends AbstractRoutine<Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.mb_non_empty_string_map.RETURN_VALUE</code>.
     */
    public static final Parameter<Boolean> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>public.mb_non_empty_string_map.candidate</code>.
     */
    public static final Parameter<JSONB> CANDIDATE = Internal.createParameter("candidate", SQLDataType.JSONB, false, false);

    /**
     * Create a new routine call instance
     */
    public MbNonEmptyStringMap() {
        super("mb_non_empty_string_map", Public.PUBLIC, SQLDataType.BOOLEAN);

        setReturnParameter(RETURN_VALUE);
        addInParameter(CANDIDATE);
    }

    /**
     * Set the <code>candidate</code> parameter IN value to the routine
     */
    public void setCandidate(JSONB value) {
        setValue(CANDIDATE, value);
    }

    /**
     * Set the <code>candidate</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setCandidate(Field<JSONB> field) {
        setField(CANDIDATE, field);
    }
}
