// admin 是内核子系统：登录后 Shell、消息、个人中心和基础权限都依赖它。
// 路由、菜单与按钮级权限在此保持同一声明口径。
// 权限符用原型业务域风格（spec §7.5）。
import type { SubsystemManifest } from '@/modules/types';

export const adminManifest: SubsystemManifest = {
  subsystem: {
    key: 'admin',
    label: { 'zh-CN': '后台管理', 'en-US': 'Admin' },
    desc: { 'zh-CN': '组织 · 权限 · 审计', 'en-US': 'Org · IAM · Audit' },
    icon: 'layout-grid',
    color: '#3370ff',
    home: '/admin/dashboard',
    builtin: true,
    enabled: true,
    sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
  },
  menuSeed: [
    {
      id: 'm-home',
      parentId: null,
      subsystemKey: 'admin',
      type: 'dir',
      label: { 'zh-CN': '工作台', 'en-US': 'Workspace' },
      shortLabel: { 'zh-CN': '工作台', 'en-US': 'Workspace' },
      icon: 'layout-dashboard',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-dashboard',
      parentId: 'm-home',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '企业概览', 'en-US': 'Overview' },
      path: '/admin/dashboard',
      permission: 'dashboard:overview:view',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-org',
      parentId: null,
      subsystemKey: 'admin',
      type: 'dir',
      label: { 'zh-CN': '组织与权限', 'en-US': 'Organization & Access' },
      shortLabel: { 'zh-CN': '组织', 'en-US': 'Org' },
      icon: 'users',
      visible: true,
      sort: 2,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-users',
      parentId: 'm-org',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '成员与部门', 'en-US': 'Members & Departments' },
      path: '/admin/users',
      permission: 'iam:user:view',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-roles',
      parentId: 'm-org',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '角色与权限', 'en-US': 'Roles & Permissions' },
      path: '/admin/roles',
      permission: 'iam:role:view',
      visible: true,
      sort: 2,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-menus',
      parentId: 'm-org',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '菜单管理', 'en-US': 'Menu Management' },
      path: '/admin/menus',
      permission: 'iam:menu:view',
      icon: 'menu',
      visible: true,
      sort: 3,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-menu-create',
      parentId: 'm-menus',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '新增菜单', 'en-US': 'Create Menu' },
      permission: 'iam:menu:create',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-menu-update',
      parentId: 'm-menus',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '编辑菜单', 'en-US': 'Edit Menu' },
      permission: 'iam:menu:update',
      visible: true,
      sort: 2,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-menu-toggle',
      parentId: 'm-menus',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '切换显示', 'en-US': 'Toggle Visibility' },
      permission: 'iam:menu:toggle',
      visible: true,
      sort: 3,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-menu-delete',
      parentId: 'm-menus',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '删除菜单', 'en-US': 'Delete Menu' },
      permission: 'iam:menu:del',
      visible: true,
      sort: 4,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-audit',
      parentId: null,
      subsystemKey: 'admin',
      type: 'dir',
      label: { 'zh-CN': '安全审计', 'en-US': 'Security Audit' },
      shortLabel: { 'zh-CN': '审计', 'en-US': 'Audit' },
      icon: 'list',
      visible: true,
      sort: 3,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-logs',
      parentId: 'm-audit',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '日志审计', 'en-US': 'Audit Logs' },
      path: '/admin/logs',
      permission: 'audit:oplog:view',
      icon: 'list',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-operation-log-export',
      parentId: 'm-logs',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '导出操作日志', 'en-US': 'Export Operation Logs' },
      permission: 'audit:oplog:export',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-login-log-export',
      parentId: 'm-logs',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '导出登录日志', 'en-US': 'Export Login Logs' },
      permission: 'audit:login:export',
      visible: true,
      sort: 2,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-file-center',
      parentId: null,
      subsystemKey: 'admin',
      type: 'dir',
      label: { 'zh-CN': '文件中心', 'en-US': 'File Center' },
      shortLabel: { 'zh-CN': '文件', 'en-US': 'Files' },
      icon: 'folder',
      visible: true,
      sort: 4,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-files',
      parentId: 'm-file-center',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '文件管理', 'en-US': 'File Management' },
      path: '/admin/files',
      permission: 'file:doc:view',
      icon: 'folder',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-file-upload',
      parentId: 'm-files',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '上传文件', 'en-US': 'Upload' },
      permission: 'file:doc:upload',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-file-download', parentId: 'm-files', subsystemKey: 'admin', type: 'action',
      label: { 'zh-CN': '下载文件', 'en-US': 'Download' }, permission: 'file:doc:download', visible: true, sort: 2, origin: 'catalog', runtimeManaged: false,
    },
    {
      id: 'a-file-rename', parentId: 'm-files', subsystemKey: 'admin', type: 'action',
      label: { 'zh-CN': '重命名', 'en-US': 'Rename' }, permission: 'file:doc:rename', visible: true, sort: 3, origin: 'catalog', runtimeManaged: false,
    },
    {
      id: 'a-file-share', parentId: 'm-files', subsystemKey: 'admin', type: 'action',
      label: { 'zh-CN': '分享文件', 'en-US': 'Share' }, permission: 'file:doc:share', visible: true, sort: 4, origin: 'catalog', runtimeManaged: false,
    },
    {
      id: 'a-file-del', parentId: 'm-files', subsystemKey: 'admin', type: 'action',
      label: { 'zh-CN': '删除文件', 'en-US': 'Delete' }, permission: 'file:doc:del', visible: true, sort: 5, origin: 'catalog', runtimeManaged: false,
    },
    {
      id: 'm-system',
      parentId: null,
      subsystemKey: 'admin',
      type: 'dir',
      label: { 'zh-CN': '系统设置', 'en-US': 'System Settings' },
      shortLabel: { 'zh-CN': '设置', 'en-US': 'Settings' },
      icon: 'settings',
      visible: true,
      sort: 5,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-company',
      parentId: 'm-system',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '企业信息', 'en-US': 'Company Information' },
      path: '/admin/company',
      permission: 'sys:org:view',
      icon: 'settings',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-company-edit',
      parentId: 'm-company',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '编辑企业信息', 'en-US': 'Edit Company Information' },
      permission: 'sys:org:edit',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'm-dictionaries',
      parentId: 'm-system',
      subsystemKey: 'admin',
      type: 'menu',
      label: { 'zh-CN': '字典管理', 'en-US': 'Dictionaries' },
      path: '/admin/dictionaries',
      permission: 'sys:dict:view',
      icon: 'list',
      visible: true,
      sort: 2,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-dictionary-create',
      parentId: 'm-dictionaries',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '新增字典', 'en-US': 'Create Dictionary' },
      permission: 'sys:dict:create',
      visible: true,
      sort: 1,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-dictionary-update',
      parentId: 'm-dictionaries',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '编辑字典', 'en-US': 'Edit Dictionary' },
      permission: 'sys:dict:update',
      visible: true,
      sort: 2,
      origin: 'catalog',
      runtimeManaged: false,
    },
    {
      id: 'a-dictionary-delete',
      parentId: 'm-dictionaries',
      subsystemKey: 'admin',
      type: 'action',
      label: { 'zh-CN': '删除字典', 'en-US': 'Delete Dictionary' },
      permission: 'sys:dict:delete',
      visible: true,
      sort: 3,
      origin: 'catalog',
      runtimeManaged: false,
    },
  ],
};
