/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbCompany;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbCompanyRecord extends UpdatableRecordImpl<MbCompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_company.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_company.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_company.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_company.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mb_company.verified</code>.
     */
    public void setVerified(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_company.verified</code>.
     */
    public Boolean getVerified() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.mb_company.domain</code>.
     */
    public void setDomain(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_company.domain</code>.
     */
    public String getDomain() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_company.code</code>.
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_company.code</code>.
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_company.industry</code>.
     */
    public void setIndustry(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_company.industry</code>.
     */
    public String getIndustry() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_company.scale</code>.
     */
    public void setScale(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_company.scale</code>.
     */
    public String getScale() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_company.data_residency</code>.
     */
    public void setDataResidency(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_company.data_residency</code>.
     */
    public String getDataResidency() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_company.created_date</code>.
     */
    public void setCreatedDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_company.created_date</code>.
     */
    public LocalDate getCreatedDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>public.mb_company.contact_name</code>.
     */
    public void setContactName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_company.contact_name</code>.
     */
    public String getContactName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_company.contact_email</code>.
     */
    public void setContactEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_company.contact_email</code>.
     */
    public String getContactEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.mb_company.contact_phone</code>.
     */
    public void setContactPhone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_company.contact_phone</code>.
     */
    public String getContactPhone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.mb_company.landline</code>.
     */
    public void setLandline(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_company.landline</code>.
     */
    public String getLandline() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.mb_company.address</code>.
     */
    public void setAddress(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_company.address</code>.
     */
    public String getAddress() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.mb_company.postal_code</code>.
     */
    public void setPostalCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mb_company.postal_code</code>.
     */
    public String getPostalCode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.mb_company.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.mb_company.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(15);
    }

    /**
     * Setter for <code>public.mb_company.singleton_key</code>.
     */
    public void setSingletonKey(Short value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.mb_company.singleton_key</code>.
     */
    public Short getSingletonKey() {
        return (Short) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbCompanyRecord
     */
    public MbCompanyRecord() {
        super(MbCompany.MB_COMPANY);
    }

    /**
     * Create a detached, initialised MbCompanyRecord
     */
    public MbCompanyRecord(UUID id, String name, Boolean verified, String domain, String code, String industry, String scale, String dataResidency, LocalDate createdDate, String contactName, String contactEmail, String contactPhone, String landline, String address, String postalCode, OffsetDateTime updatedAt, Short singletonKey) {
        super(MbCompany.MB_COMPANY);

        setId(id);
        setName(name);
        setVerified(verified);
        setDomain(domain);
        setCode(code);
        setIndustry(industry);
        setScale(scale);
        setDataResidency(dataResidency);
        setCreatedDate(createdDate);
        setContactName(contactName);
        setContactEmail(contactEmail);
        setContactPhone(contactPhone);
        setLandline(landline);
        setAddress(address);
        setPostalCode(postalCode);
        setUpdatedAt(updatedAt);
        setSingletonKey(singletonKey);
        resetChangedOnNotNull();
    }
}
