/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbCredentialRevocationOutbox;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbCredentialRevocationOutboxRecord extends UpdatableRecordImpl<MbCredentialRevocationOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_credential_revocation_outbox.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_credential_revocation_outbox.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_credential_revocation_outbox.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_credential_revocation_outbox.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.credential_revision</code>.
     */
    public void setCredentialRevision(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.credential_revision</code>.
     */
    public Long getCredentialRevision() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.event_type</code>.
     */
    public void setEventType(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.event_type</code>.
     */
    public String getEventType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_credential_revocation_outbox.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_credential_revocation_outbox.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_credential_revocation_outbox.attempts</code>.
     */
    public void setAttempts(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_credential_revocation_outbox.attempts</code>.
     */
    public Integer getAttempts() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.next_attempt_at</code>.
     */
    public void setNextAttemptAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.next_attempt_at</code>.
     */
    public OffsetDateTime getNextAttemptAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.last_error</code>.
     */
    public void setLastError(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.last_error</code>.
     */
    public String getLastError() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.processed_at</code>.
     */
    public void setProcessedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.processed_at</code>.
     */
    public OffsetDateTime getProcessedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.protected_session_id</code>.
     */
    public void setProtectedSessionId(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.protected_session_id</code>.
     */
    public String getProtectedSessionId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.mb_credential_revocation_outbox.worker_id</code>.
     */
    public void setWorkerId(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_credential_revocation_outbox.worker_id</code>.
     */
    public UUID getWorkerId() {
        return (UUID) get(11);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.claimed_at</code>.
     */
    public void setClaimedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.claimed_at</code>.
     */
    public OffsetDateTime getClaimedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for
     * <code>public.mb_credential_revocation_outbox.lease_until</code>.
     */
    public void setLeaseUntil(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>public.mb_credential_revocation_outbox.lease_until</code>.
     */
    public OffsetDateTime getLeaseUntil() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbCredentialRevocationOutboxRecord
     */
    public MbCredentialRevocationOutboxRecord() {
        super(MbCredentialRevocationOutbox.MB_CREDENTIAL_REVOCATION_OUTBOX);
    }

    /**
     * Create a detached, initialised MbCredentialRevocationOutboxRecord
     */
    public MbCredentialRevocationOutboxRecord(UUID id, UUID userId, Long credentialRevision, String eventType, String status, Integer attempts, OffsetDateTime nextAttemptAt, String lastError, OffsetDateTime createdAt, OffsetDateTime processedAt, String protectedSessionId, UUID workerId, OffsetDateTime claimedAt, OffsetDateTime leaseUntil) {
        super(MbCredentialRevocationOutbox.MB_CREDENTIAL_REVOCATION_OUTBOX);

        setId(id);
        setUserId(userId);
        setCredentialRevision(credentialRevision);
        setEventType(eventType);
        setStatus(status);
        setAttempts(attempts);
        setNextAttemptAt(nextAttemptAt);
        setLastError(lastError);
        setCreatedAt(createdAt);
        setProcessedAt(processedAt);
        setProtectedSessionId(protectedSessionId);
        setWorkerId(workerId);
        setClaimedAt(claimedAt);
        setLeaseUntil(leaseUntil);
        resetChangedOnNotNull();
    }
}
