/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbDept;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDeptRecord extends UpdatableRecordImpl<MbDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_dept.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_dept.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_dept.parent_id</code>.
     */
    public void setParentId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_dept.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_dept.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_dept.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_dept.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_dept.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_dept.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_dept.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_dept.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_dept.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.mb_dept.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_dept.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.mb_dept.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_dept.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.mb_dept.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_dept.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbDeptRecord
     */
    public MbDeptRecord() {
        super(MbDept.MB_DEPT);
    }

    /**
     * Create a detached, initialised MbDeptRecord
     */
    public MbDeptRecord(UUID id, UUID parentId, String code, String name, String status, Integer sortOrder, OffsetDateTime deletedAt, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(MbDept.MB_DEPT);

        setId(id);
        setParentId(parentId);
        setCode(code);
        setName(name);
        setStatus(status);
        setSortOrder(sortOrder);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
