/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbDictionaryItem;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDictionaryItemRecord extends UpdatableRecordImpl<MbDictionaryItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_dictionary_item.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.dictionary_id</code>.
     */
    public void setDictionaryId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.dictionary_id</code>.
     */
    public UUID getDictionaryId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.label</code>.
     */
    public void setLabel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.label</code>.
     */
    public String getLabel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.sort</code>.
     */
    public void setSort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.sort</code>.
     */
    public Integer getSort() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.color</code>.
     */
    public void setColor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.color</code>.
     */
    public String getColor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.remark</code>.
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.remark</code>.
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.mb_dictionary_item.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_dictionary_item.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbDictionaryItemRecord
     */
    public MbDictionaryItemRecord() {
        super(MbDictionaryItem.MB_DICTIONARY_ITEM);
    }

    /**
     * Create a detached, initialised MbDictionaryItemRecord
     */
    public MbDictionaryItemRecord(UUID id, UUID dictionaryId, String label, String value, Integer sort, Boolean enabled, String color, String remark, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(MbDictionaryItem.MB_DICTIONARY_ITEM);

        setId(id);
        setDictionaryId(dictionaryId);
        setLabel(label);
        setValue(value);
        setSort(sort);
        setEnabled(enabled);
        setColor(color);
        setRemark(remark);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
