/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbDictionary;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDictionaryRecord extends UpdatableRecordImpl<MbDictionaryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_dictionary.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_dictionary.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_dictionary.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_dictionary.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mb_dictionary.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_dictionary.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_dictionary.remark</code>.
     */
    public void setRemark(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_dictionary.remark</code>.
     */
    public String getRemark() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_dictionary.builtin</code>.
     */
    public void setBuiltin(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_dictionary.builtin</code>.
     */
    public Boolean getBuiltin() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.mb_dictionary.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_dictionary.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.mb_dictionary.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_dictionary.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbDictionaryRecord
     */
    public MbDictionaryRecord() {
        super(MbDictionary.MB_DICTIONARY);
    }

    /**
     * Create a detached, initialised MbDictionaryRecord
     */
    public MbDictionaryRecord(UUID id, String name, String code, String remark, Boolean builtin, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(MbDictionary.MB_DICTIONARY);

        setId(id);
        setName(name);
        setCode(code);
        setRemark(remark);
        setBuiltin(builtin);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
