/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbInboxMessage;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbInboxMessageRecord extends UpdatableRecordImpl<MbInboxMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_inbox_message.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_inbox_message.recipient_user_id</code>.
     */
    public void setRecipientUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.recipient_user_id</code>.
     */
    public UUID getRecipientUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_inbox_message.idempotency_key</code>.
     */
    public void setIdempotencyKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_inbox_message.category</code>.
     */
    public void setCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.category</code>.
     */
    public String getCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_inbox_message.title</code>.
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_inbox_message.sender</code>.
     */
    public void setSender(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.sender</code>.
     */
    public String getSender() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_inbox_message.body</code>.
     */
    public void setBody(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.body</code>.
     */
    public String getBody() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_inbox_message.link</code>.
     */
    public void setLink(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.link</code>.
     */
    public String getLink() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_inbox_message.unread</code>.
     */
    public void setUnread(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.unread</code>.
     */
    public Boolean getUnread() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.mb_inbox_message.approval_status</code>.
     */
    public void setApprovalStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.approval_status</code>.
     */
    public String getApprovalStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_inbox_message.decided_at</code>.
     */
    public void setDecidedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.decided_at</code>.
     */
    public OffsetDateTime getDecidedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.mb_inbox_message.decided_by</code>.
     */
    public void setDecidedBy(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.decided_by</code>.
     */
    public UUID getDecidedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.mb_inbox_message.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.mb_inbox_message.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_inbox_message.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbInboxMessageRecord
     */
    public MbInboxMessageRecord() {
        super(MbInboxMessage.MB_INBOX_MESSAGE);
    }

    /**
     * Create a detached, initialised MbInboxMessageRecord
     */
    public MbInboxMessageRecord(UUID id, UUID recipientUserId, String idempotencyKey, String category, String title, String sender, String body, String link, Boolean unread, String approvalStatus, OffsetDateTime decidedAt, UUID decidedBy, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(MbInboxMessage.MB_INBOX_MESSAGE);

        setId(id);
        setRecipientUserId(recipientUserId);
        setIdempotencyKey(idempotencyKey);
        setCategory(category);
        setTitle(title);
        setSender(sender);
        setBody(body);
        setLink(link);
        setUnread(unread);
        setApprovalStatus(approvalStatus);
        setDecidedAt(decidedAt);
        setDecidedBy(decidedBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
