/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbInboxPublishOutbox;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbInboxPublishOutboxRecord extends UpdatableRecordImpl<MbInboxPublishOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.recipient_user_id</code>.
     */
    public void setRecipientUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.recipient_user_id</code>.
     */
    public UUID getRecipientUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.idempotency_key</code>.
     */
    public void setIdempotencyKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.category</code>.
     */
    public void setCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.category</code>.
     */
    public String getCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.title</code>.
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.body</code>.
     */
    public void setBody(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.body</code>.
     */
    public String getBody() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.link</code>.
     */
    public void setLink(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.link</code>.
     */
    public String getLink() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.attempts</code>.
     */
    public void setAttempts(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.attempts</code>.
     */
    public Integer getAttempts() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.worker_id</code>.
     */
    public void setWorkerId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.worker_id</code>.
     */
    public String getWorkerId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.lease_until</code>.
     */
    public void setLeaseUntil(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.lease_until</code>.
     */
    public OffsetDateTime getLeaseUntil() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.next_attempt_at</code>.
     */
    public void setNextAttemptAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.next_attempt_at</code>.
     */
    public OffsetDateTime getNextAttemptAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.last_error</code>.
     */
    public void setLastError(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.last_error</code>.
     */
    public String getLastError() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.mb_inbox_publish_outbox.processed_at</code>.
     */
    public void setProcessedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mb_inbox_publish_outbox.processed_at</code>.
     */
    public OffsetDateTime getProcessedAt() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbInboxPublishOutboxRecord
     */
    public MbInboxPublishOutboxRecord() {
        super(MbInboxPublishOutbox.MB_INBOX_PUBLISH_OUTBOX);
    }

    /**
     * Create a detached, initialised MbInboxPublishOutboxRecord
     */
    public MbInboxPublishOutboxRecord(UUID id, UUID recipientUserId, String idempotencyKey, String category, String title, String body, String link, String status, Integer attempts, String workerId, OffsetDateTime leaseUntil, OffsetDateTime nextAttemptAt, String lastError, OffsetDateTime createdAt, OffsetDateTime processedAt) {
        super(MbInboxPublishOutbox.MB_INBOX_PUBLISH_OUTBOX);

        setId(id);
        setRecipientUserId(recipientUserId);
        setIdempotencyKey(idempotencyKey);
        setCategory(category);
        setTitle(title);
        setBody(body);
        setLink(link);
        setStatus(status);
        setAttempts(attempts);
        setWorkerId(workerId);
        setLeaseUntil(leaseUntil);
        setNextAttemptAt(nextAttemptAt);
        setLastError(lastError);
        setCreatedAt(createdAt);
        setProcessedAt(processedAt);
        resetChangedOnNotNull();
    }
}
