/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbLoginAuditOutbox;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbLoginAuditOutboxRecord extends UpdatableRecordImpl<MbLoginAuditOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_login_audit_outbox.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.failure_code</code>.
     */
    public void setFailureCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.failure_code</code>.
     */
    public String getFailureCode() {
        return (String) get(4);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setIpAddress(Object value) {
        set(5, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getIpAddress() {
        return get(5);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.attempts</code>.
     */
    public void setAttempts(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.attempts</code>.
     */
    public Integer getAttempts() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.worker_id</code>.
     */
    public void setWorkerId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.worker_id</code>.
     */
    public String getWorkerId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.lease_until</code>.
     */
    public void setLeaseUntil(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.lease_until</code>.
     */
    public OffsetDateTime getLeaseUntil() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.next_attempt_at</code>.
     */
    public void setNextAttemptAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.next_attempt_at</code>.
     */
    public OffsetDateTime getNextAttemptAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.last_error</code>.
     */
    public void setLastError(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.last_error</code>.
     */
    public String getLastError() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.mb_login_audit_outbox.processed_at</code>.
     */
    public void setProcessedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mb_login_audit_outbox.processed_at</code>.
     */
    public OffsetDateTime getProcessedAt() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbLoginAuditOutboxRecord
     */
    public MbLoginAuditOutboxRecord() {
        super(MbLoginAuditOutbox.MB_LOGIN_AUDIT_OUTBOX);
    }

    /**
     * Create a detached, initialised MbLoginAuditOutboxRecord
     */
    public MbLoginAuditOutboxRecord(UUID id, UUID userId, String username, Boolean success, String failureCode, Object ipAddress, String userAgent, String status, Integer attempts, String workerId, OffsetDateTime leaseUntil, OffsetDateTime nextAttemptAt, String lastError, OffsetDateTime createdAt, OffsetDateTime processedAt) {
        super(MbLoginAuditOutbox.MB_LOGIN_AUDIT_OUTBOX);

        setId(id);
        setUserId(userId);
        setUsername(username);
        setSuccess(success);
        setFailureCode(failureCode);
        setIpAddress(ipAddress);
        setUserAgent(userAgent);
        setStatus(status);
        setAttempts(attempts);
        setWorkerId(workerId);
        setLeaseUntil(leaseUntil);
        setNextAttemptAt(nextAttemptAt);
        setLastError(lastError);
        setCreatedAt(createdAt);
        setProcessedAt(processedAt);
        resetChangedOnNotNull();
    }
}
