/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbLoginLog;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbLoginLogRecord extends UpdatableRecordImpl<MbLoginLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_login_log.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_login_log.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_login_log.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_login_log.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_login_log.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_login_log.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_login_log.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_login_log.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.mb_login_log.failure_code</code>.
     */
    public void setFailureCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_login_log.failure_code</code>.
     */
    public String getFailureCode() {
        return (String) get(4);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setIpAddress(Object value) {
        set(5, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getIpAddress() {
        return get(5);
    }

    /**
     * Setter for <code>public.mb_login_log.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_login_log.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_login_log.trace_id</code>.
     */
    public void setTraceId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_login_log.trace_id</code>.
     */
    public String getTraceId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_login_log.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_login_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbLoginLogRecord
     */
    public MbLoginLogRecord() {
        super(MbLoginLog.MB_LOGIN_LOG);
    }

    /**
     * Create a detached, initialised MbLoginLogRecord
     */
    public MbLoginLogRecord(UUID id, UUID userId, String username, Boolean success, String failureCode, Object ipAddress, String userAgent, String traceId, OffsetDateTime createdAt) {
        super(MbLoginLog.MB_LOGIN_LOG);

        setId(id);
        setUserId(userId);
        setUsername(username);
        setSuccess(success);
        setFailureCode(failureCode);
        setIpAddress(ipAddress);
        setUserAgent(userAgent);
        setTraceId(traceId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
