/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbMenuCustomization;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbMenuCustomizationRecord extends UpdatableRecordImpl<MbMenuCustomizationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_menu_customization.menu_id</code>.
     */
    public void setMenuId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.menu_id</code>.
     */
    public UUID getMenuId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_menu_customization.parent_overridden</code>.
     */
    public void setParentOverridden(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.parent_overridden</code>.
     */
    public Boolean getParentOverridden() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.mb_menu_customization.parent_id</code>.
     */
    public void setParentId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.mb_menu_customization.label_key</code>.
     */
    public void setLabelKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.label_key</code>.
     */
    public String getLabelKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_menu_customization.icon</code>.
     */
    public void setIcon(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.icon</code>.
     */
    public String getIcon() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_menu_customization.sort</code>.
     */
    public void setSort(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.sort</code>.
     */
    public Integer getSort() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.mb_menu_customization.visible</code>.
     */
    public void setVisible(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.mb_menu_customization.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.mb_menu_customization.label_zh_cn</code>.
     */
    public void setLabelZhCn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.label_zh_cn</code>.
     */
    public String getLabelZhCn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mb_menu_customization.label_en_us</code>.
     */
    public void setLabelEnUs(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.label_en_us</code>.
     */
    public String getLabelEnUs() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_menu_customization.localized_label</code>.
     */
    public void setLocalizedLabel(JSONB value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_menu_customization.localized_label</code>.
     */
    public JSONB getLocalizedLabel() {
        return (JSONB) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbMenuCustomizationRecord
     */
    public MbMenuCustomizationRecord() {
        super(MbMenuCustomization.MB_MENU_CUSTOMIZATION);
    }

    /**
     * Create a detached, initialised MbMenuCustomizationRecord
     */
    public MbMenuCustomizationRecord(UUID menuId, Boolean parentOverridden, UUID parentId, String labelKey, String icon, Integer sort, Boolean visible, OffsetDateTime updatedAt, String labelZhCn, String labelEnUs, JSONB localizedLabel) {
        super(MbMenuCustomization.MB_MENU_CUSTOMIZATION);

        setMenuId(menuId);
        setParentOverridden(parentOverridden);
        setParentId(parentId);
        setLabelKey(labelKey);
        setIcon(icon);
        setSort(sort);
        setVisible(visible);
        setUpdatedAt(updatedAt);
        setLabelZhCn(labelZhCn);
        setLabelEnUs(labelEnUs);
        setLocalizedLabel(localizedLabel);
        resetChangedOnNotNull();
    }
}
