/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbMenu;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbMenuRecord extends UpdatableRecordImpl<MbMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_menu.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_menu.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_menu.source_key</code>.
     */
    public void setSourceKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_menu.source_key</code>.
     */
    public String getSourceKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mb_menu.origin</code>.
     */
    public void setOrigin(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_menu.origin</code>.
     */
    public String getOrigin() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_menu.subsystem_key</code>.
     */
    public void setSubsystemKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_menu.subsystem_key</code>.
     */
    public String getSubsystemKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_menu.route_key</code>.
     */
    public void setRouteKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_menu.route_key</code>.
     */
    public String getRouteKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_menu.permission_id</code>.
     */
    public void setPermissionId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_menu.permission_id</code>.
     */
    public UUID getPermissionId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.mb_menu.default_parent_source_key</code>.
     */
    public void setDefaultParentSourceKey(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_menu.default_parent_source_key</code>.
     */
    public String getDefaultParentSourceKey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_menu.default_label_key</code>.
     */
    public void setDefaultLabelKey(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_menu.default_label_key</code>.
     */
    public String getDefaultLabelKey() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_menu.default_icon</code>.
     */
    public void setDefaultIcon(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_menu.default_icon</code>.
     */
    public String getDefaultIcon() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mb_menu.default_sort</code>.
     */
    public void setDefaultSort(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_menu.default_sort</code>.
     */
    public Integer getDefaultSort() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.mb_menu.default_visible</code>.
     */
    public void setDefaultVisible(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_menu.default_visible</code>.
     */
    public Boolean getDefaultVisible() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.mb_menu.status</code>.
     */
    public void setStatus(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_menu.status</code>.
     */
    public String getStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.mb_menu.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_menu.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.mb_menu.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_menu.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>public.mb_menu.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mb_menu.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbMenuRecord
     */
    public MbMenuRecord() {
        super(MbMenu.MB_MENU);
    }

    /**
     * Create a detached, initialised MbMenuRecord
     */
    public MbMenuRecord(UUID id, String sourceKey, String origin, String subsystemKey, String routeKey, UUID permissionId, String defaultParentSourceKey, String defaultLabelKey, String defaultIcon, Integer defaultSort, Boolean defaultVisible, String status, OffsetDateTime deletedAt, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(MbMenu.MB_MENU);

        setId(id);
        setSourceKey(sourceKey);
        setOrigin(origin);
        setSubsystemKey(subsystemKey);
        setRouteKey(routeKey);
        setPermissionId(permissionId);
        setDefaultParentSourceKey(defaultParentSourceKey);
        setDefaultLabelKey(defaultLabelKey);
        setDefaultIcon(defaultIcon);
        setDefaultSort(defaultSort);
        setDefaultVisible(defaultVisible);
        setStatus(status);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
