/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbOperationLog;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbOperationLogRecord extends UpdatableRecordImpl<MbOperationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_operation_log.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_operation_log.actor_id</code>.
     */
    public void setActorId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.actor_id</code>.
     */
    public UUID getActorId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_operation_log.operation</code>.
     */
    public void setOperation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.operation</code>.
     */
    public String getOperation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_operation_log.resource_type</code>.
     */
    public void setResourceType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.resource_type</code>.
     */
    public String getResourceType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_operation_log.resource_id</code>.
     */
    public void setResourceId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.resource_id</code>.
     */
    public UUID getResourceId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.mb_operation_log.request_method</code>.
     */
    public void setRequestMethod(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.request_method</code>.
     */
    public String getRequestMethod() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_operation_log.request_path</code>.
     */
    public void setRequestPath(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.request_path</code>.
     */
    public String getRequestPath() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_operation_log.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.mb_operation_log.detail</code>.
     */
    public void setDetail(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.detail</code>.
     */
    public JSONB getDetail() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.mb_operation_log.trace_id</code>.
     */
    public void setTraceId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.trace_id</code>.
     */
    public String getTraceId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_operation_log.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbOperationLogRecord
     */
    public MbOperationLogRecord() {
        super(MbOperationLog.MB_OPERATION_LOG);
    }

    /**
     * Create a detached, initialised MbOperationLogRecord
     */
    public MbOperationLogRecord(UUID id, UUID actorId, String operation, String resourceType, UUID resourceId, String requestMethod, String requestPath, Boolean success, JSONB detail, String traceId, OffsetDateTime createdAt) {
        super(MbOperationLog.MB_OPERATION_LOG);

        setId(id);
        setActorId(actorId);
        setOperation(operation);
        setResourceType(resourceType);
        setResourceId(resourceId);
        setRequestMethod(requestMethod);
        setRequestPath(requestPath);
        setSuccess(success);
        setDetail(detail);
        setTraceId(traceId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
