/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbPermissionAlias;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbPermissionAliasRecord extends UpdatableRecordImpl<MbPermissionAliasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_permission_alias.old_code</code>.
     */
    public void setOldCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_permission_alias.old_code</code>.
     */
    public String getOldCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.mb_permission_alias.permission_id</code>.
     */
    public void setPermissionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_permission_alias.permission_id</code>.
     */
    public UUID getPermissionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_permission_alias.catalog_version</code>.
     */
    public void setCatalogVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_permission_alias.catalog_version</code>.
     */
    public Integer getCatalogVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.mb_permission_alias.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_permission_alias.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbPermissionAliasRecord
     */
    public MbPermissionAliasRecord() {
        super(MbPermissionAlias.MB_PERMISSION_ALIAS);
    }

    /**
     * Create a detached, initialised MbPermissionAliasRecord
     */
    public MbPermissionAliasRecord(String oldCode, UUID permissionId, Integer catalogVersion, OffsetDateTime createdAt) {
        super(MbPermissionAlias.MB_PERMISSION_ALIAS);

        setOldCode(oldCode);
        setPermissionId(permissionId);
        setCatalogVersion(catalogVersion);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
