/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbPermission;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbPermissionRecord extends UpdatableRecordImpl<MbPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_permission.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_permission.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_permission.source_key</code>.
     */
    public void setSourceKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_permission.source_key</code>.
     */
    public String getSourceKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mb_permission.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_permission.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_permission.kind</code>.
     */
    public void setKind(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_permission.kind</code>.
     */
    public String getKind() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_permission.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_permission.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_permission.first_seen_version</code>.
     */
    public void setFirstSeenVersion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_permission.first_seen_version</code>.
     */
    public String getFirstSeenVersion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_permission.last_seen_version</code>.
     */
    public void setLastSeenVersion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_permission.last_seen_version</code>.
     */
    public String getLastSeenVersion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_permission.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_permission.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.mb_permission.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_permission.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.mb_permission.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_permission.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbPermissionRecord
     */
    public MbPermissionRecord() {
        super(MbPermission.MB_PERMISSION);
    }

    /**
     * Create a detached, initialised MbPermissionRecord
     */
    public MbPermissionRecord(UUID id, String sourceKey, String code, String kind, String status, String firstSeenVersion, String lastSeenVersion, OffsetDateTime deletedAt, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(MbPermission.MB_PERMISSION);

        setId(id);
        setSourceKey(sourceKey);
        setCode(code);
        setKind(kind);
        setStatus(status);
        setFirstSeenVersion(firstSeenVersion);
        setLastSeenVersion(lastSeenVersion);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
