/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbPermissionCatalogVersion;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbPermissionCatalogVersionRecord extends UpdatableRecordImpl<MbPermissionCatalogVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_permission_catalog_version.version</code>.
     */
    public void setVersion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_permission_catalog_version.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mb_permission_catalog_version.digest</code>.
     */
    public void setDigest(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_permission_catalog_version.digest</code>.
     */
    public String getDigest() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mb_permission_catalog_version.applied_at</code>.
     */
    public void setAppliedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_permission_catalog_version.applied_at</code>.
     */
    public OffsetDateTime getAppliedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbPermissionCatalogVersionRecord
     */
    public MbPermissionCatalogVersionRecord() {
        super(MbPermissionCatalogVersion.MB_PERMISSION_CATALOG_VERSION);
    }

    /**
     * Create a detached, initialised MbPermissionCatalogVersionRecord
     */
    public MbPermissionCatalogVersionRecord(Integer version, String digest, OffsetDateTime appliedAt) {
        super(MbPermissionCatalogVersion.MB_PERMISSION_CATALOG_VERSION);

        setVersion(version);
        setDigest(digest);
        setAppliedAt(appliedAt);
        resetChangedOnNotNull();
    }
}
