/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbRefreshToken;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbRefreshTokenRecord extends UpdatableRecordImpl<MbRefreshTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_refresh_token.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_refresh_token.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_refresh_token.family_id</code>.
     */
    public void setFamilyId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.family_id</code>.
     */
    public UUID getFamilyId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.mb_refresh_token.token_hash</code>.
     */
    public void setTokenHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.token_hash</code>.
     */
    public String getTokenHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_refresh_token.expires_at</code>.
     */
    public void setExpiresAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.mb_refresh_token.consumed_at</code>.
     */
    public void setConsumedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.consumed_at</code>.
     */
    public OffsetDateTime getConsumedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.mb_refresh_token.revoked_at</code>.
     */
    public void setRevokedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.revoked_at</code>.
     */
    public OffsetDateTime getRevokedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.mb_refresh_token.replaced_by_id</code>.
     */
    public void setReplacedById(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.replaced_by_id</code>.
     */
    public UUID getReplacedById() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.mb_refresh_token.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.mb_refresh_token.credential_revision</code>.
     */
    public void setCredentialRevision(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_refresh_token.credential_revision</code>.
     */
    public Long getCredentialRevision() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbRefreshTokenRecord
     */
    public MbRefreshTokenRecord() {
        super(MbRefreshToken.MB_REFRESH_TOKEN);
    }

    /**
     * Create a detached, initialised MbRefreshTokenRecord
     */
    public MbRefreshTokenRecord(UUID id, UUID userId, UUID familyId, String tokenHash, OffsetDateTime expiresAt, OffsetDateTime consumedAt, OffsetDateTime revokedAt, UUID replacedById, OffsetDateTime createdAt, Long credentialRevision) {
        super(MbRefreshToken.MB_REFRESH_TOKEN);

        setId(id);
        setUserId(userId);
        setFamilyId(familyId);
        setTokenHash(tokenHash);
        setExpiresAt(expiresAt);
        setConsumedAt(consumedAt);
        setRevokedAt(revokedAt);
        setReplacedById(replacedById);
        setCreatedAt(createdAt);
        setCredentialRevision(credentialRevision);
        resetChangedOnNotNull();
    }
}
