/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbRole;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbRoleRecord extends UpdatableRecordImpl<MbRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_role.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_role.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_role.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_role.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mb_role.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_role.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_role.system_role</code>.
     */
    public void setSystemRole(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_role.system_role</code>.
     */
    public Boolean getSystemRole() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.mb_role.grants_system_admin</code>.
     */
    public void setGrantsSystemAdmin(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_role.grants_system_admin</code>.
     */
    public Boolean getGrantsSystemAdmin() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.mb_role.data_scope_type</code>.
     */
    public void setDataScopeType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_role.data_scope_type</code>.
     */
    public String getDataScopeType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_role.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_role.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_role.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_role.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.mb_role.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_role.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.mb_role.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_role.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.mb_role.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_role.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbRoleRecord
     */
    public MbRoleRecord() {
        super(MbRole.MB_ROLE);
    }

    /**
     * Create a detached, initialised MbRoleRecord
     */
    public MbRoleRecord(UUID id, String code, String name, Boolean systemRole, Boolean grantsSystemAdmin, String dataScopeType, String status, OffsetDateTime deletedAt, OffsetDateTime createdAt, OffsetDateTime updatedAt, String description) {
        super(MbRole.MB_ROLE);

        setId(id);
        setCode(code);
        setName(name);
        setSystemRole(systemRole);
        setGrantsSystemAdmin(grantsSystemAdmin);
        setDataScopeType(dataScopeType);
        setStatus(status);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
