/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbRoleCustomDept;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbRoleCustomDeptRecord extends UpdatableRecordImpl<MbRoleCustomDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_role_custom_dept.role_id</code>.
     */
    public void setRoleId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_role_custom_dept.role_id</code>.
     */
    public UUID getRoleId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_role_custom_dept.dept_id</code>.
     */
    public void setDeptId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_role_custom_dept.dept_id</code>.
     */
    public UUID getDeptId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_role_custom_dept.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_role_custom_dept.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbRoleCustomDeptRecord
     */
    public MbRoleCustomDeptRecord() {
        super(MbRoleCustomDept.MB_ROLE_CUSTOM_DEPT);
    }

    /**
     * Create a detached, initialised MbRoleCustomDeptRecord
     */
    public MbRoleCustomDeptRecord(UUID roleId, UUID deptId, OffsetDateTime createdAt) {
        super(MbRoleCustomDept.MB_ROLE_CUSTOM_DEPT);

        setRoleId(roleId);
        setDeptId(deptId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
