/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbRolePermission;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbRolePermissionRecord extends UpdatableRecordImpl<MbRolePermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_role_permission.role_id</code>.
     */
    public void setRoleId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_role_permission.role_id</code>.
     */
    public UUID getRoleId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_role_permission.permission_id</code>.
     */
    public void setPermissionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_role_permission.permission_id</code>.
     */
    public UUID getPermissionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_role_permission.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_role_permission.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbRolePermissionRecord
     */
    public MbRolePermissionRecord() {
        super(MbRolePermission.MB_ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised MbRolePermissionRecord
     */
    public MbRolePermissionRecord(UUID roleId, UUID permissionId, OffsetDateTime createdAt) {
        super(MbRolePermission.MB_ROLE_PERMISSION);

        setRoleId(roleId);
        setPermissionId(permissionId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
