/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables.records;


import com.metabuild.schema.platform.tables.MbUser;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbUserRecord extends UpdatableRecordImpl<MbUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_user.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mb_user.dept_id</code>.
     */
    public void setDeptId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_user.dept_id</code>.
     */
    public UUID getDeptId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.mb_user.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_user.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_user.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_user.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_user.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_user.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_user.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_user.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_user.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_user.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_user.authz_revision</code>.
     */
    public void setAuthzRevision(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_user.authz_revision</code>.
     */
    public Long getAuthzRevision() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.mb_user.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_user.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.mb_user.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_user.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.mb_user.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_user.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.mb_user.credential_revision</code>.
     */
    public void setCredentialRevision(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_user.credential_revision</code>.
     */
    public Long getCredentialRevision() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbUserRecord
     */
    public MbUserRecord() {
        super(MbUser.MB_USER);
    }

    /**
     * Create a detached, initialised MbUserRecord
     */
    public MbUserRecord(UUID id, UUID deptId, String username, String passwordHash, String displayName, String email, String phone, String status, Long authzRevision, OffsetDateTime deletedAt, OffsetDateTime createdAt, OffsetDateTime updatedAt, Long credentialRevision) {
        super(MbUser.MB_USER);

        setId(id);
        setDeptId(deptId);
        setUsername(username);
        setPasswordHash(passwordHash);
        setDisplayName(displayName);
        setEmail(email);
        setPhone(phone);
        setStatus(status);
        setAuthzRevision(authzRevision);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCredentialRevision(credentialRevision);
        resetChangedOnNotNull();
    }
}
