/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.lastmile;


import com.metabuild.schema.lastmile.tables.BizSchemaProbe;
import com.metabuild.schema.lastmile.tables.records.BizSchemaProbeRecord;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BizSchemaProbeRecord> BIZ_SCHEMA_PROBE_PKEY = Internal.createUniqueKey(BizSchemaProbe.BIZ_SCHEMA_PROBE, DSL.name("biz_schema_probe_pkey"), new TableField[] { BizSchemaProbe.BIZ_SCHEMA_PROBE.ID }, true);
}
