/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbAuthzRefreshOutboxRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbAuthzRefreshOutbox extends TableImpl<MbAuthzRefreshOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_authz_refresh_outbox</code>
     */
    public static final MbAuthzRefreshOutbox MB_AUTHZ_REFRESH_OUTBOX = new MbAuthzRefreshOutbox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbAuthzRefreshOutboxRecord> getRecordType() {
        return MbAuthzRefreshOutboxRecord.class;
    }

    /**
     * The column <code>public.mb_authz_refresh_outbox.id</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.operation_id</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, UUID> OPERATION_ID = createField(DSL.name("operation_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.user_id</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.target_revision</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, Long> TARGET_REVISION = createField(DSL.name("target_revision"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.event_type</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.status</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.attempts</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, Integer> ATTEMPTS = createField(DSL.name("attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.worker_id</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, String> WORKER_ID = createField(DSL.name("worker_id"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.claimed_at</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, OffsetDateTime> CLAIMED_AT = createField(DSL.name("claimed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.lease_until</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, OffsetDateTime> LEASE_UNTIL = createField(DSL.name("lease_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.next_attempt_at</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, OffsetDateTime> NEXT_ATTEMPT_AT = createField(DSL.name("next_attempt_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.last_error</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.created_at</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_authz_refresh_outbox.processed_at</code>.
     */
    public final TableField<MbAuthzRefreshOutboxRecord, OffsetDateTime> PROCESSED_AT = createField(DSL.name("processed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private MbAuthzRefreshOutbox(Name alias, Table<MbAuthzRefreshOutboxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbAuthzRefreshOutbox(Name alias, Table<MbAuthzRefreshOutboxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_authz_refresh_outbox</code> table
     * reference
     */
    public MbAuthzRefreshOutbox(String alias) {
        this(DSL.name(alias), MB_AUTHZ_REFRESH_OUTBOX);
    }

    /**
     * Create an aliased <code>public.mb_authz_refresh_outbox</code> table
     * reference
     */
    public MbAuthzRefreshOutbox(Name alias) {
        this(alias, MB_AUTHZ_REFRESH_OUTBOX);
    }

    /**
     * Create a <code>public.mb_authz_refresh_outbox</code> table reference
     */
    public MbAuthzRefreshOutbox() {
        this(DSL.name("mb_authz_refresh_outbox"), null);
    }

    public <O extends Record> MbAuthzRefreshOutbox(Table<O> path, ForeignKey<O, MbAuthzRefreshOutboxRecord> childPath, InverseForeignKey<O, MbAuthzRefreshOutboxRecord> parentPath) {
        super(path, childPath, parentPath, MB_AUTHZ_REFRESH_OUTBOX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbAuthzRefreshOutboxPath extends MbAuthzRefreshOutbox implements Path<MbAuthzRefreshOutboxRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbAuthzRefreshOutboxPath(Table<O> path, ForeignKey<O, MbAuthzRefreshOutboxRecord> childPath, InverseForeignKey<O, MbAuthzRefreshOutboxRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbAuthzRefreshOutboxPath(Name alias, Table<MbAuthzRefreshOutboxRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbAuthzRefreshOutboxPath as(String alias) {
            return new MbAuthzRefreshOutboxPath(DSL.name(alias), this);
        }

        @Override
        public MbAuthzRefreshOutboxPath as(Name alias) {
            return new MbAuthzRefreshOutboxPath(alias, this);
        }

        @Override
        public MbAuthzRefreshOutboxPath as(Table<?> alias) {
            return new MbAuthzRefreshOutboxPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_AUTHZ_REFRESH_OUTBOX_PENDING_IDX, Indexes.MB_AUTHZ_REFRESH_OUTBOX_RECLAIM_IDX);
    }

    @Override
    public UniqueKey<MbAuthzRefreshOutboxRecord> getPrimaryKey() {
        return Keys.MB_AUTHZ_REFRESH_OUTBOX_PKEY;
    }

    @Override
    public List<UniqueKey<MbAuthzRefreshOutboxRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_AUTHZ_REFRESH_OUTBOX_OPERATION_ID_USER_ID_KEY);
    }

    @Override
    public List<ForeignKey<MbAuthzRefreshOutboxRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_AUTHZ_REFRESH_OUTBOX__MB_AUTHZ_REFRESH_OUTBOX_USER_ID_FKEY);
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table.
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, Keys.MB_AUTHZ_REFRESH_OUTBOX__MB_AUTHZ_REFRESH_OUTBOX_USER_ID_FKEY, null);

        return _mbUser;
    }

    @Override
    public List<Check<MbAuthzRefreshOutboxRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_authz_refresh_outbox_attempts_check"), "((attempts >= 0))", true),
            Internal.createCheck(this, DSL.name("mb_authz_refresh_outbox_claim_shape_check"), "(((((status)::text = 'PROCESSING'::text) AND (worker_id IS NOT NULL) AND (claimed_at IS NOT NULL) AND (lease_until IS NOT NULL) AND (lease_until > claimed_at)) OR (((status)::text <> 'PROCESSING'::text) AND (worker_id IS NULL) AND (claimed_at IS NULL) AND (lease_until IS NULL))))", true),
            Internal.createCheck(this, DSL.name("mb_authz_refresh_outbox_event_type_check"), "(((event_type)::text = ANY ((ARRAY['REFRESH'::character varying, 'TERMINAL'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_authz_refresh_outbox_status_check"), "(((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'DONE'::character varying, 'FAILED'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_authz_refresh_outbox_target_revision_check"), "((target_revision >= 0))", true)
        );
    }

    @Override
    public MbAuthzRefreshOutbox as(String alias) {
        return new MbAuthzRefreshOutbox(DSL.name(alias), this);
    }

    @Override
    public MbAuthzRefreshOutbox as(Name alias) {
        return new MbAuthzRefreshOutbox(alias, this);
    }

    @Override
    public MbAuthzRefreshOutbox as(Table<?> alias) {
        return new MbAuthzRefreshOutbox(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbAuthzRefreshOutbox rename(String name) {
        return new MbAuthzRefreshOutbox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbAuthzRefreshOutbox rename(Name name) {
        return new MbAuthzRefreshOutbox(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbAuthzRefreshOutbox rename(Table<?> name) {
        return new MbAuthzRefreshOutbox(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbAuthzRefreshOutbox where(Condition condition) {
        return new MbAuthzRefreshOutbox(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbAuthzRefreshOutbox where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbAuthzRefreshOutbox where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbAuthzRefreshOutbox where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbAuthzRefreshOutbox where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbAuthzRefreshOutbox where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbAuthzRefreshOutbox where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbAuthzRefreshOutbox where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbAuthzRefreshOutbox whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbAuthzRefreshOutbox whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
