/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.records.MbCompanyRecord;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbCompany extends TableImpl<MbCompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_company</code>
     */
    public static final MbCompany MB_COMPANY = new MbCompany();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbCompanyRecord> getRecordType() {
        return MbCompanyRecord.class;
    }

    /**
     * The column <code>public.mb_company.id</code>.
     */
    public final TableField<MbCompanyRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_company.name</code>.
     */
    public final TableField<MbCompanyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.verified</code>.
     */
    public final TableField<MbCompanyRecord, Boolean> VERIFIED = createField(DSL.name("verified"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_company.domain</code>.
     */
    public final TableField<MbCompanyRecord, String> DOMAIN = createField(DSL.name("domain"), SQLDataType.VARCHAR(253).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.code</code>.
     */
    public final TableField<MbCompanyRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.industry</code>.
     */
    public final TableField<MbCompanyRecord, String> INDUSTRY = createField(DSL.name("industry"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.scale</code>.
     */
    public final TableField<MbCompanyRecord, String> SCALE = createField(DSL.name("scale"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.data_residency</code>.
     */
    public final TableField<MbCompanyRecord, String> DATA_RESIDENCY = createField(DSL.name("data_residency"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.created_date</code>.
     */
    public final TableField<MbCompanyRecord, LocalDate> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.mb_company.contact_name</code>.
     */
    public final TableField<MbCompanyRecord, String> CONTACT_NAME = createField(DSL.name("contact_name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.contact_email</code>.
     */
    public final TableField<MbCompanyRecord, String> CONTACT_EMAIL = createField(DSL.name("contact_email"), SQLDataType.VARCHAR(320).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.contact_phone</code>.
     */
    public final TableField<MbCompanyRecord, String> CONTACT_PHONE = createField(DSL.name("contact_phone"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.landline</code>.
     */
    public final TableField<MbCompanyRecord, String> LANDLINE = createField(DSL.name("landline"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_company.address</code>.
     */
    public final TableField<MbCompanyRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.postal_code</code>.
     */
    public final TableField<MbCompanyRecord, String> POSTAL_CODE = createField(DSL.name("postal_code"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.mb_company.updated_at</code>.
     */
    public final TableField<MbCompanyRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_company.singleton_key</code>.
     */
    public final TableField<MbCompanyRecord, Short> SINGLETON_KEY = createField(DSL.name("singleton_key"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    private MbCompany(Name alias, Table<MbCompanyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbCompany(Name alias, Table<MbCompanyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_company</code> table reference
     */
    public MbCompany(String alias) {
        this(DSL.name(alias), MB_COMPANY);
    }

    /**
     * Create an aliased <code>public.mb_company</code> table reference
     */
    public MbCompany(Name alias) {
        this(alias, MB_COMPANY);
    }

    /**
     * Create a <code>public.mb_company</code> table reference
     */
    public MbCompany() {
        this(DSL.name("mb_company"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbCompanyRecord> getPrimaryKey() {
        return Keys.MB_COMPANY_PKEY;
    }

    @Override
    public List<UniqueKey<MbCompanyRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_COMPANY_CODE_KEY, Keys.MB_COMPANY_SINGLETON);
    }

    @Override
    public List<Check<MbCompanyRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_company_singleton_key"), "((singleton_key = 1))", true)
        );
    }

    @Override
    public MbCompany as(String alias) {
        return new MbCompany(DSL.name(alias), this);
    }

    @Override
    public MbCompany as(Name alias) {
        return new MbCompany(alias, this);
    }

    @Override
    public MbCompany as(Table<?> alias) {
        return new MbCompany(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbCompany rename(String name) {
        return new MbCompany(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbCompany rename(Name name) {
        return new MbCompany(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbCompany rename(Table<?> name) {
        return new MbCompany(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbCompany where(Condition condition) {
        return new MbCompany(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbCompany where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbCompany where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbCompany where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbCompany where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbCompany where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbCompany where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbCompany where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbCompany whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbCompany whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
