/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbDept.MbDeptPath;
import com.metabuild.schema.platform.tables.MbRole.MbRolePath;
import com.metabuild.schema.platform.tables.MbRoleCustomDept.MbRoleCustomDeptPath;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbDeptRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDept extends TableImpl<MbDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_dept</code>
     */
    public static final MbDept MB_DEPT = new MbDept();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbDeptRecord> getRecordType() {
        return MbDeptRecord.class;
    }

    /**
     * The column <code>public.mb_dept.id</code>.
     */
    public final TableField<MbDeptRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_dept.parent_id</code>.
     */
    public final TableField<MbDeptRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_dept.code</code>.
     */
    public final TableField<MbDeptRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_dept.name</code>.
     */
    public final TableField<MbDeptRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_dept.status</code>.
     */
    public final TableField<MbDeptRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_dept.sort_order</code>.
     */
    public final TableField<MbDeptRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_dept.deleted_at</code>.
     */
    public final TableField<MbDeptRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_dept.created_at</code>.
     */
    public final TableField<MbDeptRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_dept.updated_at</code>.
     */
    public final TableField<MbDeptRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbDept(Name alias, Table<MbDeptRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbDept(Name alias, Table<MbDeptRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_dept</code> table reference
     */
    public MbDept(String alias) {
        this(DSL.name(alias), MB_DEPT);
    }

    /**
     * Create an aliased <code>public.mb_dept</code> table reference
     */
    public MbDept(Name alias) {
        this(alias, MB_DEPT);
    }

    /**
     * Create a <code>public.mb_dept</code> table reference
     */
    public MbDept() {
        this(DSL.name("mb_dept"), null);
    }

    public <O extends Record> MbDept(Table<O> path, ForeignKey<O, MbDeptRecord> childPath, InverseForeignKey<O, MbDeptRecord> parentPath) {
        super(path, childPath, parentPath, MB_DEPT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbDeptPath extends MbDept implements Path<MbDeptRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbDeptPath(Table<O> path, ForeignKey<O, MbDeptRecord> childPath, InverseForeignKey<O, MbDeptRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbDeptPath(Name alias, Table<MbDeptRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbDeptPath as(String alias) {
            return new MbDeptPath(DSL.name(alias), this);
        }

        @Override
        public MbDeptPath as(Name alias) {
            return new MbDeptPath(alias, this);
        }

        @Override
        public MbDeptPath as(Table<?> alias) {
            return new MbDeptPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_DEPT_PARENT_ACTIVE_IDX);
    }

    @Override
    public UniqueKey<MbDeptRecord> getPrimaryKey() {
        return Keys.MB_DEPT_PKEY;
    }

    @Override
    public List<ForeignKey<MbDeptRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_DEPT__MB_DEPT_PARENT_ID_FKEY);
    }

    private transient MbDeptPath _mbDept;

    /**
     * Get the implicit join path to the <code>public.mb_dept</code> table.
     */
    public MbDeptPath mbDept() {
        if (_mbDept == null)
            _mbDept = new MbDeptPath(this, Keys.MB_DEPT__MB_DEPT_PARENT_ID_FKEY, null);

        return _mbDept;
    }

    private transient MbRoleCustomDeptPath _mbRoleCustomDept;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_role_custom_dept</code> table
     */
    public MbRoleCustomDeptPath mbRoleCustomDept() {
        if (_mbRoleCustomDept == null)
            _mbRoleCustomDept = new MbRoleCustomDeptPath(this, null, Keys.MB_ROLE_CUSTOM_DEPT__MB_ROLE_CUSTOM_DEPT_DEPT_ID_FKEY.getInverseKey());

        return _mbRoleCustomDept;
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit to-many join path to the <code>public.mb_user</code>
     * table
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, null, Keys.MB_USER__MB_USER_DEPT_ID_FKEY.getInverseKey());

        return _mbUser;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_role</code> table
     */
    public MbRolePath mbRole() {
        return mbRoleCustomDept().mbRole();
    }

    @Override
    public List<Check<MbDeptRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_dept_not_self_parent"), "(((parent_id IS NULL) OR (parent_id <> id)))", true),
            Internal.createCheck(this, DSL.name("mb_dept_status_check"), "(((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbDept as(String alias) {
        return new MbDept(DSL.name(alias), this);
    }

    @Override
    public MbDept as(Name alias) {
        return new MbDept(alias, this);
    }

    @Override
    public MbDept as(Table<?> alias) {
        return new MbDept(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDept rename(String name) {
        return new MbDept(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDept rename(Name name) {
        return new MbDept(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDept rename(Table<?> name) {
        return new MbDept(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDept where(Condition condition) {
        return new MbDept(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDept where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDept where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDept where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDept where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDept where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDept where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDept where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDept whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDept whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
