/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbDictionary.MbDictionaryPath;
import com.metabuild.schema.platform.tables.records.MbDictionaryItemRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDictionaryItem extends TableImpl<MbDictionaryItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_dictionary_item</code>
     */
    public static final MbDictionaryItem MB_DICTIONARY_ITEM = new MbDictionaryItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbDictionaryItemRecord> getRecordType() {
        return MbDictionaryItemRecord.class;
    }

    /**
     * The column <code>public.mb_dictionary_item.id</code>.
     */
    public final TableField<MbDictionaryItemRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary_item.dictionary_id</code>.
     */
    public final TableField<MbDictionaryItemRecord, UUID> DICTIONARY_ID = createField(DSL.name("dictionary_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary_item.label</code>.
     */
    public final TableField<MbDictionaryItemRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary_item.value</code>.
     */
    public final TableField<MbDictionaryItemRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary_item.sort</code>.
     */
    public final TableField<MbDictionaryItemRecord, Integer> SORT = createField(DSL.name("sort"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary_item.enabled</code>.
     */
    public final TableField<MbDictionaryItemRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_dictionary_item.color</code>.
     */
    public final TableField<MbDictionaryItemRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary_item.remark</code>.
     */
    public final TableField<MbDictionaryItemRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_dictionary_item.created_at</code>.
     */
    public final TableField<MbDictionaryItemRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_dictionary_item.updated_at</code>.
     */
    public final TableField<MbDictionaryItemRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbDictionaryItem(Name alias, Table<MbDictionaryItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbDictionaryItem(Name alias, Table<MbDictionaryItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_dictionary_item</code> table reference
     */
    public MbDictionaryItem(String alias) {
        this(DSL.name(alias), MB_DICTIONARY_ITEM);
    }

    /**
     * Create an aliased <code>public.mb_dictionary_item</code> table reference
     */
    public MbDictionaryItem(Name alias) {
        this(alias, MB_DICTIONARY_ITEM);
    }

    /**
     * Create a <code>public.mb_dictionary_item</code> table reference
     */
    public MbDictionaryItem() {
        this(DSL.name("mb_dictionary_item"), null);
    }

    public <O extends Record> MbDictionaryItem(Table<O> path, ForeignKey<O, MbDictionaryItemRecord> childPath, InverseForeignKey<O, MbDictionaryItemRecord> parentPath) {
        super(path, childPath, parentPath, MB_DICTIONARY_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbDictionaryItemPath extends MbDictionaryItem implements Path<MbDictionaryItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbDictionaryItemPath(Table<O> path, ForeignKey<O, MbDictionaryItemRecord> childPath, InverseForeignKey<O, MbDictionaryItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbDictionaryItemPath(Name alias, Table<MbDictionaryItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbDictionaryItemPath as(String alias) {
            return new MbDictionaryItemPath(DSL.name(alias), this);
        }

        @Override
        public MbDictionaryItemPath as(Name alias) {
            return new MbDictionaryItemPath(alias, this);
        }

        @Override
        public MbDictionaryItemPath as(Table<?> alias) {
            return new MbDictionaryItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_DICTIONARY_ITEM_ORDER);
    }

    @Override
    public UniqueKey<MbDictionaryItemRecord> getPrimaryKey() {
        return Keys.MB_DICTIONARY_ITEM_PKEY;
    }

    @Override
    public List<UniqueKey<MbDictionaryItemRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_DICTIONARY_ITEM_VALUE_UNIQUE);
    }

    @Override
    public List<ForeignKey<MbDictionaryItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_DICTIONARY_ITEM__MB_DICTIONARY_ITEM_DICTIONARY_ID_FKEY);
    }

    private transient MbDictionaryPath _mbDictionary;

    /**
     * Get the implicit join path to the <code>public.mb_dictionary</code>
     * table.
     */
    public MbDictionaryPath mbDictionary() {
        if (_mbDictionary == null)
            _mbDictionary = new MbDictionaryPath(this, Keys.MB_DICTIONARY_ITEM__MB_DICTIONARY_ITEM_DICTIONARY_ID_FKEY, null);

        return _mbDictionary;
    }

    @Override
    public List<Check<MbDictionaryItemRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_dictionary_item_color"), "(((color)::text = ANY ((ARRAY['primary'::character varying, 'success'::character varying, 'warning'::character varying, 'danger'::character varying, 'neutral'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbDictionaryItem as(String alias) {
        return new MbDictionaryItem(DSL.name(alias), this);
    }

    @Override
    public MbDictionaryItem as(Name alias) {
        return new MbDictionaryItem(alias, this);
    }

    @Override
    public MbDictionaryItem as(Table<?> alias) {
        return new MbDictionaryItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictionaryItem rename(String name) {
        return new MbDictionaryItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictionaryItem rename(Name name) {
        return new MbDictionaryItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictionaryItem rename(Table<?> name) {
        return new MbDictionaryItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionaryItem where(Condition condition) {
        return new MbDictionaryItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionaryItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionaryItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionaryItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionaryItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionaryItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionaryItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionaryItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionaryItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionaryItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
