/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbDictionaryItem.MbDictionaryItemPath;
import com.metabuild.schema.platform.tables.records.MbDictionaryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDictionary extends TableImpl<MbDictionaryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_dictionary</code>
     */
    public static final MbDictionary MB_DICTIONARY = new MbDictionary();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbDictionaryRecord> getRecordType() {
        return MbDictionaryRecord.class;
    }

    /**
     * The column <code>public.mb_dictionary.id</code>.
     */
    public final TableField<MbDictionaryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary.name</code>.
     */
    public final TableField<MbDictionaryRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary.code</code>.
     */
    public final TableField<MbDictionaryRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_dictionary.remark</code>.
     */
    public final TableField<MbDictionaryRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_dictionary.builtin</code>.
     */
    public final TableField<MbDictionaryRecord, Boolean> BUILTIN = createField(DSL.name("builtin"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_dictionary.created_at</code>.
     */
    public final TableField<MbDictionaryRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_dictionary.updated_at</code>.
     */
    public final TableField<MbDictionaryRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbDictionary(Name alias, Table<MbDictionaryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbDictionary(Name alias, Table<MbDictionaryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_dictionary</code> table reference
     */
    public MbDictionary(String alias) {
        this(DSL.name(alias), MB_DICTIONARY);
    }

    /**
     * Create an aliased <code>public.mb_dictionary</code> table reference
     */
    public MbDictionary(Name alias) {
        this(alias, MB_DICTIONARY);
    }

    /**
     * Create a <code>public.mb_dictionary</code> table reference
     */
    public MbDictionary() {
        this(DSL.name("mb_dictionary"), null);
    }

    public <O extends Record> MbDictionary(Table<O> path, ForeignKey<O, MbDictionaryRecord> childPath, InverseForeignKey<O, MbDictionaryRecord> parentPath) {
        super(path, childPath, parentPath, MB_DICTIONARY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbDictionaryPath extends MbDictionary implements Path<MbDictionaryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbDictionaryPath(Table<O> path, ForeignKey<O, MbDictionaryRecord> childPath, InverseForeignKey<O, MbDictionaryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbDictionaryPath(Name alias, Table<MbDictionaryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbDictionaryPath as(String alias) {
            return new MbDictionaryPath(DSL.name(alias), this);
        }

        @Override
        public MbDictionaryPath as(Name alias) {
            return new MbDictionaryPath(alias, this);
        }

        @Override
        public MbDictionaryPath as(Table<?> alias) {
            return new MbDictionaryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbDictionaryRecord> getPrimaryKey() {
        return Keys.MB_DICTIONARY_PKEY;
    }

    @Override
    public List<UniqueKey<MbDictionaryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_DICTIONARY_CODE_UNIQUE);
    }

    private transient MbDictionaryItemPath _mbDictionaryItem;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_dictionary_item</code> table
     */
    public MbDictionaryItemPath mbDictionaryItem() {
        if (_mbDictionaryItem == null)
            _mbDictionaryItem = new MbDictionaryItemPath(this, null, Keys.MB_DICTIONARY_ITEM__MB_DICTIONARY_ITEM_DICTIONARY_ID_FKEY.getInverseKey());

        return _mbDictionaryItem;
    }

    @Override
    public List<Check<MbDictionaryRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_dictionary_code_format"), "(((code)::text ~ '^[a-z][a-z0-9_]*$'::text))", true)
        );
    }

    @Override
    public MbDictionary as(String alias) {
        return new MbDictionary(DSL.name(alias), this);
    }

    @Override
    public MbDictionary as(Name alias) {
        return new MbDictionary(alias, this);
    }

    @Override
    public MbDictionary as(Table<?> alias) {
        return new MbDictionary(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictionary rename(String name) {
        return new MbDictionary(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictionary rename(Name name) {
        return new MbDictionary(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictionary rename(Table<?> name) {
        return new MbDictionary(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionary where(Condition condition) {
        return new MbDictionary(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionary where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionary where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionary where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionary where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionary where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionary where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictionary where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionary whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictionary whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
