/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbInboxMessageRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbInboxMessage extends TableImpl<MbInboxMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_inbox_message</code>
     */
    public static final MbInboxMessage MB_INBOX_MESSAGE = new MbInboxMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbInboxMessageRecord> getRecordType() {
        return MbInboxMessageRecord.class;
    }

    /**
     * The column <code>public.mb_inbox_message.id</code>.
     */
    public final TableField<MbInboxMessageRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_message.recipient_user_id</code>.
     */
    public final TableField<MbInboxMessageRecord, UUID> RECIPIENT_USER_ID = createField(DSL.name("recipient_user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_message.idempotency_key</code>.
     */
    public final TableField<MbInboxMessageRecord, String> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_message.category</code>.
     */
    public final TableField<MbInboxMessageRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_message.title</code>.
     */
    public final TableField<MbInboxMessageRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_message.sender</code>.
     */
    public final TableField<MbInboxMessageRecord, String> SENDER = createField(DSL.name("sender"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_message.body</code>.
     */
    public final TableField<MbInboxMessageRecord, String> BODY = createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_message.link</code>.
     */
    public final TableField<MbInboxMessageRecord, String> LINK = createField(DSL.name("link"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.mb_inbox_message.unread</code>.
     */
    public final TableField<MbInboxMessageRecord, Boolean> UNREAD = createField(DSL.name("unread"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_inbox_message.approval_status</code>.
     */
    public final TableField<MbInboxMessageRecord, String> APPROVAL_STATUS = createField(DSL.name("approval_status"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>public.mb_inbox_message.decided_at</code>.
     */
    public final TableField<MbInboxMessageRecord, OffsetDateTime> DECIDED_AT = createField(DSL.name("decided_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_inbox_message.decided_by</code>.
     */
    public final TableField<MbInboxMessageRecord, UUID> DECIDED_BY = createField(DSL.name("decided_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_inbox_message.created_at</code>.
     */
    public final TableField<MbInboxMessageRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_inbox_message.updated_at</code>.
     */
    public final TableField<MbInboxMessageRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbInboxMessage(Name alias, Table<MbInboxMessageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbInboxMessage(Name alias, Table<MbInboxMessageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_inbox_message</code> table reference
     */
    public MbInboxMessage(String alias) {
        this(DSL.name(alias), MB_INBOX_MESSAGE);
    }

    /**
     * Create an aliased <code>public.mb_inbox_message</code> table reference
     */
    public MbInboxMessage(Name alias) {
        this(alias, MB_INBOX_MESSAGE);
    }

    /**
     * Create a <code>public.mb_inbox_message</code> table reference
     */
    public MbInboxMessage() {
        this(DSL.name("mb_inbox_message"), null);
    }

    public <O extends Record> MbInboxMessage(Table<O> path, ForeignKey<O, MbInboxMessageRecord> childPath, InverseForeignKey<O, MbInboxMessageRecord> parentPath) {
        super(path, childPath, parentPath, MB_INBOX_MESSAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbInboxMessagePath extends MbInboxMessage implements Path<MbInboxMessageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbInboxMessagePath(Table<O> path, ForeignKey<O, MbInboxMessageRecord> childPath, InverseForeignKey<O, MbInboxMessageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbInboxMessagePath(Name alias, Table<MbInboxMessageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbInboxMessagePath as(String alias) {
            return new MbInboxMessagePath(DSL.name(alias), this);
        }

        @Override
        public MbInboxMessagePath as(Name alias) {
            return new MbInboxMessagePath(alias, this);
        }

        @Override
        public MbInboxMessagePath as(Table<?> alias) {
            return new MbInboxMessagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_INBOX_RECIPIENT_CREATED_IDX, Indexes.MB_INBOX_RECIPIENT_UNREAD_IDX);
    }

    @Override
    public UniqueKey<MbInboxMessageRecord> getPrimaryKey() {
        return Keys.MB_INBOX_MESSAGE_PKEY;
    }

    @Override
    public List<UniqueKey<MbInboxMessageRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_INBOX_MESSAGE_RECIPIENT_USER_ID_IDEMPOTENCY_KEY_KEY);
    }

    @Override
    public List<ForeignKey<MbInboxMessageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_INBOX_MESSAGE__MB_INBOX_MESSAGE_DECIDED_BY_FKEY, Keys.MB_INBOX_MESSAGE__MB_INBOX_MESSAGE_RECIPIENT_USER_ID_FKEY);
    }

    private transient MbUserPath _mbInboxMessageDecidedByFkey;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table, via
     * the <code>mb_inbox_message_decided_by_fkey</code> key.
     */
    public MbUserPath mbInboxMessageDecidedByFkey() {
        if (_mbInboxMessageDecidedByFkey == null)
            _mbInboxMessageDecidedByFkey = new MbUserPath(this, Keys.MB_INBOX_MESSAGE__MB_INBOX_MESSAGE_DECIDED_BY_FKEY, null);

        return _mbInboxMessageDecidedByFkey;
    }

    private transient MbUserPath _mbInboxMessageRecipientUserIdFkey;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table, via
     * the <code>mb_inbox_message_recipient_user_id_fkey</code> key.
     */
    public MbUserPath mbInboxMessageRecipientUserIdFkey() {
        if (_mbInboxMessageRecipientUserIdFkey == null)
            _mbInboxMessageRecipientUserIdFkey = new MbUserPath(this, Keys.MB_INBOX_MESSAGE__MB_INBOX_MESSAGE_RECIPIENT_USER_ID_FKEY, null);

        return _mbInboxMessageRecipientUserIdFkey;
    }

    @Override
    public List<Check<MbInboxMessageRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_inbox_approval_shape"), "(((((category)::text = 'approval'::text) AND (approval_status IS NOT NULL)) OR (((category)::text <> 'approval'::text) AND (approval_status IS NULL))))", true),
            Internal.createCheck(this, DSL.name("mb_inbox_message_approval_status_check"), "(((approval_status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_inbox_message_category_check"), "(((category)::text = ANY ((ARRAY['approval'::character varying, 'security'::character varying, 'system'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbInboxMessage as(String alias) {
        return new MbInboxMessage(DSL.name(alias), this);
    }

    @Override
    public MbInboxMessage as(Name alias) {
        return new MbInboxMessage(alias, this);
    }

    @Override
    public MbInboxMessage as(Table<?> alias) {
        return new MbInboxMessage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbInboxMessage rename(String name) {
        return new MbInboxMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbInboxMessage rename(Name name) {
        return new MbInboxMessage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbInboxMessage rename(Table<?> name) {
        return new MbInboxMessage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxMessage where(Condition condition) {
        return new MbInboxMessage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxMessage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxMessage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxMessage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxMessage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxMessage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxMessage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxMessage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxMessage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxMessage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
