/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbInboxPublishOutboxRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbInboxPublishOutbox extends TableImpl<MbInboxPublishOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_inbox_publish_outbox</code>
     */
    public static final MbInboxPublishOutbox MB_INBOX_PUBLISH_OUTBOX = new MbInboxPublishOutbox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbInboxPublishOutboxRecord> getRecordType() {
        return MbInboxPublishOutboxRecord.class;
    }

    /**
     * The column <code>public.mb_inbox_publish_outbox.id</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.recipient_user_id</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, UUID> RECIPIENT_USER_ID = createField(DSL.name("recipient_user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.idempotency_key</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.category</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.title</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.body</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> BODY = createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.link</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> LINK = createField(DSL.name("link"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.status</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.attempts</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, Integer> ATTEMPTS = createField(DSL.name("attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.worker_id</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> WORKER_ID = createField(DSL.name("worker_id"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.lease_until</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, OffsetDateTime> LEASE_UNTIL = createField(DSL.name("lease_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.next_attempt_at</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, OffsetDateTime> NEXT_ATTEMPT_AT = createField(DSL.name("next_attempt_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.last_error</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.created_at</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_inbox_publish_outbox.processed_at</code>.
     */
    public final TableField<MbInboxPublishOutboxRecord, OffsetDateTime> PROCESSED_AT = createField(DSL.name("processed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private MbInboxPublishOutbox(Name alias, Table<MbInboxPublishOutboxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbInboxPublishOutbox(Name alias, Table<MbInboxPublishOutboxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_inbox_publish_outbox</code> table
     * reference
     */
    public MbInboxPublishOutbox(String alias) {
        this(DSL.name(alias), MB_INBOX_PUBLISH_OUTBOX);
    }

    /**
     * Create an aliased <code>public.mb_inbox_publish_outbox</code> table
     * reference
     */
    public MbInboxPublishOutbox(Name alias) {
        this(alias, MB_INBOX_PUBLISH_OUTBOX);
    }

    /**
     * Create a <code>public.mb_inbox_publish_outbox</code> table reference
     */
    public MbInboxPublishOutbox() {
        this(DSL.name("mb_inbox_publish_outbox"), null);
    }

    public <O extends Record> MbInboxPublishOutbox(Table<O> path, ForeignKey<O, MbInboxPublishOutboxRecord> childPath, InverseForeignKey<O, MbInboxPublishOutboxRecord> parentPath) {
        super(path, childPath, parentPath, MB_INBOX_PUBLISH_OUTBOX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbInboxPublishOutboxPath extends MbInboxPublishOutbox implements Path<MbInboxPublishOutboxRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbInboxPublishOutboxPath(Table<O> path, ForeignKey<O, MbInboxPublishOutboxRecord> childPath, InverseForeignKey<O, MbInboxPublishOutboxRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbInboxPublishOutboxPath(Name alias, Table<MbInboxPublishOutboxRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbInboxPublishOutboxPath as(String alias) {
            return new MbInboxPublishOutboxPath(DSL.name(alias), this);
        }

        @Override
        public MbInboxPublishOutboxPath as(Name alias) {
            return new MbInboxPublishOutboxPath(alias, this);
        }

        @Override
        public MbInboxPublishOutboxPath as(Table<?> alias) {
            return new MbInboxPublishOutboxPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_INBOX_PUBLISH_READY_IDX);
    }

    @Override
    public UniqueKey<MbInboxPublishOutboxRecord> getPrimaryKey() {
        return Keys.MB_INBOX_PUBLISH_OUTBOX_PKEY;
    }

    @Override
    public List<UniqueKey<MbInboxPublishOutboxRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_INBOX_PUBLISH_OUTBOX_RECIPIENT_USER_ID_IDEMPOTENCY_KEY_KEY);
    }

    @Override
    public List<ForeignKey<MbInboxPublishOutboxRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_INBOX_PUBLISH_OUTBOX__MB_INBOX_PUBLISH_OUTBOX_RECIPIENT_USER_ID_FKEY);
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table.
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, Keys.MB_INBOX_PUBLISH_OUTBOX__MB_INBOX_PUBLISH_OUTBOX_RECIPIENT_USER_ID_FKEY, null);

        return _mbUser;
    }

    @Override
    public List<Check<MbInboxPublishOutboxRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_inbox_publish_claim_shape"), "(((((status)::text = 'PROCESSING'::text) AND (worker_id IS NOT NULL) AND (lease_until IS NOT NULL)) OR (((status)::text <> 'PROCESSING'::text) AND (worker_id IS NULL) AND (lease_until IS NULL))))", true),
            Internal.createCheck(this, DSL.name("mb_inbox_publish_outbox_attempts_check"), "((attempts >= 0))", true),
            Internal.createCheck(this, DSL.name("mb_inbox_publish_outbox_category_check"), "(((category)::text = ANY ((ARRAY['approval'::character varying, 'security'::character varying, 'system'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_inbox_publish_outbox_status_check"), "(((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'DONE'::character varying, 'FAILED'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbInboxPublishOutbox as(String alias) {
        return new MbInboxPublishOutbox(DSL.name(alias), this);
    }

    @Override
    public MbInboxPublishOutbox as(Name alias) {
        return new MbInboxPublishOutbox(alias, this);
    }

    @Override
    public MbInboxPublishOutbox as(Table<?> alias) {
        return new MbInboxPublishOutbox(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbInboxPublishOutbox rename(String name) {
        return new MbInboxPublishOutbox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbInboxPublishOutbox rename(Name name) {
        return new MbInboxPublishOutbox(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbInboxPublishOutbox rename(Table<?> name) {
        return new MbInboxPublishOutbox(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxPublishOutbox where(Condition condition) {
        return new MbInboxPublishOutbox(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxPublishOutbox where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxPublishOutbox where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxPublishOutbox where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxPublishOutbox where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxPublishOutbox where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxPublishOutbox where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbInboxPublishOutbox where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxPublishOutbox whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbInboxPublishOutbox whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
