/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbLoginAuditOutboxRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbLoginAuditOutbox extends TableImpl<MbLoginAuditOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_login_audit_outbox</code>
     */
    public static final MbLoginAuditOutbox MB_LOGIN_AUDIT_OUTBOX = new MbLoginAuditOutbox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbLoginAuditOutboxRecord> getRecordType() {
        return MbLoginAuditOutboxRecord.class;
    }

    /**
     * The column <code>public.mb_login_audit_outbox.id</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.user_id</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.username</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.success</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.failure_code</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, String> FAILURE_CODE = createField(DSL.name("failure_code"), SQLDataType.VARCHAR(160), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<MbLoginAuditOutboxRecord, Object> IP_ADDRESS = createField(DSL.name("ip_address"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\""), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.user_agent</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.status</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.attempts</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, Integer> ATTEMPTS = createField(DSL.name("attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.worker_id</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, String> WORKER_ID = createField(DSL.name("worker_id"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.lease_until</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, OffsetDateTime> LEASE_UNTIL = createField(DSL.name("lease_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.next_attempt_at</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, OffsetDateTime> NEXT_ATTEMPT_AT = createField(DSL.name("next_attempt_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.last_error</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.created_at</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_login_audit_outbox.processed_at</code>.
     */
    public final TableField<MbLoginAuditOutboxRecord, OffsetDateTime> PROCESSED_AT = createField(DSL.name("processed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private MbLoginAuditOutbox(Name alias, Table<MbLoginAuditOutboxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbLoginAuditOutbox(Name alias, Table<MbLoginAuditOutboxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_login_audit_outbox</code> table
     * reference
     */
    public MbLoginAuditOutbox(String alias) {
        this(DSL.name(alias), MB_LOGIN_AUDIT_OUTBOX);
    }

    /**
     * Create an aliased <code>public.mb_login_audit_outbox</code> table
     * reference
     */
    public MbLoginAuditOutbox(Name alias) {
        this(alias, MB_LOGIN_AUDIT_OUTBOX);
    }

    /**
     * Create a <code>public.mb_login_audit_outbox</code> table reference
     */
    public MbLoginAuditOutbox() {
        this(DSL.name("mb_login_audit_outbox"), null);
    }

    public <O extends Record> MbLoginAuditOutbox(Table<O> path, ForeignKey<O, MbLoginAuditOutboxRecord> childPath, InverseForeignKey<O, MbLoginAuditOutboxRecord> parentPath) {
        super(path, childPath, parentPath, MB_LOGIN_AUDIT_OUTBOX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbLoginAuditOutboxPath extends MbLoginAuditOutbox implements Path<MbLoginAuditOutboxRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbLoginAuditOutboxPath(Table<O> path, ForeignKey<O, MbLoginAuditOutboxRecord> childPath, InverseForeignKey<O, MbLoginAuditOutboxRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbLoginAuditOutboxPath(Name alias, Table<MbLoginAuditOutboxRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbLoginAuditOutboxPath as(String alias) {
            return new MbLoginAuditOutboxPath(DSL.name(alias), this);
        }

        @Override
        public MbLoginAuditOutboxPath as(Name alias) {
            return new MbLoginAuditOutboxPath(alias, this);
        }

        @Override
        public MbLoginAuditOutboxPath as(Table<?> alias) {
            return new MbLoginAuditOutboxPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_LOGIN_AUDIT_READY_IDX);
    }

    @Override
    public UniqueKey<MbLoginAuditOutboxRecord> getPrimaryKey() {
        return Keys.MB_LOGIN_AUDIT_OUTBOX_PKEY;
    }

    @Override
    public List<ForeignKey<MbLoginAuditOutboxRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_LOGIN_AUDIT_OUTBOX__MB_LOGIN_AUDIT_OUTBOX_USER_ID_FKEY);
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table.
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, Keys.MB_LOGIN_AUDIT_OUTBOX__MB_LOGIN_AUDIT_OUTBOX_USER_ID_FKEY, null);

        return _mbUser;
    }

    @Override
    public List<Check<MbLoginAuditOutboxRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_login_audit_claim_shape"), "(((((status)::text = 'PROCESSING'::text) AND (worker_id IS NOT NULL) AND (lease_until IS NOT NULL)) OR (((status)::text <> 'PROCESSING'::text) AND (worker_id IS NULL) AND (lease_until IS NULL))))", true),
            Internal.createCheck(this, DSL.name("mb_login_audit_outbox_attempts_check"), "((attempts >= 0))", true),
            Internal.createCheck(this, DSL.name("mb_login_audit_outbox_status_check"), "(((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'DONE'::character varying, 'FAILED'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbLoginAuditOutbox as(String alias) {
        return new MbLoginAuditOutbox(DSL.name(alias), this);
    }

    @Override
    public MbLoginAuditOutbox as(Name alias) {
        return new MbLoginAuditOutbox(alias, this);
    }

    @Override
    public MbLoginAuditOutbox as(Table<?> alias) {
        return new MbLoginAuditOutbox(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbLoginAuditOutbox rename(String name) {
        return new MbLoginAuditOutbox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbLoginAuditOutbox rename(Name name) {
        return new MbLoginAuditOutbox(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbLoginAuditOutbox rename(Table<?> name) {
        return new MbLoginAuditOutbox(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLoginAuditOutbox where(Condition condition) {
        return new MbLoginAuditOutbox(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLoginAuditOutbox where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLoginAuditOutbox where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLoginAuditOutbox where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLoginAuditOutbox where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLoginAuditOutbox where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLoginAuditOutbox where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLoginAuditOutbox where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLoginAuditOutbox whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLoginAuditOutbox whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
