/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbMenu.MbMenuPath;
import com.metabuild.schema.platform.tables.records.MbMenuCustomizationRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbMenuCustomization extends TableImpl<MbMenuCustomizationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_menu_customization</code>
     */
    public static final MbMenuCustomization MB_MENU_CUSTOMIZATION = new MbMenuCustomization();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbMenuCustomizationRecord> getRecordType() {
        return MbMenuCustomizationRecord.class;
    }

    /**
     * The column <code>public.mb_menu_customization.menu_id</code>.
     */
    public final TableField<MbMenuCustomizationRecord, UUID> MENU_ID = createField(DSL.name("menu_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_menu_customization.parent_overridden</code>.
     */
    public final TableField<MbMenuCustomizationRecord, Boolean> PARENT_OVERRIDDEN = createField(DSL.name("parent_overridden"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_menu_customization.parent_id</code>.
     */
    public final TableField<MbMenuCustomizationRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_menu_customization.label_key</code>.
     */
    public final TableField<MbMenuCustomizationRecord, String> LABEL_KEY = createField(DSL.name("label_key"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu_customization.icon</code>.
     */
    public final TableField<MbMenuCustomizationRecord, String> ICON = createField(DSL.name("icon"), SQLDataType.VARCHAR(96), this, "");

    /**
     * The column <code>public.mb_menu_customization.sort</code>.
     */
    public final TableField<MbMenuCustomizationRecord, Integer> SORT = createField(DSL.name("sort"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.mb_menu_customization.visible</code>.
     */
    public final TableField<MbMenuCustomizationRecord, Boolean> VISIBLE = createField(DSL.name("visible"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.mb_menu_customization.updated_at</code>.
     */
    public final TableField<MbMenuCustomizationRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_menu_customization.label_zh_cn</code>.
     */
    public final TableField<MbMenuCustomizationRecord, String> LABEL_ZH_CN = createField(DSL.name("label_zh_cn"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu_customization.label_en_us</code>.
     */
    public final TableField<MbMenuCustomizationRecord, String> LABEL_EN_US = createField(DSL.name("label_en_us"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu_customization.localized_label</code>.
     */
    public final TableField<MbMenuCustomizationRecord, JSONB> LOCALIZED_LABEL = createField(DSL.name("localized_label"), SQLDataType.JSONB, this, "");

    private MbMenuCustomization(Name alias, Table<MbMenuCustomizationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbMenuCustomization(Name alias, Table<MbMenuCustomizationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_menu_customization</code> table
     * reference
     */
    public MbMenuCustomization(String alias) {
        this(DSL.name(alias), MB_MENU_CUSTOMIZATION);
    }

    /**
     * Create an aliased <code>public.mb_menu_customization</code> table
     * reference
     */
    public MbMenuCustomization(Name alias) {
        this(alias, MB_MENU_CUSTOMIZATION);
    }

    /**
     * Create a <code>public.mb_menu_customization</code> table reference
     */
    public MbMenuCustomization() {
        this(DSL.name("mb_menu_customization"), null);
    }

    public <O extends Record> MbMenuCustomization(Table<O> path, ForeignKey<O, MbMenuCustomizationRecord> childPath, InverseForeignKey<O, MbMenuCustomizationRecord> parentPath) {
        super(path, childPath, parentPath, MB_MENU_CUSTOMIZATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbMenuCustomizationPath extends MbMenuCustomization implements Path<MbMenuCustomizationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbMenuCustomizationPath(Table<O> path, ForeignKey<O, MbMenuCustomizationRecord> childPath, InverseForeignKey<O, MbMenuCustomizationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbMenuCustomizationPath(Name alias, Table<MbMenuCustomizationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbMenuCustomizationPath as(String alias) {
            return new MbMenuCustomizationPath(DSL.name(alias), this);
        }

        @Override
        public MbMenuCustomizationPath as(Name alias) {
            return new MbMenuCustomizationPath(alias, this);
        }

        @Override
        public MbMenuCustomizationPath as(Table<?> alias) {
            return new MbMenuCustomizationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbMenuCustomizationRecord> getPrimaryKey() {
        return Keys.MB_MENU_CUSTOMIZATION_PKEY;
    }

    @Override
    public List<ForeignKey<MbMenuCustomizationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_MENU_CUSTOMIZATION__MB_MENU_CUSTOMIZATION_MENU_ID_FKEY, Keys.MB_MENU_CUSTOMIZATION__MB_MENU_CUSTOMIZATION_PARENT_ID_FKEY);
    }

    private transient MbMenuPath _mbMenuCustomizationMenuIdFkey;

    /**
     * Get the implicit join path to the <code>public.mb_menu</code> table, via
     * the <code>mb_menu_customization_menu_id_fkey</code> key.
     */
    public MbMenuPath mbMenuCustomizationMenuIdFkey() {
        if (_mbMenuCustomizationMenuIdFkey == null)
            _mbMenuCustomizationMenuIdFkey = new MbMenuPath(this, Keys.MB_MENU_CUSTOMIZATION__MB_MENU_CUSTOMIZATION_MENU_ID_FKEY, null);

        return _mbMenuCustomizationMenuIdFkey;
    }

    private transient MbMenuPath _mbMenuCustomizationParentIdFkey;

    /**
     * Get the implicit join path to the <code>public.mb_menu</code> table, via
     * the <code>mb_menu_customization_parent_id_fkey</code> key.
     */
    public MbMenuPath mbMenuCustomizationParentIdFkey() {
        if (_mbMenuCustomizationParentIdFkey == null)
            _mbMenuCustomizationParentIdFkey = new MbMenuPath(this, Keys.MB_MENU_CUSTOMIZATION__MB_MENU_CUSTOMIZATION_PARENT_ID_FKEY, null);

        return _mbMenuCustomizationParentIdFkey;
    }

    @Override
    public List<Check<MbMenuCustomizationRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_menu_custom_label_shape"), "(((localized_label IS NULL) OR ((jsonb_typeof(localized_label) = 'object'::text) AND (localized_label <> '{}'::jsonb))))", true),
            Internal.createCheck(this, DSL.name("mb_menu_customization_not_self_parent"), "(((parent_id IS NULL) OR (parent_id <> menu_id)))", true)
        );
    }

    @Override
    public MbMenuCustomization as(String alias) {
        return new MbMenuCustomization(DSL.name(alias), this);
    }

    @Override
    public MbMenuCustomization as(Name alias) {
        return new MbMenuCustomization(alias, this);
    }

    @Override
    public MbMenuCustomization as(Table<?> alias) {
        return new MbMenuCustomization(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbMenuCustomization rename(String name) {
        return new MbMenuCustomization(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbMenuCustomization rename(Name name) {
        return new MbMenuCustomization(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbMenuCustomization rename(Table<?> name) {
        return new MbMenuCustomization(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenuCustomization where(Condition condition) {
        return new MbMenuCustomization(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenuCustomization where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenuCustomization where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenuCustomization where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenuCustomization where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenuCustomization where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenuCustomization where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenuCustomization where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenuCustomization whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenuCustomization whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
