/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbMenuCustomization.MbMenuCustomizationPath;
import com.metabuild.schema.platform.tables.MbPermission.MbPermissionPath;
import com.metabuild.schema.platform.tables.records.MbMenuRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbMenu extends TableImpl<MbMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_menu</code>
     */
    public static final MbMenu MB_MENU = new MbMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbMenuRecord> getRecordType() {
        return MbMenuRecord.class;
    }

    /**
     * The column <code>public.mb_menu.id</code>.
     */
    public final TableField<MbMenuRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_menu.source_key</code>.
     */
    public final TableField<MbMenuRecord, String> SOURCE_KEY = createField(DSL.name("source_key"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu.origin</code>.
     */
    public final TableField<MbMenuRecord, String> ORIGIN = createField(DSL.name("origin"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.mb_menu.subsystem_key</code>.
     */
    public final TableField<MbMenuRecord, String> SUBSYSTEM_KEY = createField(DSL.name("subsystem_key"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_menu.route_key</code>.
     */
    public final TableField<MbMenuRecord, String> ROUTE_KEY = createField(DSL.name("route_key"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu.permission_id</code>.
     */
    public final TableField<MbMenuRecord, UUID> PERMISSION_ID = createField(DSL.name("permission_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_menu.default_parent_source_key</code>.
     */
    public final TableField<MbMenuRecord, String> DEFAULT_PARENT_SOURCE_KEY = createField(DSL.name("default_parent_source_key"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu.default_label_key</code>.
     */
    public final TableField<MbMenuRecord, String> DEFAULT_LABEL_KEY = createField(DSL.name("default_label_key"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_menu.default_icon</code>.
     */
    public final TableField<MbMenuRecord, String> DEFAULT_ICON = createField(DSL.name("default_icon"), SQLDataType.VARCHAR(96), this, "");

    /**
     * The column <code>public.mb_menu.default_sort</code>.
     */
    public final TableField<MbMenuRecord, Integer> DEFAULT_SORT = createField(DSL.name("default_sort"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_menu.default_visible</code>.
     */
    public final TableField<MbMenuRecord, Boolean> DEFAULT_VISIBLE = createField(DSL.name("default_visible"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_menu.status</code>.
     */
    public final TableField<MbMenuRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_menu.deleted_at</code>.
     */
    public final TableField<MbMenuRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_menu.created_at</code>.
     */
    public final TableField<MbMenuRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_menu.updated_at</code>.
     */
    public final TableField<MbMenuRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_menu.default_path</code>.
     */
    public final TableField<MbMenuRecord, String> DEFAULT_PATH = createField(DSL.name("default_path"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu.default_type</code>.
     */
    public final TableField<MbMenuRecord, String> DEFAULT_TYPE = createField(DSL.name("default_type"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'dir'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_menu.runtime_label_zh_cn</code>.
     */
    public final TableField<MbMenuRecord, String> RUNTIME_LABEL_ZH_CN = createField(DSL.name("runtime_label_zh_cn"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu.runtime_label_en_us</code>.
     */
    public final TableField<MbMenuRecord, String> RUNTIME_LABEL_EN_US = createField(DSL.name("runtime_label_en_us"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_menu.runtime_label</code>.
     */
    public final TableField<MbMenuRecord, JSONB> RUNTIME_LABEL = createField(DSL.name("runtime_label"), SQLDataType.JSONB, this, "");

    private MbMenu(Name alias, Table<MbMenuRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbMenu(Name alias, Table<MbMenuRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_menu</code> table reference
     */
    public MbMenu(String alias) {
        this(DSL.name(alias), MB_MENU);
    }

    /**
     * Create an aliased <code>public.mb_menu</code> table reference
     */
    public MbMenu(Name alias) {
        this(alias, MB_MENU);
    }

    /**
     * Create a <code>public.mb_menu</code> table reference
     */
    public MbMenu() {
        this(DSL.name("mb_menu"), null);
    }

    public <O extends Record> MbMenu(Table<O> path, ForeignKey<O, MbMenuRecord> childPath, InverseForeignKey<O, MbMenuRecord> parentPath) {
        super(path, childPath, parentPath, MB_MENU);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbMenuPath extends MbMenu implements Path<MbMenuRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbMenuPath(Table<O> path, ForeignKey<O, MbMenuRecord> childPath, InverseForeignKey<O, MbMenuRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbMenuPath(Name alias, Table<MbMenuRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbMenuPath as(String alias) {
            return new MbMenuPath(DSL.name(alias), this);
        }

        @Override
        public MbMenuPath as(Name alias) {
            return new MbMenuPath(alias, this);
        }

        @Override
        public MbMenuPath as(Table<?> alias) {
            return new MbMenuPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_MENU_SOURCE_KEY_ACTIVE_UQ, Indexes.MB_MENU_SUBSYSTEM_IDX);
    }

    @Override
    public UniqueKey<MbMenuRecord> getPrimaryKey() {
        return Keys.MB_MENU_PKEY;
    }

    @Override
    public List<ForeignKey<MbMenuRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_MENU__MB_MENU_PERMISSION_ID_FKEY);
    }

    private transient MbPermissionPath _mbPermission;

    /**
     * Get the implicit join path to the <code>public.mb_permission</code>
     * table.
     */
    public MbPermissionPath mbPermission() {
        if (_mbPermission == null)
            _mbPermission = new MbPermissionPath(this, Keys.MB_MENU__MB_MENU_PERMISSION_ID_FKEY, null);

        return _mbPermission;
    }

    private transient MbMenuCustomizationPath _mbMenuCustomizationMenuIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_menu_customization</code> table, via the
     * <code>mb_menu_customization_menu_id_fkey</code> key
     */
    public MbMenuCustomizationPath mbMenuCustomizationMenuIdFkey() {
        if (_mbMenuCustomizationMenuIdFkey == null)
            _mbMenuCustomizationMenuIdFkey = new MbMenuCustomizationPath(this, null, Keys.MB_MENU_CUSTOMIZATION__MB_MENU_CUSTOMIZATION_MENU_ID_FKEY.getInverseKey());

        return _mbMenuCustomizationMenuIdFkey;
    }

    private transient MbMenuCustomizationPath _mbMenuCustomizationParentIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_menu_customization</code> table, via the
     * <code>mb_menu_customization_parent_id_fkey</code> key
     */
    public MbMenuCustomizationPath mbMenuCustomizationParentIdFkey() {
        if (_mbMenuCustomizationParentIdFkey == null)
            _mbMenuCustomizationParentIdFkey = new MbMenuCustomizationPath(this, null, Keys.MB_MENU_CUSTOMIZATION__MB_MENU_CUSTOMIZATION_PARENT_ID_FKEY.getInverseKey());

        return _mbMenuCustomizationParentIdFkey;
    }

    @Override
    public List<Check<MbMenuRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_menu_catalog_navigation_shape"), "((((origin)::text <> 'CATALOG'::text) OR ((default_type)::text = 'dir'::text) OR ((route_key IS NOT NULL) AND (default_path IS NOT NULL))))", true),
            Internal.createCheck(this, DSL.name("mb_menu_default_type_check"), "(((default_type)::text = ANY ((ARRAY['dir'::character varying, 'menu'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_menu_origin_check"), "(((origin)::text = ANY ((ARRAY['CATALOG'::character varying, 'RUNTIME'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_menu_origin_shape_check"), "(((((origin)::text = 'CATALOG'::text) AND (source_key IS NOT NULL)) OR (((origin)::text = 'RUNTIME'::text) AND (source_key IS NULL) AND (route_key IS NULL) AND (permission_id IS NULL))))", true),
            Internal.createCheck(this, DSL.name("mb_menu_runtime_label_shape"), "((((origin)::text <> 'RUNTIME'::text) OR ((jsonb_typeof(runtime_label) = 'object'::text) AND (runtime_label <> '{}'::jsonb))))", true),
            Internal.createCheck(this, DSL.name("mb_menu_status_check"), "(((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DEPRECATED'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbMenu as(String alias) {
        return new MbMenu(DSL.name(alias), this);
    }

    @Override
    public MbMenu as(Name alias) {
        return new MbMenu(alias, this);
    }

    @Override
    public MbMenu as(Table<?> alias) {
        return new MbMenu(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbMenu rename(String name) {
        return new MbMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbMenu rename(Name name) {
        return new MbMenu(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbMenu rename(Table<?> name) {
        return new MbMenu(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenu where(Condition condition) {
        return new MbMenu(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenu where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenu where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenu where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenu where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenu where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenu where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbMenu where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenu whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbMenu whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
