/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbOperationLogRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbOperationLog extends TableImpl<MbOperationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_operation_log</code>
     */
    public static final MbOperationLog MB_OPERATION_LOG = new MbOperationLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbOperationLogRecord> getRecordType() {
        return MbOperationLogRecord.class;
    }

    /**
     * The column <code>public.mb_operation_log.id</code>.
     */
    public final TableField<MbOperationLogRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.actor_id</code>.
     */
    public final TableField<MbOperationLogRecord, UUID> ACTOR_ID = createField(DSL.name("actor_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_operation_log.operation</code>.
     */
    public final TableField<MbOperationLogRecord, String> OPERATION = createField(DSL.name("operation"), SQLDataType.VARCHAR(160).nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.resource_type</code>.
     */
    public final TableField<MbOperationLogRecord, String> RESOURCE_TYPE = createField(DSL.name("resource_type"), SQLDataType.VARCHAR(96).nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.resource_id</code>.
     */
    public final TableField<MbOperationLogRecord, UUID> RESOURCE_ID = createField(DSL.name("resource_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_operation_log.request_method</code>.
     */
    public final TableField<MbOperationLogRecord, String> REQUEST_METHOD = createField(DSL.name("request_method"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>public.mb_operation_log.request_path</code>.
     */
    public final TableField<MbOperationLogRecord, String> REQUEST_PATH = createField(DSL.name("request_path"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.mb_operation_log.success</code>.
     */
    public final TableField<MbOperationLogRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.detail</code>.
     */
    public final TableField<MbOperationLogRecord, JSONB> DETAIL = createField(DSL.name("detail"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.mb_operation_log.trace_id</code>.
     */
    public final TableField<MbOperationLogRecord, String> TRACE_ID = createField(DSL.name("trace_id"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.mb_operation_log.created_at</code>.
     */
    public final TableField<MbOperationLogRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbOperationLog(Name alias, Table<MbOperationLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbOperationLog(Name alias, Table<MbOperationLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_operation_log</code> table reference
     */
    public MbOperationLog(String alias) {
        this(DSL.name(alias), MB_OPERATION_LOG);
    }

    /**
     * Create an aliased <code>public.mb_operation_log</code> table reference
     */
    public MbOperationLog(Name alias) {
        this(alias, MB_OPERATION_LOG);
    }

    /**
     * Create a <code>public.mb_operation_log</code> table reference
     */
    public MbOperationLog() {
        this(DSL.name("mb_operation_log"), null);
    }

    public <O extends Record> MbOperationLog(Table<O> path, ForeignKey<O, MbOperationLogRecord> childPath, InverseForeignKey<O, MbOperationLogRecord> parentPath) {
        super(path, childPath, parentPath, MB_OPERATION_LOG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbOperationLogPath extends MbOperationLog implements Path<MbOperationLogRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbOperationLogPath(Table<O> path, ForeignKey<O, MbOperationLogRecord> childPath, InverseForeignKey<O, MbOperationLogRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbOperationLogPath(Name alias, Table<MbOperationLogRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbOperationLogPath as(String alias) {
            return new MbOperationLogPath(DSL.name(alias), this);
        }

        @Override
        public MbOperationLogPath as(Name alias) {
            return new MbOperationLogPath(alias, this);
        }

        @Override
        public MbOperationLogPath as(Table<?> alias) {
            return new MbOperationLogPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_OPERATION_LOG_ACTOR_CREATED_IDX, Indexes.MB_OPERATION_LOG_RESOURCE_IDX);
    }

    @Override
    public UniqueKey<MbOperationLogRecord> getPrimaryKey() {
        return Keys.MB_OPERATION_LOG_PKEY;
    }

    @Override
    public List<ForeignKey<MbOperationLogRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_OPERATION_LOG__MB_OPERATION_LOG_ACTOR_ID_FKEY);
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table.
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, Keys.MB_OPERATION_LOG__MB_OPERATION_LOG_ACTOR_ID_FKEY, null);

        return _mbUser;
    }

    @Override
    public MbOperationLog as(String alias) {
        return new MbOperationLog(DSL.name(alias), this);
    }

    @Override
    public MbOperationLog as(Name alias) {
        return new MbOperationLog(alias, this);
    }

    @Override
    public MbOperationLog as(Table<?> alias) {
        return new MbOperationLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbOperationLog rename(String name) {
        return new MbOperationLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbOperationLog rename(Name name) {
        return new MbOperationLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbOperationLog rename(Table<?> name) {
        return new MbOperationLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Condition condition) {
        return new MbOperationLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
