/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbPermission.MbPermissionPath;
import com.metabuild.schema.platform.tables.records.MbPermissionAliasRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbPermissionAlias extends TableImpl<MbPermissionAliasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_permission_alias</code>
     */
    public static final MbPermissionAlias MB_PERMISSION_ALIAS = new MbPermissionAlias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbPermissionAliasRecord> getRecordType() {
        return MbPermissionAliasRecord.class;
    }

    /**
     * The column <code>public.mb_permission_alias.old_code</code>.
     */
    public final TableField<MbPermissionAliasRecord, String> OLD_CODE = createField(DSL.name("old_code"), SQLDataType.VARCHAR(160).nullable(false), this, "");

    /**
     * The column <code>public.mb_permission_alias.permission_id</code>.
     */
    public final TableField<MbPermissionAliasRecord, UUID> PERMISSION_ID = createField(DSL.name("permission_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_permission_alias.catalog_version</code>.
     */
    public final TableField<MbPermissionAliasRecord, Integer> CATALOG_VERSION = createField(DSL.name("catalog_version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.mb_permission_alias.created_at</code>.
     */
    public final TableField<MbPermissionAliasRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbPermissionAlias(Name alias, Table<MbPermissionAliasRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbPermissionAlias(Name alias, Table<MbPermissionAliasRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_permission_alias</code> table reference
     */
    public MbPermissionAlias(String alias) {
        this(DSL.name(alias), MB_PERMISSION_ALIAS);
    }

    /**
     * Create an aliased <code>public.mb_permission_alias</code> table reference
     */
    public MbPermissionAlias(Name alias) {
        this(alias, MB_PERMISSION_ALIAS);
    }

    /**
     * Create a <code>public.mb_permission_alias</code> table reference
     */
    public MbPermissionAlias() {
        this(DSL.name("mb_permission_alias"), null);
    }

    public <O extends Record> MbPermissionAlias(Table<O> path, ForeignKey<O, MbPermissionAliasRecord> childPath, InverseForeignKey<O, MbPermissionAliasRecord> parentPath) {
        super(path, childPath, parentPath, MB_PERMISSION_ALIAS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbPermissionAliasPath extends MbPermissionAlias implements Path<MbPermissionAliasRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbPermissionAliasPath(Table<O> path, ForeignKey<O, MbPermissionAliasRecord> childPath, InverseForeignKey<O, MbPermissionAliasRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbPermissionAliasPath(Name alias, Table<MbPermissionAliasRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbPermissionAliasPath as(String alias) {
            return new MbPermissionAliasPath(DSL.name(alias), this);
        }

        @Override
        public MbPermissionAliasPath as(Name alias) {
            return new MbPermissionAliasPath(alias, this);
        }

        @Override
        public MbPermissionAliasPath as(Table<?> alias) {
            return new MbPermissionAliasPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbPermissionAliasRecord> getPrimaryKey() {
        return Keys.MB_PERMISSION_ALIAS_PKEY;
    }

    @Override
    public List<ForeignKey<MbPermissionAliasRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_PERMISSION_ALIAS__MB_PERMISSION_ALIAS_PERMISSION_ID_FKEY);
    }

    private transient MbPermissionPath _mbPermission;

    /**
     * Get the implicit join path to the <code>public.mb_permission</code>
     * table.
     */
    public MbPermissionPath mbPermission() {
        if (_mbPermission == null)
            _mbPermission = new MbPermissionPath(this, Keys.MB_PERMISSION_ALIAS__MB_PERMISSION_ALIAS_PERMISSION_ID_FKEY, null);

        return _mbPermission;
    }

    @Override
    public List<Check<MbPermissionAliasRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_permission_alias_code_grammar"), "(((old_code)::text ~ '^[a-z][a-z0-9-]*:[a-z][a-z0-9-]*:[a-z][a-z0-9-]*$'::text))", true)
        );
    }

    @Override
    public MbPermissionAlias as(String alias) {
        return new MbPermissionAlias(DSL.name(alias), this);
    }

    @Override
    public MbPermissionAlias as(Name alias) {
        return new MbPermissionAlias(alias, this);
    }

    @Override
    public MbPermissionAlias as(Table<?> alias) {
        return new MbPermissionAlias(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermissionAlias rename(String name) {
        return new MbPermissionAlias(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermissionAlias rename(Name name) {
        return new MbPermissionAlias(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermissionAlias rename(Table<?> name) {
        return new MbPermissionAlias(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionAlias where(Condition condition) {
        return new MbPermissionAlias(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionAlias where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionAlias where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionAlias where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionAlias where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionAlias where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionAlias where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionAlias where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionAlias whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionAlias whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
