/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.records.MbPermissionCatalogVersionRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbPermissionCatalogVersion extends TableImpl<MbPermissionCatalogVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.mb_permission_catalog_version</code>
     */
    public static final MbPermissionCatalogVersion MB_PERMISSION_CATALOG_VERSION = new MbPermissionCatalogVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbPermissionCatalogVersionRecord> getRecordType() {
        return MbPermissionCatalogVersionRecord.class;
    }

    /**
     * The column <code>public.mb_permission_catalog_version.version</code>.
     */
    public final TableField<MbPermissionCatalogVersionRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.mb_permission_catalog_version.digest</code>.
     */
    public final TableField<MbPermissionCatalogVersionRecord, String> DIGEST = createField(DSL.name("digest"), SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_permission_catalog_version.applied_at</code>.
     */
    public final TableField<MbPermissionCatalogVersionRecord, OffsetDateTime> APPLIED_AT = createField(DSL.name("applied_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbPermissionCatalogVersion(Name alias, Table<MbPermissionCatalogVersionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbPermissionCatalogVersion(Name alias, Table<MbPermissionCatalogVersionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_permission_catalog_version</code> table
     * reference
     */
    public MbPermissionCatalogVersion(String alias) {
        this(DSL.name(alias), MB_PERMISSION_CATALOG_VERSION);
    }

    /**
     * Create an aliased <code>public.mb_permission_catalog_version</code> table
     * reference
     */
    public MbPermissionCatalogVersion(Name alias) {
        this(alias, MB_PERMISSION_CATALOG_VERSION);
    }

    /**
     * Create a <code>public.mb_permission_catalog_version</code> table
     * reference
     */
    public MbPermissionCatalogVersion() {
        this(DSL.name("mb_permission_catalog_version"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbPermissionCatalogVersionRecord> getPrimaryKey() {
        return Keys.MB_PERMISSION_CATALOG_VERSION_PKEY;
    }

    @Override
    public List<UniqueKey<MbPermissionCatalogVersionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_PERMISSION_CATALOG_VERSION_DIGEST_KEY);
    }

    @Override
    public MbPermissionCatalogVersion as(String alias) {
        return new MbPermissionCatalogVersion(DSL.name(alias), this);
    }

    @Override
    public MbPermissionCatalogVersion as(Name alias) {
        return new MbPermissionCatalogVersion(alias, this);
    }

    @Override
    public MbPermissionCatalogVersion as(Table<?> alias) {
        return new MbPermissionCatalogVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermissionCatalogVersion rename(String name) {
        return new MbPermissionCatalogVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermissionCatalogVersion rename(Name name) {
        return new MbPermissionCatalogVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermissionCatalogVersion rename(Table<?> name) {
        return new MbPermissionCatalogVersion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionCatalogVersion where(Condition condition) {
        return new MbPermissionCatalogVersion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionCatalogVersion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionCatalogVersion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionCatalogVersion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionCatalogVersion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionCatalogVersion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionCatalogVersion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermissionCatalogVersion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionCatalogVersion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermissionCatalogVersion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
