/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbMenu.MbMenuPath;
import com.metabuild.schema.platform.tables.MbPermissionAlias.MbPermissionAliasPath;
import com.metabuild.schema.platform.tables.MbRole.MbRolePath;
import com.metabuild.schema.platform.tables.MbRolePermission.MbRolePermissionPath;
import com.metabuild.schema.platform.tables.records.MbPermissionRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbPermission extends TableImpl<MbPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_permission</code>
     */
    public static final MbPermission MB_PERMISSION = new MbPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbPermissionRecord> getRecordType() {
        return MbPermissionRecord.class;
    }

    /**
     * The column <code>public.mb_permission.id</code>.
     */
    public final TableField<MbPermissionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_permission.source_key</code>.
     */
    public final TableField<MbPermissionRecord, String> SOURCE_KEY = createField(DSL.name("source_key"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_permission.code</code>.
     */
    public final TableField<MbPermissionRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(160).nullable(false), this, "");

    /**
     * The column <code>public.mb_permission.kind</code>.
     */
    public final TableField<MbPermissionRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.mb_permission.status</code>.
     */
    public final TableField<MbPermissionRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_permission.first_seen_version</code>.
     */
    public final TableField<MbPermissionRecord, String> FIRST_SEEN_VERSION = createField(DSL.name("first_seen_version"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_permission.last_seen_version</code>.
     */
    public final TableField<MbPermissionRecord, String> LAST_SEEN_VERSION = createField(DSL.name("last_seen_version"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_permission.deleted_at</code>.
     */
    public final TableField<MbPermissionRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_permission.created_at</code>.
     */
    public final TableField<MbPermissionRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_permission.updated_at</code>.
     */
    public final TableField<MbPermissionRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbPermission(Name alias, Table<MbPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbPermission(Name alias, Table<MbPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_permission</code> table reference
     */
    public MbPermission(String alias) {
        this(DSL.name(alias), MB_PERMISSION);
    }

    /**
     * Create an aliased <code>public.mb_permission</code> table reference
     */
    public MbPermission(Name alias) {
        this(alias, MB_PERMISSION);
    }

    /**
     * Create a <code>public.mb_permission</code> table reference
     */
    public MbPermission() {
        this(DSL.name("mb_permission"), null);
    }

    public <O extends Record> MbPermission(Table<O> path, ForeignKey<O, MbPermissionRecord> childPath, InverseForeignKey<O, MbPermissionRecord> parentPath) {
        super(path, childPath, parentPath, MB_PERMISSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbPermissionPath extends MbPermission implements Path<MbPermissionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbPermissionPath(Table<O> path, ForeignKey<O, MbPermissionRecord> childPath, InverseForeignKey<O, MbPermissionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbPermissionPath(Name alias, Table<MbPermissionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbPermissionPath as(String alias) {
            return new MbPermissionPath(DSL.name(alias), this);
        }

        @Override
        public MbPermissionPath as(Name alias) {
            return new MbPermissionPath(alias, this);
        }

        @Override
        public MbPermissionPath as(Table<?> alias) {
            return new MbPermissionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_PERMISSION_CODE_ACTIVE_UQ, Indexes.MB_PERMISSION_SOURCE_KEY_ACTIVE_UQ);
    }

    @Override
    public UniqueKey<MbPermissionRecord> getPrimaryKey() {
        return Keys.MB_PERMISSION_PKEY;
    }

    private transient MbMenuPath _mbMenu;

    /**
     * Get the implicit to-many join path to the <code>public.mb_menu</code>
     * table
     */
    public MbMenuPath mbMenu() {
        if (_mbMenu == null)
            _mbMenu = new MbMenuPath(this, null, Keys.MB_MENU__MB_MENU_PERMISSION_ID_FKEY.getInverseKey());

        return _mbMenu;
    }

    private transient MbPermissionAliasPath _mbPermissionAlias;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_permission_alias</code> table
     */
    public MbPermissionAliasPath mbPermissionAlias() {
        if (_mbPermissionAlias == null)
            _mbPermissionAlias = new MbPermissionAliasPath(this, null, Keys.MB_PERMISSION_ALIAS__MB_PERMISSION_ALIAS_PERMISSION_ID_FKEY.getInverseKey());

        return _mbPermissionAlias;
    }

    private transient MbRolePermissionPath _mbRolePermission;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_role_permission</code> table
     */
    public MbRolePermissionPath mbRolePermission() {
        if (_mbRolePermission == null)
            _mbRolePermission = new MbRolePermissionPath(this, null, Keys.MB_ROLE_PERMISSION__MB_ROLE_PERMISSION_PERMISSION_ID_FKEY.getInverseKey());

        return _mbRolePermission;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_role</code> table
     */
    public MbRolePath mbRole() {
        return mbRolePermission().mbRole();
    }

    @Override
    public List<Check<MbPermissionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_permission_code_grammar"), "(((code)::text ~ '^[a-z][a-z0-9-]*:[a-z][a-z0-9-]*:[a-z][a-z0-9-]*$'::text))", true),
            Internal.createCheck(this, DSL.name("mb_permission_kind_check"), "(((kind)::text = ANY ((ARRAY['PAGE'::character varying, 'ACTION'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_permission_source_key_grammar"), "(((source_key)::text ~ '^/.+#(page|action:[a-z][a-z0-9-]*)$'::text))", true),
            Internal.createCheck(this, DSL.name("mb_permission_status_check"), "(((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DEPRECATED'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbPermission as(String alias) {
        return new MbPermission(DSL.name(alias), this);
    }

    @Override
    public MbPermission as(Name alias) {
        return new MbPermission(alias, this);
    }

    @Override
    public MbPermission as(Table<?> alias) {
        return new MbPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermission rename(String name) {
        return new MbPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermission rename(Name name) {
        return new MbPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbPermission rename(Table<?> name) {
        return new MbPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermission where(Condition condition) {
        return new MbPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
