/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbRefreshToken.MbRefreshTokenPath;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbRefreshTokenRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbRefreshToken extends TableImpl<MbRefreshTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_refresh_token</code>
     */
    public static final MbRefreshToken MB_REFRESH_TOKEN = new MbRefreshToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbRefreshTokenRecord> getRecordType() {
        return MbRefreshTokenRecord.class;
    }

    /**
     * The column <code>public.mb_refresh_token.id</code>.
     */
    public final TableField<MbRefreshTokenRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_refresh_token.user_id</code>.
     */
    public final TableField<MbRefreshTokenRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_refresh_token.family_id</code>.
     */
    public final TableField<MbRefreshTokenRecord, UUID> FAMILY_ID = createField(DSL.name("family_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_refresh_token.token_hash</code>.
     */
    public final TableField<MbRefreshTokenRecord, String> TOKEN_HASH = createField(DSL.name("token_hash"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_refresh_token.expires_at</code>.
     */
    public final TableField<MbRefreshTokenRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.mb_refresh_token.consumed_at</code>.
     */
    public final TableField<MbRefreshTokenRecord, OffsetDateTime> CONSUMED_AT = createField(DSL.name("consumed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_refresh_token.revoked_at</code>.
     */
    public final TableField<MbRefreshTokenRecord, OffsetDateTime> REVOKED_AT = createField(DSL.name("revoked_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_refresh_token.replaced_by_id</code>.
     */
    public final TableField<MbRefreshTokenRecord, UUID> REPLACED_BY_ID = createField(DSL.name("replaced_by_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_refresh_token.created_at</code>.
     */
    public final TableField<MbRefreshTokenRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_refresh_token.credential_revision</code>.
     */
    public final TableField<MbRefreshTokenRecord, Long> CREDENTIAL_REVISION = createField(DSL.name("credential_revision"), SQLDataType.BIGINT.nullable(false), this, "");

    private MbRefreshToken(Name alias, Table<MbRefreshTokenRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbRefreshToken(Name alias, Table<MbRefreshTokenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_refresh_token</code> table reference
     */
    public MbRefreshToken(String alias) {
        this(DSL.name(alias), MB_REFRESH_TOKEN);
    }

    /**
     * Create an aliased <code>public.mb_refresh_token</code> table reference
     */
    public MbRefreshToken(Name alias) {
        this(alias, MB_REFRESH_TOKEN);
    }

    /**
     * Create a <code>public.mb_refresh_token</code> table reference
     */
    public MbRefreshToken() {
        this(DSL.name("mb_refresh_token"), null);
    }

    public <O extends Record> MbRefreshToken(Table<O> path, ForeignKey<O, MbRefreshTokenRecord> childPath, InverseForeignKey<O, MbRefreshTokenRecord> parentPath) {
        super(path, childPath, parentPath, MB_REFRESH_TOKEN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbRefreshTokenPath extends MbRefreshToken implements Path<MbRefreshTokenRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbRefreshTokenPath(Table<O> path, ForeignKey<O, MbRefreshTokenRecord> childPath, InverseForeignKey<O, MbRefreshTokenRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbRefreshTokenPath(Name alias, Table<MbRefreshTokenRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbRefreshTokenPath as(String alias) {
            return new MbRefreshTokenPath(DSL.name(alias), this);
        }

        @Override
        public MbRefreshTokenPath as(Name alias) {
            return new MbRefreshTokenPath(alias, this);
        }

        @Override
        public MbRefreshTokenPath as(Table<?> alias) {
            return new MbRefreshTokenPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_REFRESH_TOKEN_FAMILY_IDX, Indexes.MB_REFRESH_TOKEN_USER_ACTIVE_IDX);
    }

    @Override
    public UniqueKey<MbRefreshTokenRecord> getPrimaryKey() {
        return Keys.MB_REFRESH_TOKEN_PKEY;
    }

    @Override
    public List<UniqueKey<MbRefreshTokenRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_REFRESH_TOKEN_TOKEN_HASH_KEY);
    }

    @Override
    public List<ForeignKey<MbRefreshTokenRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_REFRESH_TOKEN__MB_REFRESH_TOKEN_REPLACED_BY_ID_FKEY, Keys.MB_REFRESH_TOKEN__MB_REFRESH_TOKEN_USER_ID_FKEY);
    }

    private transient MbRefreshTokenPath _mbRefreshToken;

    /**
     * Get the implicit join path to the <code>public.mb_refresh_token</code>
     * table.
     */
    public MbRefreshTokenPath mbRefreshToken() {
        if (_mbRefreshToken == null)
            _mbRefreshToken = new MbRefreshTokenPath(this, Keys.MB_REFRESH_TOKEN__MB_REFRESH_TOKEN_REPLACED_BY_ID_FKEY, null);

        return _mbRefreshToken;
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table.
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, Keys.MB_REFRESH_TOKEN__MB_REFRESH_TOKEN_USER_ID_FKEY, null);

        return _mbUser;
    }

    @Override
    public List<Check<MbRefreshTokenRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_refresh_token_credential_revision_nonnegative"), "((credential_revision >= 0))", true),
            Internal.createCheck(this, DSL.name("mb_refresh_token_expiry_check"), "((expires_at > created_at))", true)
        );
    }

    @Override
    public MbRefreshToken as(String alias) {
        return new MbRefreshToken(DSL.name(alias), this);
    }

    @Override
    public MbRefreshToken as(Name alias) {
        return new MbRefreshToken(alias, this);
    }

    @Override
    public MbRefreshToken as(Table<?> alias) {
        return new MbRefreshToken(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRefreshToken rename(String name) {
        return new MbRefreshToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRefreshToken rename(Name name) {
        return new MbRefreshToken(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRefreshToken rename(Table<?> name) {
        return new MbRefreshToken(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRefreshToken where(Condition condition) {
        return new MbRefreshToken(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRefreshToken where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRefreshToken where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRefreshToken where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRefreshToken where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRefreshToken where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRefreshToken where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRefreshToken where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRefreshToken whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRefreshToken whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
