/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbDept.MbDeptPath;
import com.metabuild.schema.platform.tables.MbPermission.MbPermissionPath;
import com.metabuild.schema.platform.tables.MbRoleCustomDept.MbRoleCustomDeptPath;
import com.metabuild.schema.platform.tables.MbRolePermission.MbRolePermissionPath;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.MbUserRole.MbUserRolePath;
import com.metabuild.schema.platform.tables.records.MbRoleRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbRole extends TableImpl<MbRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_role</code>
     */
    public static final MbRole MB_ROLE = new MbRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbRoleRecord> getRecordType() {
        return MbRoleRecord.class;
    }

    /**
     * The column <code>public.mb_role.id</code>.
     */
    public final TableField<MbRoleRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_role.code</code>.
     */
    public final TableField<MbRoleRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(96).nullable(false), this, "");

    /**
     * The column <code>public.mb_role.name</code>.
     */
    public final TableField<MbRoleRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_role.system_role</code>.
     */
    public final TableField<MbRoleRecord, Boolean> SYSTEM_ROLE = createField(DSL.name("system_role"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_role.grants_system_admin</code>.
     */
    public final TableField<MbRoleRecord, Boolean> GRANTS_SYSTEM_ADMIN = createField(DSL.name("grants_system_admin"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_role.data_scope_type</code>.
     */
    public final TableField<MbRoleRecord, String> DATA_SCOPE_TYPE = createField(DSL.name("data_scope_type"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.mb_role.status</code>.
     */
    public final TableField<MbRoleRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_role.deleted_at</code>.
     */
    public final TableField<MbRoleRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_role.created_at</code>.
     */
    public final TableField<MbRoleRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_role.updated_at</code>.
     */
    public final TableField<MbRoleRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbRole(Name alias, Table<MbRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbRole(Name alias, Table<MbRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_role</code> table reference
     */
    public MbRole(String alias) {
        this(DSL.name(alias), MB_ROLE);
    }

    /**
     * Create an aliased <code>public.mb_role</code> table reference
     */
    public MbRole(Name alias) {
        this(alias, MB_ROLE);
    }

    /**
     * Create a <code>public.mb_role</code> table reference
     */
    public MbRole() {
        this(DSL.name("mb_role"), null);
    }

    public <O extends Record> MbRole(Table<O> path, ForeignKey<O, MbRoleRecord> childPath, InverseForeignKey<O, MbRoleRecord> parentPath) {
        super(path, childPath, parentPath, MB_ROLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbRolePath extends MbRole implements Path<MbRoleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbRolePath(Table<O> path, ForeignKey<O, MbRoleRecord> childPath, InverseForeignKey<O, MbRoleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbRolePath(Name alias, Table<MbRoleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbRolePath as(String alias) {
            return new MbRolePath(DSL.name(alias), this);
        }

        @Override
        public MbRolePath as(Name alias) {
            return new MbRolePath(alias, this);
        }

        @Override
        public MbRolePath as(Table<?> alias) {
            return new MbRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbRoleRecord> getPrimaryKey() {
        return Keys.MB_ROLE_PKEY;
    }

    private transient MbRoleCustomDeptPath _mbRoleCustomDept;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_role_custom_dept</code> table
     */
    public MbRoleCustomDeptPath mbRoleCustomDept() {
        if (_mbRoleCustomDept == null)
            _mbRoleCustomDept = new MbRoleCustomDeptPath(this, null, Keys.MB_ROLE_CUSTOM_DEPT__MB_ROLE_CUSTOM_DEPT_ROLE_ID_FKEY.getInverseKey());

        return _mbRoleCustomDept;
    }

    private transient MbRolePermissionPath _mbRolePermission;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_role_permission</code> table
     */
    public MbRolePermissionPath mbRolePermission() {
        if (_mbRolePermission == null)
            _mbRolePermission = new MbRolePermissionPath(this, null, Keys.MB_ROLE_PERMISSION__MB_ROLE_PERMISSION_ROLE_ID_FKEY.getInverseKey());

        return _mbRolePermission;
    }

    private transient MbUserRolePath _mbUserRole;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_user_role</code> table
     */
    public MbUserRolePath mbUserRole() {
        if (_mbUserRole == null)
            _mbUserRole = new MbUserRolePath(this, null, Keys.MB_USER_ROLE__MB_USER_ROLE_ROLE_ID_FKEY.getInverseKey());

        return _mbUserRole;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_dept</code> table
     */
    public MbDeptPath mbDept() {
        return mbRoleCustomDept().mbDept();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_permission</code> table
     */
    public MbPermissionPath mbPermission() {
        return mbRolePermission().mbPermission();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_user</code> table
     */
    public MbUserPath mbUser() {
        return mbUserRole().mbUser();
    }

    @Override
    public List<Check<MbRoleRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_role_data_scope_type_check"), "(((data_scope_type)::text = ANY ((ARRAY['ALL'::character varying, 'SELF'::character varying, 'OWN_DEPT'::character varying, 'OWN_DEPT_AND_BELOW'::character varying, 'CUSTOM_DEPT'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_role_status_check"), "(((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("mb_role_system_admin_shape_check"), "(((NOT grants_system_admin) OR (system_role AND ((data_scope_type)::text = 'ALL'::text))))", true)
        );
    }

    @Override
    public MbRole as(String alias) {
        return new MbRole(DSL.name(alias), this);
    }

    @Override
    public MbRole as(Name alias) {
        return new MbRole(alias, this);
    }

    @Override
    public MbRole as(Table<?> alias) {
        return new MbRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRole rename(String name) {
        return new MbRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRole rename(Name name) {
        return new MbRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRole rename(Table<?> name) {
        return new MbRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRole where(Condition condition) {
        return new MbRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
