/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbDept.MbDeptPath;
import com.metabuild.schema.platform.tables.MbRole.MbRolePath;
import com.metabuild.schema.platform.tables.records.MbRoleCustomDeptRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbRoleCustomDept extends TableImpl<MbRoleCustomDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_role_custom_dept</code>
     */
    public static final MbRoleCustomDept MB_ROLE_CUSTOM_DEPT = new MbRoleCustomDept();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbRoleCustomDeptRecord> getRecordType() {
        return MbRoleCustomDeptRecord.class;
    }

    /**
     * The column <code>public.mb_role_custom_dept.role_id</code>.
     */
    public final TableField<MbRoleCustomDeptRecord, UUID> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_role_custom_dept.dept_id</code>.
     */
    public final TableField<MbRoleCustomDeptRecord, UUID> DEPT_ID = createField(DSL.name("dept_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_role_custom_dept.created_at</code>.
     */
    public final TableField<MbRoleCustomDeptRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbRoleCustomDept(Name alias, Table<MbRoleCustomDeptRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbRoleCustomDept(Name alias, Table<MbRoleCustomDeptRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_role_custom_dept</code> table reference
     */
    public MbRoleCustomDept(String alias) {
        this(DSL.name(alias), MB_ROLE_CUSTOM_DEPT);
    }

    /**
     * Create an aliased <code>public.mb_role_custom_dept</code> table reference
     */
    public MbRoleCustomDept(Name alias) {
        this(alias, MB_ROLE_CUSTOM_DEPT);
    }

    /**
     * Create a <code>public.mb_role_custom_dept</code> table reference
     */
    public MbRoleCustomDept() {
        this(DSL.name("mb_role_custom_dept"), null);
    }

    public <O extends Record> MbRoleCustomDept(Table<O> path, ForeignKey<O, MbRoleCustomDeptRecord> childPath, InverseForeignKey<O, MbRoleCustomDeptRecord> parentPath) {
        super(path, childPath, parentPath, MB_ROLE_CUSTOM_DEPT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbRoleCustomDeptPath extends MbRoleCustomDept implements Path<MbRoleCustomDeptRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbRoleCustomDeptPath(Table<O> path, ForeignKey<O, MbRoleCustomDeptRecord> childPath, InverseForeignKey<O, MbRoleCustomDeptRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbRoleCustomDeptPath(Name alias, Table<MbRoleCustomDeptRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbRoleCustomDeptPath as(String alias) {
            return new MbRoleCustomDeptPath(DSL.name(alias), this);
        }

        @Override
        public MbRoleCustomDeptPath as(Name alias) {
            return new MbRoleCustomDeptPath(alias, this);
        }

        @Override
        public MbRoleCustomDeptPath as(Table<?> alias) {
            return new MbRoleCustomDeptPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbRoleCustomDeptRecord> getPrimaryKey() {
        return Keys.MB_ROLE_CUSTOM_DEPT_PKEY;
    }

    @Override
    public List<ForeignKey<MbRoleCustomDeptRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_ROLE_CUSTOM_DEPT__MB_ROLE_CUSTOM_DEPT_DEPT_ID_FKEY, Keys.MB_ROLE_CUSTOM_DEPT__MB_ROLE_CUSTOM_DEPT_ROLE_ID_FKEY);
    }

    private transient MbDeptPath _mbDept;

    /**
     * Get the implicit join path to the <code>public.mb_dept</code> table.
     */
    public MbDeptPath mbDept() {
        if (_mbDept == null)
            _mbDept = new MbDeptPath(this, Keys.MB_ROLE_CUSTOM_DEPT__MB_ROLE_CUSTOM_DEPT_DEPT_ID_FKEY, null);

        return _mbDept;
    }

    private transient MbRolePath _mbRole;

    /**
     * Get the implicit join path to the <code>public.mb_role</code> table.
     */
    public MbRolePath mbRole() {
        if (_mbRole == null)
            _mbRole = new MbRolePath(this, Keys.MB_ROLE_CUSTOM_DEPT__MB_ROLE_CUSTOM_DEPT_ROLE_ID_FKEY, null);

        return _mbRole;
    }

    @Override
    public MbRoleCustomDept as(String alias) {
        return new MbRoleCustomDept(DSL.name(alias), this);
    }

    @Override
    public MbRoleCustomDept as(Name alias) {
        return new MbRoleCustomDept(alias, this);
    }

    @Override
    public MbRoleCustomDept as(Table<?> alias) {
        return new MbRoleCustomDept(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRoleCustomDept rename(String name) {
        return new MbRoleCustomDept(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRoleCustomDept rename(Name name) {
        return new MbRoleCustomDept(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbRoleCustomDept rename(Table<?> name) {
        return new MbRoleCustomDept(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRoleCustomDept where(Condition condition) {
        return new MbRoleCustomDept(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRoleCustomDept where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRoleCustomDept where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRoleCustomDept where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRoleCustomDept where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRoleCustomDept where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRoleCustomDept where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbRoleCustomDept where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRoleCustomDept whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbRoleCustomDept whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
