/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.records.MbSchemaProbeRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbSchemaProbe extends TableImpl<MbSchemaProbeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_schema_probe</code>
     */
    public static final MbSchemaProbe MB_SCHEMA_PROBE = new MbSchemaProbe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbSchemaProbeRecord> getRecordType() {
        return MbSchemaProbeRecord.class;
    }

    /**
     * The column <code>public.mb_schema_probe.id</code>.
     */
    public final TableField<MbSchemaProbeRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_schema_probe.owner_name</code>.
     */
    public final TableField<MbSchemaProbeRecord, String> OWNER_NAME = createField(DSL.name("owner_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.mb_schema_probe.created_at</code>.
     */
    public final TableField<MbSchemaProbeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbSchemaProbe(Name alias, Table<MbSchemaProbeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbSchemaProbe(Name alias, Table<MbSchemaProbeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_schema_probe</code> table reference
     */
    public MbSchemaProbe(String alias) {
        this(DSL.name(alias), MB_SCHEMA_PROBE);
    }

    /**
     * Create an aliased <code>public.mb_schema_probe</code> table reference
     */
    public MbSchemaProbe(Name alias) {
        this(alias, MB_SCHEMA_PROBE);
    }

    /**
     * Create a <code>public.mb_schema_probe</code> table reference
     */
    public MbSchemaProbe() {
        this(DSL.name("mb_schema_probe"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbSchemaProbeRecord> getPrimaryKey() {
        return Keys.MB_SCHEMA_PROBE_PKEY;
    }

    @Override
    public List<Check<MbSchemaProbeRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_schema_probe_owner_name_check"), "(((owner_name)::text = 'platform'::text))", true)
        );
    }

    @Override
    public MbSchemaProbe as(String alias) {
        return new MbSchemaProbe(DSL.name(alias), this);
    }

    @Override
    public MbSchemaProbe as(Name alias) {
        return new MbSchemaProbe(alias, this);
    }

    @Override
    public MbSchemaProbe as(Table<?> alias) {
        return new MbSchemaProbe(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbSchemaProbe rename(String name) {
        return new MbSchemaProbe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbSchemaProbe rename(Name name) {
        return new MbSchemaProbe(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbSchemaProbe rename(Table<?> name) {
        return new MbSchemaProbe(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbSchemaProbe where(Condition condition) {
        return new MbSchemaProbe(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbSchemaProbe where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbSchemaProbe where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbSchemaProbe where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbSchemaProbe where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbSchemaProbe where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbSchemaProbe where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbSchemaProbe where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbSchemaProbe whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbSchemaProbe whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
