/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbAuthzRefreshOutbox.MbAuthzRefreshOutboxPath;
import com.metabuild.schema.platform.tables.MbCredentialRevocationOutbox.MbCredentialRevocationOutboxPath;
import com.metabuild.schema.platform.tables.MbDept.MbDeptPath;
import com.metabuild.schema.platform.tables.MbInboxMessage.MbInboxMessagePath;
import com.metabuild.schema.platform.tables.MbInboxPublishOutbox.MbInboxPublishOutboxPath;
import com.metabuild.schema.platform.tables.MbLoginAuditOutbox.MbLoginAuditOutboxPath;
import com.metabuild.schema.platform.tables.MbLoginLog.MbLoginLogPath;
import com.metabuild.schema.platform.tables.MbOperationLog.MbOperationLogPath;
import com.metabuild.schema.platform.tables.MbRefreshToken.MbRefreshTokenPath;
import com.metabuild.schema.platform.tables.MbRole.MbRolePath;
import com.metabuild.schema.platform.tables.MbUserProfile.MbUserProfilePath;
import com.metabuild.schema.platform.tables.MbUserRole.MbUserRolePath;
import com.metabuild.schema.platform.tables.records.MbUserRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbUser extends TableImpl<MbUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_user</code>
     */
    public static final MbUser MB_USER = new MbUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbUserRecord> getRecordType() {
        return MbUserRecord.class;
    }

    /**
     * The column <code>public.mb_user.id</code>.
     */
    public final TableField<MbUserRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_user.dept_id</code>.
     */
    public final TableField<MbUserRecord, UUID> DEPT_ID = createField(DSL.name("dept_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.mb_user.username</code>.
     */
    public final TableField<MbUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_user.password_hash</code>.
     */
    public final TableField<MbUserRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_user.display_name</code>.
     */
    public final TableField<MbUserRecord, String> DISPLAY_NAME = createField(DSL.name("display_name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_user.email</code>.
     */
    public final TableField<MbUserRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_user.phone</code>.
     */
    public final TableField<MbUserRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.mb_user.status</code>.
     */
    public final TableField<MbUserRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user.authz_revision</code>.
     */
    public final TableField<MbUserRecord, Long> AUTHZ_REVISION = createField(DSL.name("authz_revision"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_user.deleted_at</code>.
     */
    public final TableField<MbUserRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_user.created_at</code>.
     */
    public final TableField<MbUserRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_user.updated_at</code>.
     */
    public final TableField<MbUserRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_user.credential_revision</code>.
     */
    public final TableField<MbUserRecord, Long> CREDENTIAL_REVISION = createField(DSL.name("credential_revision"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private MbUser(Name alias, Table<MbUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbUser(Name alias, Table<MbUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_user</code> table reference
     */
    public MbUser(String alias) {
        this(DSL.name(alias), MB_USER);
    }

    /**
     * Create an aliased <code>public.mb_user</code> table reference
     */
    public MbUser(Name alias) {
        this(alias, MB_USER);
    }

    /**
     * Create a <code>public.mb_user</code> table reference
     */
    public MbUser() {
        this(DSL.name("mb_user"), null);
    }

    public <O extends Record> MbUser(Table<O> path, ForeignKey<O, MbUserRecord> childPath, InverseForeignKey<O, MbUserRecord> parentPath) {
        super(path, childPath, parentPath, MB_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbUserPath extends MbUser implements Path<MbUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbUserPath(Table<O> path, ForeignKey<O, MbUserRecord> childPath, InverseForeignKey<O, MbUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbUserPath(Name alias, Table<MbUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbUserPath as(String alias) {
            return new MbUserPath(DSL.name(alias), this);
        }

        @Override
        public MbUserPath as(Name alias) {
            return new MbUserPath(alias, this);
        }

        @Override
        public MbUserPath as(Table<?> alias) {
            return new MbUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_USER_DEPT_ACTIVE_IDX);
    }

    @Override
    public UniqueKey<MbUserRecord> getPrimaryKey() {
        return Keys.MB_USER_PKEY;
    }

    @Override
    public List<ForeignKey<MbUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_USER__MB_USER_DEPT_ID_FKEY);
    }

    private transient MbDeptPath _mbDept;

    /**
     * Get the implicit join path to the <code>public.mb_dept</code> table.
     */
    public MbDeptPath mbDept() {
        if (_mbDept == null)
            _mbDept = new MbDeptPath(this, Keys.MB_USER__MB_USER_DEPT_ID_FKEY, null);

        return _mbDept;
    }

    private transient MbAuthzRefreshOutboxPath _mbAuthzRefreshOutbox;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_authz_refresh_outbox</code> table
     */
    public MbAuthzRefreshOutboxPath mbAuthzRefreshOutbox() {
        if (_mbAuthzRefreshOutbox == null)
            _mbAuthzRefreshOutbox = new MbAuthzRefreshOutboxPath(this, null, Keys.MB_AUTHZ_REFRESH_OUTBOX__MB_AUTHZ_REFRESH_OUTBOX_USER_ID_FKEY.getInverseKey());

        return _mbAuthzRefreshOutbox;
    }

    private transient MbCredentialRevocationOutboxPath _mbCredentialRevocationOutbox;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_credential_revocation_outbox</code> table
     */
    public MbCredentialRevocationOutboxPath mbCredentialRevocationOutbox() {
        if (_mbCredentialRevocationOutbox == null)
            _mbCredentialRevocationOutbox = new MbCredentialRevocationOutboxPath(this, null, Keys.MB_CREDENTIAL_REVOCATION_OUTBOX__MB_CREDENTIAL_REVOCATION_OUTBOX_USER_ID_FKEY.getInverseKey());

        return _mbCredentialRevocationOutbox;
    }

    private transient MbInboxMessagePath _mbInboxMessageDecidedByFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_inbox_message</code> table, via the
     * <code>mb_inbox_message_decided_by_fkey</code> key
     */
    public MbInboxMessagePath mbInboxMessageDecidedByFkey() {
        if (_mbInboxMessageDecidedByFkey == null)
            _mbInboxMessageDecidedByFkey = new MbInboxMessagePath(this, null, Keys.MB_INBOX_MESSAGE__MB_INBOX_MESSAGE_DECIDED_BY_FKEY.getInverseKey());

        return _mbInboxMessageDecidedByFkey;
    }

    private transient MbInboxMessagePath _mbInboxMessageRecipientUserIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_inbox_message</code> table, via the
     * <code>mb_inbox_message_recipient_user_id_fkey</code> key
     */
    public MbInboxMessagePath mbInboxMessageRecipientUserIdFkey() {
        if (_mbInboxMessageRecipientUserIdFkey == null)
            _mbInboxMessageRecipientUserIdFkey = new MbInboxMessagePath(this, null, Keys.MB_INBOX_MESSAGE__MB_INBOX_MESSAGE_RECIPIENT_USER_ID_FKEY.getInverseKey());

        return _mbInboxMessageRecipientUserIdFkey;
    }

    private transient MbInboxPublishOutboxPath _mbInboxPublishOutbox;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_inbox_publish_outbox</code> table
     */
    public MbInboxPublishOutboxPath mbInboxPublishOutbox() {
        if (_mbInboxPublishOutbox == null)
            _mbInboxPublishOutbox = new MbInboxPublishOutboxPath(this, null, Keys.MB_INBOX_PUBLISH_OUTBOX__MB_INBOX_PUBLISH_OUTBOX_RECIPIENT_USER_ID_FKEY.getInverseKey());

        return _mbInboxPublishOutbox;
    }

    private transient MbLoginAuditOutboxPath _mbLoginAuditOutbox;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_login_audit_outbox</code> table
     */
    public MbLoginAuditOutboxPath mbLoginAuditOutbox() {
        if (_mbLoginAuditOutbox == null)
            _mbLoginAuditOutbox = new MbLoginAuditOutboxPath(this, null, Keys.MB_LOGIN_AUDIT_OUTBOX__MB_LOGIN_AUDIT_OUTBOX_USER_ID_FKEY.getInverseKey());

        return _mbLoginAuditOutbox;
    }

    private transient MbLoginLogPath _mbLoginLog;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_login_log</code> table
     */
    public MbLoginLogPath mbLoginLog() {
        if (_mbLoginLog == null)
            _mbLoginLog = new MbLoginLogPath(this, null, Keys.MB_LOGIN_LOG__MB_LOGIN_LOG_USER_ID_FKEY.getInverseKey());

        return _mbLoginLog;
    }

    private transient MbOperationLogPath _mbOperationLog;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_operation_log</code> table
     */
    public MbOperationLogPath mbOperationLog() {
        if (_mbOperationLog == null)
            _mbOperationLog = new MbOperationLogPath(this, null, Keys.MB_OPERATION_LOG__MB_OPERATION_LOG_ACTOR_ID_FKEY.getInverseKey());

        return _mbOperationLog;
    }

    private transient MbRefreshTokenPath _mbRefreshToken;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_refresh_token</code> table
     */
    public MbRefreshTokenPath mbRefreshToken() {
        if (_mbRefreshToken == null)
            _mbRefreshToken = new MbRefreshTokenPath(this, null, Keys.MB_REFRESH_TOKEN__MB_REFRESH_TOKEN_USER_ID_FKEY.getInverseKey());

        return _mbRefreshToken;
    }

    private transient MbUserProfilePath _mbUserProfile;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_user_profile</code> table
     */
    public MbUserProfilePath mbUserProfile() {
        if (_mbUserProfile == null)
            _mbUserProfile = new MbUserProfilePath(this, null, Keys.MB_USER_PROFILE__MB_USER_PROFILE_USER_ID_FKEY.getInverseKey());

        return _mbUserProfile;
    }

    private transient MbUserRolePath _mbUserRole;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_user_role</code> table
     */
    public MbUserRolePath mbUserRole() {
        if (_mbUserRole == null)
            _mbUserRole = new MbUserRolePath(this, null, Keys.MB_USER_ROLE__MB_USER_ROLE_USER_ID_FKEY.getInverseKey());

        return _mbUserRole;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_role</code> table
     */
    public MbRolePath mbRole() {
        return mbUserRole().mbRole();
    }

    @Override
    public List<Check<MbUserRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("mb_user_authz_revision_check"), "((authz_revision >= 0))", true),
            Internal.createCheck(this, DSL.name("mb_user_credential_revision_nonnegative"), "((credential_revision >= 0))", true),
            Internal.createCheck(this, DSL.name("mb_user_status_check"), "(((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying, 'UNACTIVATED'::character varying, 'LEFT'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbUser as(String alias) {
        return new MbUser(DSL.name(alias), this);
    }

    @Override
    public MbUser as(Name alias) {
        return new MbUser(alias, this);
    }

    @Override
    public MbUser as(Table<?> alias) {
        return new MbUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUser rename(String name) {
        return new MbUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUser rename(Name name) {
        return new MbUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUser rename(Table<?> name) {
        return new MbUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUser where(Condition condition) {
        return new MbUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
