/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Indexes;
import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbRole.MbRolePath;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbUserRoleRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbUserRole extends TableImpl<MbUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_user_role</code>
     */
    public static final MbUserRole MB_USER_ROLE = new MbUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbUserRoleRecord> getRecordType() {
        return MbUserRoleRecord.class;
    }

    /**
     * The column <code>public.mb_user_role.user_id</code>.
     */
    public final TableField<MbUserRoleRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_user_role.role_id</code>.
     */
    public final TableField<MbUserRoleRecord, UUID> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_user_role.created_at</code>.
     */
    public final TableField<MbUserRoleRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbUserRole(Name alias, Table<MbUserRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbUserRole(Name alias, Table<MbUserRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_user_role</code> table reference
     */
    public MbUserRole(String alias) {
        this(DSL.name(alias), MB_USER_ROLE);
    }

    /**
     * Create an aliased <code>public.mb_user_role</code> table reference
     */
    public MbUserRole(Name alias) {
        this(alias, MB_USER_ROLE);
    }

    /**
     * Create a <code>public.mb_user_role</code> table reference
     */
    public MbUserRole() {
        this(DSL.name("mb_user_role"), null);
    }

    public <O extends Record> MbUserRole(Table<O> path, ForeignKey<O, MbUserRoleRecord> childPath, InverseForeignKey<O, MbUserRoleRecord> parentPath) {
        super(path, childPath, parentPath, MB_USER_ROLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbUserRolePath extends MbUserRole implements Path<MbUserRoleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbUserRolePath(Table<O> path, ForeignKey<O, MbUserRoleRecord> childPath, InverseForeignKey<O, MbUserRoleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbUserRolePath(Name alias, Table<MbUserRoleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbUserRolePath as(String alias) {
            return new MbUserRolePath(DSL.name(alias), this);
        }

        @Override
        public MbUserRolePath as(Name alias) {
            return new MbUserRolePath(alias, this);
        }

        @Override
        public MbUserRolePath as(Table<?> alias) {
            return new MbUserRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MB_USER_ROLE_ROLE_IDX);
    }

    @Override
    public UniqueKey<MbUserRoleRecord> getPrimaryKey() {
        return Keys.MB_USER_ROLE_PKEY;
    }

    @Override
    public List<ForeignKey<MbUserRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_USER_ROLE__MB_USER_ROLE_ROLE_ID_FKEY, Keys.MB_USER_ROLE__MB_USER_ROLE_USER_ID_FKEY);
    }

    private transient MbRolePath _mbRole;

    /**
     * Get the implicit join path to the <code>public.mb_role</code> table.
     */
    public MbRolePath mbRole() {
        if (_mbRole == null)
            _mbRole = new MbRolePath(this, Keys.MB_USER_ROLE__MB_USER_ROLE_ROLE_ID_FKEY, null);

        return _mbRole;
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table.
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, Keys.MB_USER_ROLE__MB_USER_ROLE_USER_ID_FKEY, null);

        return _mbUser;
    }

    @Override
    public MbUserRole as(String alias) {
        return new MbUserRole(DSL.name(alias), this);
    }

    @Override
    public MbUserRole as(Name alias) {
        return new MbUserRole(alias, this);
    }

    @Override
    public MbUserRole as(Table<?> alias) {
        return new MbUserRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserRole rename(String name) {
        return new MbUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserRole rename(Name name) {
        return new MbUserRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserRole rename(Table<?> name) {
        return new MbUserRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserRole where(Condition condition) {
        return new MbUserRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
