/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.platform.tables;


import com.metabuild.schema.platform.Keys;
import com.metabuild.schema.platform.Public;
import com.metabuild.schema.platform.tables.MbUser.MbUserPath;
import com.metabuild.schema.platform.tables.records.MbUserProfileRecord;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbUserProfile extends TableImpl<MbUserProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_user_profile</code>
     */
    public static final MbUserProfile MB_USER_PROFILE = new MbUserProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbUserProfileRecord> getRecordType() {
        return MbUserProfileRecord.class;
    }

    /**
     * The column <code>public.mb_user_profile.user_id</code>.
     */
    public final TableField<MbUserProfileRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mb_user_profile.location</code>.
     */
    public final TableField<MbUserProfileRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.VARCHAR(200).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user_profile.employee_no</code>.
     */
    public final TableField<MbUserProfileRecord, String> EMPLOYEE_NO = createField(DSL.name("employee_no"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user_profile.title</code>.
     */
    public final TableField<MbUserProfileRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user_profile.joined_date</code>.
     */
    public final TableField<MbUserProfileRecord, LocalDate> JOINED_DATE = createField(DSL.name("joined_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.mb_user_profile.manager_name</code>.
     */
    public final TableField<MbUserProfileRecord, String> MANAGER_NAME = createField(DSL.name("manager_name"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user_profile.language</code>.
     */
    public final TableField<MbUserProfileRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'zh-CN'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user_profile.timezone</code>.
     */
    public final TableField<MbUserProfileRecord, String> TIMEZONE = createField(DSL.name("timezone"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field(DSL.raw("'Asia/Shanghai'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user_profile.bio</code>.
     */
    public final TableField<MbUserProfileRecord, String> BIO = createField(DSL.name("bio"), SQLDataType.VARCHAR(2000).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_user_profile.email_verified</code>.
     */
    public final TableField<MbUserProfileRecord, Boolean> EMAIL_VERIFIED = createField(DSL.name("email_verified"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_user_profile.two_factor</code>.
     */
    public final TableField<MbUserProfileRecord, Boolean> TWO_FACTOR = createField(DSL.name("two_factor"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_user_profile.email_alert</code>.
     */
    public final TableField<MbUserProfileRecord, Boolean> EMAIL_ALERT = createField(DSL.name("email_alert"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_user_profile.new_device_alert</code>.
     */
    public final TableField<MbUserProfileRecord, Boolean> NEW_DEVICE_ALERT = createField(DSL.name("new_device_alert"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_user_profile.weekly_digest</code>.
     */
    public final TableField<MbUserProfileRecord, Boolean> WEEKLY_DIGEST = createField(DSL.name("weekly_digest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_user_profile.compact_notifications</code>.
     */
    public final TableField<MbUserProfileRecord, Boolean> COMPACT_NOTIFICATIONS = createField(DSL.name("compact_notifications"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_user_profile.updated_at</code>.
     */
    public final TableField<MbUserProfileRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbUserProfile(Name alias, Table<MbUserProfileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbUserProfile(Name alias, Table<MbUserProfileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_user_profile</code> table reference
     */
    public MbUserProfile(String alias) {
        this(DSL.name(alias), MB_USER_PROFILE);
    }

    /**
     * Create an aliased <code>public.mb_user_profile</code> table reference
     */
    public MbUserProfile(Name alias) {
        this(alias, MB_USER_PROFILE);
    }

    /**
     * Create a <code>public.mb_user_profile</code> table reference
     */
    public MbUserProfile() {
        this(DSL.name("mb_user_profile"), null);
    }

    public <O extends Record> MbUserProfile(Table<O> path, ForeignKey<O, MbUserProfileRecord> childPath, InverseForeignKey<O, MbUserProfileRecord> parentPath) {
        super(path, childPath, parentPath, MB_USER_PROFILE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MbUserProfilePath extends MbUserProfile implements Path<MbUserProfileRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbUserProfilePath(Table<O> path, ForeignKey<O, MbUserProfileRecord> childPath, InverseForeignKey<O, MbUserProfileRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbUserProfilePath(Name alias, Table<MbUserProfileRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbUserProfilePath as(String alias) {
            return new MbUserProfilePath(DSL.name(alias), this);
        }

        @Override
        public MbUserProfilePath as(Name alias) {
            return new MbUserProfilePath(alias, this);
        }

        @Override
        public MbUserProfilePath as(Table<?> alias) {
            return new MbUserProfilePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbUserProfileRecord> getPrimaryKey() {
        return Keys.MB_USER_PROFILE_PKEY;
    }

    @Override
    public List<ForeignKey<MbUserProfileRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_USER_PROFILE__MB_USER_PROFILE_USER_ID_FKEY);
    }

    private transient MbUserPath _mbUser;

    /**
     * Get the implicit join path to the <code>public.mb_user</code> table.
     */
    public MbUserPath mbUser() {
        if (_mbUser == null)
            _mbUser = new MbUserPath(this, Keys.MB_USER_PROFILE__MB_USER_PROFILE_USER_ID_FKEY, null);

        return _mbUser;
    }

    @Override
    public MbUserProfile as(String alias) {
        return new MbUserProfile(DSL.name(alias), this);
    }

    @Override
    public MbUserProfile as(Name alias) {
        return new MbUserProfile(alias, this);
    }

    @Override
    public MbUserProfile as(Table<?> alias) {
        return new MbUserProfile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserProfile rename(String name) {
        return new MbUserProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserProfile rename(Name name) {
        return new MbUserProfile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserProfile rename(Table<?> name) {
        return new MbUserProfile(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserProfile where(Condition condition) {
        return new MbUserProfile(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserProfile where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserProfile where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserProfile where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserProfile where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserProfile where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserProfile where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserProfile where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserProfile whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserProfile whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
