package com.metabuild.modules.admin.roles.persistence;
import com.metabuild.modules.admin.roles.application.*; import com.metabuild.shared.kernel.*; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate;
public final class JdbcRoleRepository implements RoleRepository {
 private final JdbcTemplate jdbc;public JdbcRoleRepository(JdbcTemplate j){jdbc=j;}
 public List<RoleView> list(){return jdbc.query("select id,name,system_role,description from mb_role where deleted_at is null order by name",(r,n)->new RoleView(r.getObject(1,UUID.class),r.getString(2),r.getBoolean(3)?"system":"custom",Objects.toString(r.getString(4),""),null));}
 public Optional<RoleView> find(UUID id){return list().stream().filter(r->r.id().equals(id)).findFirst();}
 public RoleView create(UUID id,String name,String description){jdbc.update("insert into mb_role(id,code,name,description,data_scope_type) values(?,?,?,?,'SELF')",id,"CUSTOM_"+id,name,description==null?"":description);return find(id).orElseThrow();}
 public RoleView update(UUID id,String name,String description){protect(id);int n=jdbc.update("update mb_role set name=coalesce(?,name),description=coalesce(?,description),updated_at=current_timestamp where id=? and deleted_at is null",name,description,id);if(n==0)throw notFound();return find(id).orElseThrow();}
 public List<RoleMember> memberViews(UUID role){return jdbc.query("select u.id,u.display_name,d.name from mb_user_role ur join mb_user u on u.id=ur.user_id and u.deleted_at is null left join mb_dept d on d.id=u.dept_id where ur.role_id=? order by u.display_name",(r,n)->new RoleMember(r.getObject(1,UUID.class),r.getString(2),Objects.toString(r.getString(3),""),""),role);}
 public List<PermissionGroup> permissionTree(){Map<String,Map<String,List<PermissionAction>>> tree=new LinkedHashMap<>();jdbc.query("select code from mb_permission where status='ACTIVE' and deleted_at is null order by code",r->{String[] p=r.getString(1).split(":",3);tree.computeIfAbsent(p[0],k->new LinkedHashMap<>()).computeIfAbsent(p[0]+":"+p[1],k->new ArrayList<>()).add(new PermissionAction(p[2],p[2]));});return tree.entrySet().stream().map(g->new PermissionGroup(g.getKey(),g.getKey(),g.getValue().entrySet().stream().map(e->new PermissionResource(e.getKey(),e.getKey(),e.getKey(),e.getValue())).toList())).toList();}
 public List<RoleAuditLog> auditLogs(){return jdbc.query("select o.id,o.created_at,coalesce(u.display_name,'system'),o.resource_id,coalesce(r.name,'deleted role'),case when o.operation ilike '%create%' then 'create' when o.operation ilike '%grant%' or o.operation ilike '%permission%' then 'grant' when o.operation ilike '%delete%' or o.operation ilike '%remove%' then 'remove' when o.operation ilike '%scope%' then 'dataScope' else 'edit' end,coalesce(o.detail->>'change',o.operation) from mb_operation_log o left join mb_user u on u.id=o.actor_id left join mb_role r on r.id=o.resource_id where lower(o.resource_type)='role' and o.resource_id is not null order by o.created_at desc limit 500",(r,n)->new RoleAuditLog(r.getObject(1,UUID.class),r.getTimestamp(2).toInstant(),r.getString(3),r.getObject(4,UUID.class),r.getString(5),r.getString(6),r.getString(7)));}
 public void delete(UUID id){protect(id);jdbc.update("update mb_role set deleted_at=current_timestamp,status='DISABLED' where id=?",id);}
 public void disable(UUID id){protect(id);jdbc.update("update mb_role set status='DISABLED' where id=? and deleted_at is null",id);}
 public void replacePermissions(UUID id,Map<String,Set<String>> grants){protect(id);Set<String> codes=new LinkedHashSet<>();grants.forEach((resource,actions)->actions.forEach(action->codes.add(resource+":"+action)));if(!codes.isEmpty()){Integer count=jdbc.queryForObject("select count(*) from mb_permission where code=any(?) and status='ACTIVE' and deleted_at is null",Integer.class,(Object)codes.toArray(String[]::new));if(count==null||count!=codes.size())throw new BadRequest(()->"iam.role.permission-invalid","Permission set contains unknown or deprecated IDs");}jdbc.update("delete from mb_role_permission where role_id=?",id);if(!codes.isEmpty())jdbc.update("insert into mb_role_permission(role_id,permission_id) select ?,id from mb_permission where code=any(?) and status='ACTIVE' and deleted_at is null",id,(Object)codes.toArray(String[]::new));}
 public void replaceDataScope(UUID id,DataScope scope,Set<UUID> depts){protect(id);if(scope!=DataScope.CUSTOM_DEPT&&!depts.isEmpty())throw new BadRequest(() -> "iam.role.scope-invalid","Only custom scope accepts departments");jdbc.update("update mb_role set data_scope_type=? where id=? and deleted_at is null",scope.name(),id);jdbc.update("delete from mb_role_custom_dept where role_id=?",id);if(scope==DataScope.CUSTOM_DEPT&&!depts.isEmpty())jdbc.update("insert into mb_role_custom_dept(role_id,dept_id) select ?,unnest(?)",id,(Object)depts.toArray(UUID[]::new));}
 public Map<String,Set<String>> permissions(UUID id){Map<String,Set<String>> result=new LinkedHashMap<>();jdbc.query("select p.code from mb_role_permission rp join mb_permission p on p.id=rp.permission_id where rp.role_id=? and p.status='ACTIVE' and p.deleted_at is null order by p.code",r->{String[] p=r.getString(1).split(":",3);result.computeIfAbsent(p[0]+":"+p[1],k->new LinkedHashSet<>()).add(p[2]);},id);return result;}
 public DataScopeGrant dataScope(UUID id){DataScope scope=DataScope.valueOf(jdbc.queryForObject("select data_scope_type from mb_role where id=? and deleted_at is null",String.class,id));Set<UUID> ids=scope==DataScope.CUSTOM_DEPT?Set.copyOf(jdbc.queryForList("select dept_id from mb_role_custom_dept where role_id=?",UUID.class,id)):Set.of();return new DataScopeGrant(scope,ids);}
 public Set<UUID> members(UUID role){return Set.copyOf(jdbc.queryForList("select user_id from mb_user_role where role_id=?",UUID.class,role));}
 private void protect(UUID id){List<Boolean> rows=jdbc.queryForList("select system_role from mb_role where id=? and deleted_at is null",Boolean.class,id);if(rows.isEmpty())throw notFound();if(Boolean.TRUE.equals(rows.getFirst()))throw new Conflict(() -> "iam.role.system-protected","System role cannot be changed");}
 private static NotFound notFound(){return new NotFound(()->"iam.role.not-found","Role not found");}
}
