package com.metabuild.modules.admin.iam;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.assertj.core.api.Assertions.*;
import com.metabuild.admin.api.*;
import com.metabuild.modules.admin.auth.api.AuthorizationRefreshService;
import com.metabuild.modules.admin.users.application.*;
import com.metabuild.modules.admin.users.controller.UserControllerContract;
import com.metabuild.modules.admin.roles.application.*;
import com.metabuild.modules.admin.roles.controller.RoleControllerContract;
import com.metabuild.modules.admin.departments.application.*;
import com.metabuild.modules.admin.departments.controller.DepartmentControllerContract;
import com.metabuild.shared.kernel.*;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

class IamControllerMockMvcTest {
 @Test void currentFrontendRoleStringCreatesDirectResponse() throws Exception {UUID dept=UUID.fromString("01900000-0000-7000-8000-000000000001");var repo=new ContractUsers(dept);var controller=new TestUserController(new UserControllerContract(new UserService(repo,new InlineExecutor()),new UuidV7Generator()));var mvc=MockMvcBuilders.standaloneSetup(controller).setControllerAdvice(new ProblemAdvice()).build();String json="{\"name\":\"Alice\",\"deptId\":\"%s\",\"role\":\"SYSTEM_ADMIN\",\"phone\":\"1\",\"email\":\"alice@example.test\"}".formatted(dept);String body=mvc.perform(post("/api/users").contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().isOk()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON)).andReturn().getResponse().getContentAsString();assertThat(body).contains("\"name\":\"Alice\"","\"role\":\"SYSTEM_ADMIN\"","\"id\":").doesNotContain("\"list\"");}
 @Test void invalidDtoUsesProblemDetailDialect() throws Exception {var controller=new TestUserController(new UserControllerContract(new UserService(new ContractUsers(UUID.randomUUID()),new InlineExecutor()),new UuidV7Generator()));var mvc=MockMvcBuilders.standaloneSetup(controller).setControllerAdvice(new ProblemAdvice()).build();String body=mvc.perform(post("/api/users").contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isBadRequest()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON)).andReturn().getResponse().getContentAsString();assertThat(body).contains("\"code\":\"request.validation.failed\"");}
 @Test void roleAndDepartmentFixturesMatchFrontendShapes() throws Exception {UUID id=UUID.fromString("01900000-0000-7000-8000-000000000099");var role=new RoleControllerContract(new RoleService(new ContractRoles(id),new InlineExecutor()),new UuidV7Generator());var dept=new DepartmentControllerContract(new DepartmentService(new ContractDepts(id),new InlineExecutor()),new UuidV7Generator());var mvc=MockMvcBuilders.standaloneSetup(new TestRoleController(role),new TestDeptController(dept)).setControllerAdvice(new ProblemAdvice()).build();String roles=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/roles")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertThat(roles).contains("\"id\":","\"name\":","\"type\":","\"desc\":");String tree=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/permissions/tree")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertThat(tree).contains("\"resources\":","\"actions\":","\"code\":");String depts=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/depts")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertThat(depts).contains("\"parentId\":","\"memberCount\":");}
 @Test void completeRoleAndDepartmentEndpointMatrixIsDirectJsonOrVoid() throws Exception {UUID id=UUID.fromString("01900000-0000-7000-8000-000000000099");var role=new RoleControllerContract(new RoleService(new ContractRoles(id),new InlineExecutor()),new UuidV7Generator());var dept=new DepartmentControllerContract(new DepartmentService(new ContractDepts(id),new InlineExecutor()),new UuidV7Generator());var user=new UserControllerContract(new UserService(new ContractUsers(id),new InlineExecutor()),new UuidV7Generator());var mvc=MockMvcBuilders.standaloneSetup(new TestRoleController(role),new TestDeptController(dept),new TestUserController(user)).setControllerAdvice(new ProblemAdvice()).build();for(String path:List.of("/api/roles/"+id,"/api/roles/"+id+"/permissions","/api/roles/"+id+"/data-permissions","/api/roles/"+id+"/members","/api/role-audit-logs"))mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get(path)).andExpect(status().isOk()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON));mvc.perform(post("/api/roles").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"New\"}")).andExpect(status().isOk());mvc.perform(post("/api/roles").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\" \"}")).andExpect(status().isBadRequest()).andExpect(content().string(org.hamcrest.Matchers.containsString("request.validation.failed")));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put("/api/roles/"+id+"/data-permissions").contentType(MediaType.APPLICATION_JSON).content("{\"defaultScope\":null,\"defaultDepartmentIds\":null,\"resources\":null}")).andExpect(status().isBadRequest()).andExpect(content().string(org.hamcrest.Matchers.containsString("request.validation.failed")));mvc.perform(post("/api/roles/"+id+"/disable")).andExpect(status().isNoContent()).andExpect(content().string(""));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete("/api/roles/"+id)).andExpect(status().isNoContent()).andExpect(content().string(""));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete("/api/users/"+id)).andExpect(status().isNoContent()).andExpect(content().string(""));mvc.perform(post("/api/depts").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Child\"}")).andExpect(status().isOk());mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put("/api/depts/"+id).contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isBadRequest()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON));}
 static final class InlineExecutor implements AuthorizationRefreshService {public <T>T execute(Cause c,AuthorizationChange<T>x){x.affectedUserIds();return x.mutate();}public <T>T executeTerminal(TerminalChange<T>x){x.affectedUserIds();return x.mutate();}}
 static final class ContractUsers implements UserRepository {final UUID dept;ContractUsers(UUID d){dept=d;}public UserView create(UUID id,String name,UUID d,String role,String phone,String email){return new UserView(id,name,d,role,phone,email,"active",Instant.parse("2026-01-01T00:00:00Z"));}public PageResult<UserView> search(int a,int b,String c,UUID d,boolean e,String f){return new PageResult<>(List.of(),0);}public Optional<UserView> find(UUID i){return Optional.empty();}public UserView update(UUID a,UserPatch p){return null;}public Set<UUID> softDelete(UUID i){return Set.of(i);}public Set<UUID> disable(Set<UUID> i){return i;}public Set<UUID> moveToDepartment(Set<UUID> i,UUID d){return i;}public Set<UUID> usersInDepartments(Set<UUID> d){return Set.of();}public BatchResult<UUID,UserSummary> batchGet(Set<UUID> i){return new BatchResult<>(Map.of(),i);}}
 @RestControllerAdvice static final class ProblemAdvice {@ExceptionHandler(DomainException.class) ResponseEntity<ProblemDetail> domain(DomainException e){ProblemDetail p=ProblemDetail.forStatus(HttpStatus.BAD_REQUEST);p.setDetail(e.getMessage());p.setProperty("code",e.errorCode().code());return ResponseEntity.of(p).build();}}
 @RestController @RequestMapping("/api/users") static final class TestUserController {private final UserControllerContract delegate;TestUserController(UserControllerContract d){delegate=d;}@PostMapping UserView create(@RequestBody UserControllerContract.CreateUserWrite body){return delegate.create(body);}@DeleteMapping("/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)void delete(@PathVariable UUID id){delegate.delete(id);}}
 @RestController static final class TestRoleController {private final RoleControllerContract d;TestRoleController(RoleControllerContract d){this.d=d;}@GetMapping("/api/roles") List<RoleView> roles(){return d.list();}@GetMapping("/api/roles/{id}")RoleView detail(@PathVariable UUID id){return d.detail(id);}@GetMapping("/api/permissions/tree") List<RoleRepository.PermissionGroup> tree(){return d.tree();}@GetMapping("/api/roles/{id}/permissions")Map<String,Set<String>> grants(@PathVariable UUID id){return d.permissions(id);}@GetMapping("/api/roles/{id}/data-permissions")RoleControllerContract.DataPermission data(@PathVariable UUID id){return d.data(id);}@GetMapping("/api/roles/{id}/members")List<RoleRepository.RoleMember> members(@PathVariable UUID id){return d.members(id);}@GetMapping("/api/role-audit-logs")List<RoleRepository.RoleAuditLog> audits(){return d.audits();}@PostMapping("/api/roles")RoleView create(@RequestBody RoleControllerContract.Create b){return d.create(b);}@PutMapping("/api/roles/{id}")RoleView update(@PathVariable UUID id,@RequestBody RoleControllerContract.Create b){return d.update(id,b);}@PutMapping("/api/roles/{id}/permissions")Map<String,Set<String>> save(@PathVariable UUID id,@RequestBody Map<String,Set<String>> b){return d.savePermissions(id,b);}@PutMapping("/api/roles/{id}/data-permissions")RoleControllerContract.DataPermission scope(@PathVariable UUID id,@RequestBody RoleControllerContract.DataPermission b){return d.saveData(id,b);}@PostMapping("/api/roles/{id}/disable")@ResponseStatus(HttpStatus.NO_CONTENT)void disable(@PathVariable UUID id){d.disable(id);}@DeleteMapping("/api/roles/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)void delete(@PathVariable UUID id){d.delete(id);}}
 @RestController static final class TestDeptController {private final DepartmentControllerContract d;TestDeptController(DepartmentControllerContract d){this.d=d;}@GetMapping("/api/depts") List<DepartmentView> tree(){return d.tree();}@PostMapping("/api/depts")DepartmentView create(@RequestBody DepartmentControllerContract.CreateWrite b){return d.create(b);}@PutMapping("/api/depts/{id}")DepartmentView update(@PathVariable UUID id,@RequestBody DepartmentControllerContract.UpdateWrite b){return d.update(id,b);}}
 static final class ContractRoles implements RoleRepository {final UUID id;ContractRoles(UUID id){this.id=id;}public List<RoleView> list(){return List.of(new RoleView(id,"Role","custom","",null));}public Optional<RoleView> find(UUID i){return list().stream().findFirst();}public RoleView create(UUID i,String n,String d){return new RoleView(i,n,"custom",d,null);}public RoleView update(UUID i,String n,String d){return create(i,n,d);}public Set<UUID> members(UUID i){return Set.of();}public List<RoleMember> memberViews(UUID i){return List.of();}public List<PermissionGroup> permissionTree(){return List.of(new PermissionGroup("iam","iam",List.of(new PermissionResource("iam:user","iam:user","iam:user",List.of(new PermissionAction("view","view"))))));}public List<RoleAuditLog> auditLogs(){return List.of();}public void delete(UUID i){}public void disable(UUID i){}public void replacePermissions(UUID i,Map<String,Set<String>> g){}public void replaceDataScope(UUID i,DataScope s,Set<UUID>d){}public Map<String,Set<String>> permissions(UUID i){return Map.of("iam:user",Set.of("view"));}public DataScopeGrant dataScope(UUID i){return new DataScopeGrant(DataScope.SELF,Set.of());}}
 static final class ContractDepts implements DepartmentRepository {final UUID id;ContractDepts(UUID i){id=i;}public List<DepartmentView> tree(){return List.of(new DepartmentView(id,null,"Root",0,1));}public Optional<DepartmentView> find(UUID i){return tree().stream().findFirst();}public DepartmentView create(UUID i,String n,UUID p){return new DepartmentView(i,p,n,0,0);}public DepartmentMovePreimage movePreimage(UUID i,UUID p){return new DepartmentMovePreimage(Set.of());}public DepartmentView patch(UUID i,DepartmentPatch p){return new DepartmentView(i,p.parentId(),p.name(),0,0);}public Set<UUID> subtree(Set<UUID> r){return r;}public BatchResult<UUID,DepartmentSummary> batchGet(Set<UUID> i){return new BatchResult<>(Map.of(),i);}}
}
