package com.metabuild.modules.admin.iam;

import static org.assertj.core.api.Assertions.*;
import com.metabuild.modules.admin.departments.persistence.JdbcDepartmentRepository;
import com.metabuild.modules.admin.departments.application.DepartmentPatch;
import com.metabuild.modules.admin.roles.application.RoleRepository.DataScope;
import com.metabuild.modules.admin.roles.persistence.JdbcRoleRepository;
import com.metabuild.modules.admin.users.persistence.JdbcUserRepository;
import com.metabuild.schema.platform.PlatformFlywayRunner;
import com.metabuild.shared.kernel.UuidV7Generator;
import com.metabuild.shared.kernel.BadRequest;
import java.util.*;
import java.sql.*;
import java.lang.reflect.Proxy;
import java.util.concurrent.atomic.AtomicInteger;
import javax.sql.DataSource;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class IamRepositoryPostgresTest {
 static JdbcTemplate jdbc; static final UuidV7Generator IDS=new UuidV7Generator();
 @BeforeAll static void migrate(){String url=System.getProperty("task15.pg.url");Assumptions.assumeTrue(url!=null,"set -Dtask15.pg.url for real PostgreSQL");var ds=new DriverManagerDataSource(url,System.getProperty("task15.pg.user","ocean"),System.getProperty("task15.pg.password",""));PlatformFlywayRunner.migrate(ds);jdbc=new JdbcTemplate(ds);}
 @Test void batchAdaptersSupportPartialMissingAndUuidArrays(){var repo=new JdbcUserRepository(jdbc);UUID existing=UUID.fromString("01900000-0000-7000-8000-000000000010"),missing=IDS.generate();var result=repo.batchGet(Set.of(existing,missing));assertThat(result.found()).containsKey(existing);assertThat(result.missing()).containsExactly(missing);Set<UUID> tooMany=new HashSet<>();while(tooMany.size()<501)tooMany.add(IDS.generate());assertThatThrownBy(()->repo.batchGet(tooMany)).isInstanceOf(IllegalArgumentException.class);}
 @Test void departmentCycleAndSubtreeCountAreEnforced(){var depts=new JdbcDepartmentRepository(jdbc);UUID root=UUID.fromString("01900000-0000-7000-8000-000000000001"),child=IDS.generate();depts.create(child,"Child",root);assertThatThrownBy(()->depts.patch(root,new DepartmentPatch(false,null,true,child)));assertThat(depts.tree().stream().filter(d->d.id().equals(root)).findFirst().orElseThrow().memberCount()).isPositive();}
 @Test void systemRoleAndCustomScopeRulesAreEnforced(){var roles=new JdbcRoleRepository(jdbc);UUID system=UUID.fromString("01900000-0000-7000-8000-000000000020");assertThatThrownBy(()->roles.disable(system)).hasMessageContaining("System role");UUID role=IDS.generate();roles.create(role,"Custom","description");UUID root=UUID.fromString("01900000-0000-7000-8000-000000000001");roles.replaceDataScope(role,DataScope.CUSTOM_DEPT,Set.of(root));assertThat(roles.dataScope(role).departmentIds()).containsExactly(root);roles.replaceDataScope(role,DataScope.SELF,Set.of());assertThat(roles.dataScope(role).departmentIds()).isEmpty();}
 @Test void roleAuditReadsPersistedOperationLog(){UUID role=IDS.generate(),log=IDS.generate(),actor=UUID.fromString("01900000-0000-7000-8000-000000000010");var roles=new JdbcRoleRepository(jdbc);roles.create(role,"Audited","desc");jdbc.update("insert into mb_operation_log(id,actor_id,operation,resource_type,resource_id,success,detail) values(?,?,'role.permission.grant','role',?,true,'{\"change\":\"granted\"}'::jsonb)",log,actor,role);assertThat(roles.auditLogs()).anySatisfy(a->{assertThat(a.id()).isEqualTo(log);assertThat(a.kind()).isEqualTo("grant");assertThat(a.change()).isEqualTo("granted");});}
 @Test void permissionTreePutGetUsesStableIdsAndRejectsUnknownWithoutDataLoss(){var roles=new JdbcRoleRepository(jdbc);UUID role=IDS.generate();roles.create(role,"Grantable",null);var action=roles.permissionTree().stream().flatMap(g->g.resources().stream()).filter(r->!r.actions().isEmpty()).findFirst().orElseThrow();Map<String,Set<String>> selected=Map.of(action.id(),Set.of(action.actions().getFirst().id()));roles.replacePermissions(role,selected);assertThat(roles.permissions(role)).isEqualTo(selected);assertThatThrownBy(()->roles.replacePermissions(role,Map.of(action.id(),Set.of("missing")))).isInstanceOf(BadRequest.class);assertThat(roles.permissions(role)).isEqualTo(selected);assertThat(roles.find(role).orElseThrow().desc()).isEmpty();}
 @Test void softDeleteAllowsUniqueIdentityReuse(){var users=new JdbcUserRepository(jdbc);UUID root=UUID.fromString("01900000-0000-7000-8000-000000000001"),first=IDS.generate(),second=IDS.generate();String email="reuse-"+first+"@example.test";users.create(first,"First",root,"SYSTEM_ADMIN","1",email);users.softDelete(first);users.create(second,"Second",root,"System administrator","2",email);assertThat(users.find(second)).isPresent();}
 @Test void directoryAdaptersHaveFixedBatchQueryCounts(){var counting=new CountingDataSource(Objects.requireNonNull(jdbc.getDataSource()));var template=new JdbcTemplate(counting);var users=new com.metabuild.modules.admin.users.api.UserDirectoryAdapter(new JdbcUserRepository(template));var depts=new com.metabuild.modules.admin.departments.api.DepartmentDirectoryAdapter(new JdbcDepartmentRepository(template));users.batchGetUsers(Set.of());depts.batchGetDepartments(Set.of());assertThat(counting.count()).isZero();counting.reset();users.batchGetUsers(Set.of(UUID.fromString("01900000-0000-7000-8000-000000000010"),IDS.generate()));assertThat(counting.count()).isEqualTo(1);counting.reset();Set<UUID> fiveHundred=new LinkedHashSet<>();while(fiveHundred.size()<500)fiveHundred.add(IDS.generate());depts.batchGetDepartments(fiveHundred);assertThat(counting.count()).isEqualTo(1);fiveHundred.add(IDS.generate());counting.reset();assertThatThrownBy(()->users.batchGetUsers(fiveHundred)).isInstanceOf(IllegalArgumentException.class);assertThat(counting.count()).isZero();}
    @Test void partialPatchesPreserveAbsentFieldsAndStatusUsesExplicitCommands(){UUID root=UUID.fromString("01900000-0000-7000-8000-000000000001"),child=IDS.generate(),user=IDS.generate();var depts=new JdbcDepartmentRepository(jdbc);depts.create(child,"Before",root);depts.patch(child,new DepartmentPatch(true,"Renamed",false,null));assertThat(depts.find(child).orElseThrow().parentId()).isEqualTo(root);depts.patch(child,new DepartmentPatch(false,null,true,null));assertThat(depts.find(child).orElseThrow().parentId()).isNull();var users=new JdbcUserRepository(jdbc);users.create(user,"Before",root,"SYSTEM_ADMIN","1","patch-"+user+"@example.test");users.update(user,new com.metabuild.modules.admin.users.application.UserPatch(true,"After",false,null,false,null,false,null,false,null));assertThat(users.find(user).orElseThrow()).satisfies(v->{assertThat(v.name()).isEqualTo("After");assertThat(v.status()).isEqualTo("active");});users.disable(Set.of(user));assertThat(users.find(user).orElseThrow().status()).isEqualTo("disabled");users.enable(Set.of(user));assertThat(users.find(user).orElseThrow().status()).isEqualTo("active");assertThatThrownBy(()->users.update(IDS.generate(),new com.metabuild.modules.admin.users.application.UserPatch(true,"Missing",false,null,false,null,false,null,false,null))).isInstanceOf(com.metabuild.shared.kernel.NotFound.class);}
 static final class CountingDataSource extends org.springframework.jdbc.datasource.AbstractDataSource {private final DataSource delegate;private final AtomicInteger count=new AtomicInteger();CountingDataSource(DataSource d){delegate=d;}int count(){return count.get();}void reset(){count.set(0);}public Connection getConnection()throws SQLException{return wrap(delegate.getConnection());}public Connection getConnection(String u,String p)throws SQLException{return wrap(delegate.getConnection(u,p));}private Connection wrap(Connection c){return (Connection)Proxy.newProxyInstance(Connection.class.getClassLoader(),new Class[]{Connection.class},(proxy,m,args)->{if(m.getName().startsWith("prepareStatement"))count.incrementAndGet();try{return m.invoke(c,args);}catch(java.lang.reflect.InvocationTargetException e){throw e.getCause();}});}}
}
