import type { SubsystemManifest } from '@/modules/types';

export const lastmileManifest: SubsystemManifest = {
  subsystem: {
    key: 'lastmile',
    label: { 'zh-CN': '尾程快递', 'en-US': 'Last-mile Delivery' },
    desc: { 'zh-CN': '运单 · 终端客户 · 渠道', 'en-US': 'Shipments · Customers · Channels' },
    icon: 'truck',
    color: '#0891b2',
    home: '/lastmile/overview',
    builtin: false,
    enabled: true,
    sort: 2,
  },
  menuSeed: [
    {
      id: 'lm-overview-dir',
      parentId: null,
      subsystemKey: 'lastmile',
      type: 'dir',
      label: { 'zh-CN': '运营概览', 'en-US': 'Operations' },
      shortLabel: { 'zh-CN': '概览', 'en-US': 'Overview' },
      icon: 'chart-no-axes-combined',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-overview',
      parentId: 'lm-overview-dir',
      subsystemKey: 'lastmile',
      type: 'menu',
      label: { 'zh-CN': '运营概览', 'en-US': 'Operations Overview' },
      path: '/lastmile/overview',
      permission: 'lastmile:overview:view',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-shipments-dir',
      parentId: null,
      subsystemKey: 'lastmile',
      type: 'dir',
      label: { 'zh-CN': '运单管理', 'en-US': 'Shipments' },
      shortLabel: { 'zh-CN': '运单', 'en-US': 'Shipments' },
      icon: 'package',
      visible: true,
      sort: 2,
    },
    {
      id: 'lm-shipments',
      parentId: 'lm-shipments-dir',
      subsystemKey: 'lastmile',
      type: 'menu',
      label: { 'zh-CN': '运单列表', 'en-US': 'Shipment List' },
      path: '/lastmile/shipments',
      permission: 'lastmile:shipment:view',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-shipment-create',
      parentId: 'lm-shipments',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '新建运单', 'en-US': 'Create Shipment' },
      permission: 'lastmile:shipment:create',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-shipment-print',
      parentId: 'lm-shipments',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '打印面单', 'en-US': 'Print Label' },
      permission: 'lastmile:shipment:print',
      visible: true,
      sort: 2,
    },
    {
      id: 'lm-shipment-export',
      parentId: 'lm-shipments',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '导出运单', 'en-US': 'Export Shipments' },
      permission: 'lastmile:shipment:export',
      visible: true,
      sort: 3,
    },
    {
      id: 'lm-customers-dir',
      parentId: null,
      subsystemKey: 'lastmile',
      type: 'dir',
      label: { 'zh-CN': '终端客户', 'en-US': 'Customers' },
      shortLabel: { 'zh-CN': '客户', 'en-US': 'Customers' },
      icon: 'users',
      visible: true,
      sort: 3,
    },
    {
      id: 'lm-customers',
      parentId: 'lm-customers-dir',
      subsystemKey: 'lastmile',
      type: 'menu',
      label: { 'zh-CN': '客户账户', 'en-US': 'Customer Accounts' },
      path: '/lastmile/customers',
      permission: 'lastmile:customer:view',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-customer-create',
      parentId: 'lm-customers',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '新增客户', 'en-US': 'Create Customer' },
      permission: 'lastmile:customer:create',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-customer-authorize',
      parentId: 'lm-customers',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '渠道授权', 'en-US': 'Authorize Channel' },
      permission: 'lastmile:customer:authorize',
      visible: true,
      sort: 2,
    },
    {
      id: 'lm-channels-dir',
      parentId: null,
      subsystemKey: 'lastmile',
      type: 'dir',
      label: { 'zh-CN': '渠道管理', 'en-US': 'Channel Management' },
      shortLabel: { 'zh-CN': '渠道', 'en-US': 'Channels' },
      icon: 'link',
      visible: true,
      sort: 4,
    },
    {
      id: 'lm-channels',
      parentId: 'lm-channels-dir',
      subsystemKey: 'lastmile',
      type: 'menu',
      label: { 'zh-CN': '物流渠道', 'en-US': 'Logistics Channels' },
      path: '/lastmile/channels',
      permission: 'lastmile:channel:view',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-channel-create',
      parentId: 'lm-channels',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '新建渠道', 'en-US': 'Create Channel' },
      permission: 'lastmile:channel:create',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-channel-update',
      parentId: 'lm-channels',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '编辑渠道', 'en-US': 'Edit Channel' },
      permission: 'lastmile:channel:update',
      visible: true,
      sort: 2,
    },
    {
      id: 'lm-channel-toggle',
      parentId: 'lm-channels',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '启停渠道', 'en-US': 'Toggle Channel' },
      permission: 'lastmile:channel:toggle',
      visible: true,
      sort: 3,
    },
    {
      id: 'lm-carriers',
      parentId: 'lm-channels-dir',
      subsystemKey: 'lastmile',
      type: 'menu',
      label: { 'zh-CN': '承运商管理', 'en-US': 'Carriers' },
      path: '/lastmile/carriers',
      permission: 'lastmile:carrier:view',
      visible: true,
      sort: 2,
    },
    {
      id: 'lm-carrier-create',
      parentId: 'lm-carriers',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '新增承运商', 'en-US': 'Create Carrier' },
      permission: 'lastmile:carrier:create',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-suppliers',
      parentId: 'lm-channels-dir',
      subsystemKey: 'lastmile',
      type: 'menu',
      label: { 'zh-CN': '供应商管理', 'en-US': 'Suppliers' },
      path: '/lastmile/suppliers',
      permission: 'lastmile:supplier:view',
      visible: true,
      sort: 3,
    },
    {
      id: 'lm-supplier-create',
      parentId: 'lm-suppliers',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '新增供应商', 'en-US': 'Create Supplier' },
      permission: 'lastmile:supplier:create',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-billing-dir',
      parentId: null,
      subsystemKey: 'lastmile',
      type: 'dir',
      label: { 'zh-CN': '计费对账', 'en-US': 'Billing' },
      shortLabel: { 'zh-CN': '计费', 'en-US': 'Billing' },
      icon: 'circle-dollar-sign',
      visible: true,
      sort: 5,
    },
    {
      id: 'lm-billing',
      parentId: 'lm-billing-dir',
      subsystemKey: 'lastmile',
      type: 'menu',
      label: { 'zh-CN': '客户账单', 'en-US': 'Customer Bills' },
      path: '/lastmile/billing',
      permission: 'lastmile:billing:view',
      visible: true,
      sort: 1,
    },
    {
      id: 'lm-billing-export',
      parentId: 'lm-billing',
      subsystemKey: 'lastmile',
      type: 'action',
      label: { 'zh-CN': '导出对账单', 'en-US': 'Export Statement' },
      permission: 'lastmile:billing:export',
      visible: true,
      sort: 1,
    },
  ],
};
