package com.metabuild.modules.admin.task20;
import static org.assertj.core.api.Assertions.*;import com.metabuild.modules.admin.auth.application.*;import com.metabuild.modules.admin.auth.persistence.*;import com.metabuild.modules.admin.profile.application.*;import com.metabuild.modules.admin.profile.persistence.JooqProfileRepository;import com.metabuild.shared.kernel.*;import com.metabuild.shared.kernel.security.*;import java.time.*;import java.util.*;import java.util.concurrent.*;import org.jooq.impl.DSL;import org.junit.jupiter.api.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.*;import org.springframework.jdbc.datasource.DataSourceTransactionManager;
class CredentialRevisionRacePostgresTest {static JdbcTemplate jdbc;static org.jooq.DSLContext db;static final UUID USER=UUID.fromString("01900000-0000-7000-8000-000000000010");static final UuidV7Generator IDS=new UuidV7Generator();@BeforeAll static void connect(){String url=System.getProperty("task20.pg.url");Assumptions.assumeTrue(url!=null);var ds=new DriverManagerDataSource(url,System.getProperty("task20.pg.user","ocean"),System.getProperty("task20.pg.password",""));jdbc=new JdbcTemplate(ds);db=DSL.using(ds,org.jooq.SQLDialect.POSTGRES);}
 @BeforeEach void cleanRefreshTokens(){jdbc.update("delete from mb_refresh_token where user_id=?",USER);}
 @Test void loginVerifiedBeforePasswordCommitCannotReturnOldRevisionTokens()throws Exception{jdbc.update("update mb_user set password_hash='hash:old' where id=?",USER);var verified=new CountDownLatch(1);var resume=new CountDownLatch(1);var sessions=new Sessions();var tokens=tokens();var users=new JdbcAuthUserRepository(jdbc);var service=new AuthenticationService(users,(raw,encoded)->{boolean ok=encoded.equals("hash:"+raw);verified.countDown();await(resume);return ok;},graphs(),new AuthorizationSnapshotCompiler(),new Snapshots(),sessions,tokens,Clock.systemUTC(),IDS::generate,(f,e)->{});var future=CompletableFuture.supplyAsync(()->service.login("admin","old"));assertThat(verified.await(5,TimeUnit.SECONDS)).isTrue();assertThat(changePassword()).isTrue();resume.countDown();assertThatThrownBy(future::join).hasCauseInstanceOf(com.metabuild.shared.kernel.Unauthorized.class);assertThat(sessions.loggedOut).isNotNull();assertThat(activeRefresh()).isZero();}
 @Test void refreshRotatedBeforePasswordCommitCannotReturnOldRevisionAccess()throws Exception{jdbc.update("update mb_user set password_hash='hash:old' where id=?",USER);var tokens=tokens();long revision=((Number)jdbc.queryForObject("select credential_revision from mb_user where id=?",Long.class,USER)).longValue();String original=tokens.issue(USER,revision);var entered=new CountDownLatch(1);var resume=new CountDownLatch(1);var sessions=new Sessions();var service=new RefreshTokenService(tokens,new Snapshots(),new JdbcAuthUserRepository(jdbc),sessions);var future=CompletableFuture.supplyAsync(()->service.rotateForAccess(original,(id,capturedRevision)->{entered.countDown();await(resume);return sessions.login(id,capturedRevision);}));assertThat(entered.await(5,TimeUnit.SECONDS)).isTrue();assertThat(changePassword()).isTrue();resume.countDown();assertThatThrownBy(future::join).hasCauseInstanceOf(RefreshTokenRejected.class);assertThat(sessions.loggedOut).isNotNull();assertThat(activeRefresh()).isZero();}
 private static JdbcRefreshTokenStore tokens(){var manager=new DataSourceTransactionManager(Objects.requireNonNull(jdbc.getDataSource()));return new JdbcRefreshTokenStore(jdbc,manager,IDS,Clock.systemUTC(),Duration.ofDays(1));}private static JooqProfileRepository profile(){return new JooqProfileRepository(db);}private static boolean changePassword(){return profile().changePasswordWithRecovery(USER,"old","new-password",null,IDS.generate(),Duration.ofSeconds(30),codec()).changed();}private static PasswordCodec codec(){return new PasswordCodec(){public String hash(String raw){return "hash:"+raw;}public boolean matches(String raw,String encoded){return Objects.equals(encoded,"hash:"+raw);}};}private static AuthorizationGraphRepository graphs(){return ids->Map.of(USER,new AuthorizationGraph(USER,1,UUID.fromString("01900000-0000-7000-8000-000000000001"),List.of()));}private static int activeRefresh(){return jdbc.queryForObject("select count(*) from mb_refresh_token where user_id=? and revoked_at is null and consumed_at is null",Integer.class,USER);}private static void await(CountDownLatch latch){try{if(!latch.await(5,TimeUnit.SECONDS))throw new IllegalStateException("barrier timeout");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}}
 private static final class Sessions implements AccountSessionPort {String loggedOut;public AccessSession login(UUID id,long revision){return new AccessSession("access-"+UUID.randomUUID(),60);}public void logoutToken(String token){loggedOut=token;}public void kickoutAll(UUID id){}}
 private static final class Snapshots implements AuthorizationSnapshotStore {AuthorizationState state;public boolean initializeReady(AuthorizationSnapshot s){state=s;return true;}public AuthorizationState load(UUID id){if(state==null)state=new AuthorizationSnapshot(id,1,true,Set.of(),Set.of(),DataScopePolicy.allAccess(),Instant.now());return state;}public boolean fence(AuthorizationFence f){return false;}public boolean deleteIfFence(AuthorizationFence f){return false;}public void delete(UUID id){state=null;}}
}
