package com.metabuild.modules.admin.audit.controller;
import com.metabuild.admin.api.AuditedExport;import com.metabuild.admin.api.security.RequiresPermissions;import com.metabuild.modules.admin.audit.application.*;import com.metabuild.shared.kernel.*;import java.time.LocalDate;import java.util.Set;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/audit") public final class AuditController {private static final int EXPORT_LIMIT=10000;private final AuditRepository repository;public AuditController(AuditRepository repository){this.repository=repository;}
@GetMapping("/operation-logs") @RequiresPermissions(codes="audit:oplog:view") public AuditPage<OperationLogView> operations(@RequestParam(defaultValue="")String keyword,@RequestParam(defaultValue="all")String type,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="100")int size){validate(type,Set.of("all","create","edit","del","export","perm","config"),"log.operation.invalid");return repository.operations(filter(keyword,type,startDate,endDate,page,size));}
@GetMapping("/login-logs") @RequiresPermissions(codes="audit:login:view") public AuditPage<LoginLogView> logins(@RequestParam(defaultValue="")String keyword,@RequestParam(defaultValue="all")String result,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="100")int size){validate(result,Set.of("all","ok","fail"),"log.login-result.invalid");return repository.logins(filter(keyword,result,startDate,endDate,page,size));}
@GetMapping(value="/operation-logs/export",produces="text/csv") @RequiresPermissions(codes="audit:oplog:export") @AuditedExport(operation="audit.operation.export") public ResponseEntity<byte[]> exportOperations(@RequestParam(defaultValue="")String keyword,@RequestParam(defaultValue="all")String type,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate){validate(type,Set.of("all","create","edit","del","export","perm","config"),"log.operation.invalid");var page=repository.operations(filter(keyword,type,startDate,endDate,1,EXPORT_LIMIT));requireExportable(page.total());return csv(AuditCsv.operation(page.list()),"operation-logs.csv",page.list().size());}
@GetMapping(value="/login-logs/export",produces="text/csv") @RequiresPermissions(codes="audit:login:export") @AuditedExport(operation="audit.login.export") public ResponseEntity<byte[]> exportLogins(@RequestParam(defaultValue="")String keyword,@RequestParam(defaultValue="all")String result,@RequestParam(required=false)LocalDate startDate,@RequestParam(required=false)LocalDate endDate){validate(result,Set.of("all","ok","fail"),"log.login-result.invalid");var page=repository.logins(filter(keyword,result,startDate,endDate,1,EXPORT_LIMIT));requireExportable(page.total());return csv(AuditCsv.login(page.list()),"login-logs.csv",page.list().size());}
private static AuditFilter filter(String k,String d,LocalDate s,LocalDate e,int p,int z){if(p<1||z<1||z>EXPORT_LIMIT||s!=null&&e!=null&&s.isAfter(e))throw new BadRequest(()->"audit.filter.invalid","Invalid audit filter");return new AuditFilter(k,d,s,e,p,z);}
private static void requireExportable(long total){if(total>EXPORT_LIMIT)throw new PayloadTooLarge(()->"audit.export.too-large","Export exceeds 10000 rows; narrow the filters");}
private static void validate(String value,Set<String> values,String code){if(!values.contains(value))throw new BadRequest(()->code,"Invalid audit discriminator");}
private static ResponseEntity<byte[]> csv(byte[] data,String name,int rows){return ResponseEntity.ok().contentType(MediaType.parseMediaType("text/csv;charset=UTF-8")).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+name+"\"").header("X-Export-Row-Count",Integer.toString(rows)).body(data);}}
