package com.metabuild.modules.admin.departments.persistence;
import com.metabuild.admin.api.*; import com.metabuild.modules.admin.departments.application.*; import java.sql.*; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate;
public final class JdbcDepartmentRepository implements DepartmentRepository {
 private final JdbcTemplate jdbc; public JdbcDepartmentRepository(JdbcTemplate j){jdbc=j;}
 private static DepartmentView row(ResultSet r,int n)throws SQLException{return new DepartmentView(r.getObject("id",UUID.class),r.getObject("parent_id",UUID.class),r.getString("name"),r.getInt("sort_order"),r.getLong("member_count"));}
 public List<DepartmentView> tree(){return jdbc.query("select d.*, (select count(*) from mb_user u where u.deleted_at is null and u.dept_id in (with recursive s as (select id from mb_dept where id=d.id union all select c.id from mb_dept c join s on c.parent_id=s.id where c.deleted_at is null) select id from s)) member_count from mb_dept d where d.deleted_at is null order by d.sort_order,d.name",JdbcDepartmentRepository::row);}
 public Optional<DepartmentView> find(UUID id){return tree().stream().filter(d->d.id().equals(id)).findFirst();}
 public DepartmentView create(UUID id,String name,UUID parent){if(parent!=null&&!exists(parent))throw new com.metabuild.shared.kernel.NotFound(()->"iam.dept.not-found","Parent department not found");jdbc.update("insert into mb_dept(id,parent_id,code,name) values(?,?,?,?)",id,parent,id.toString(),name);return find(id).orElseThrow();}
 public DepartmentMovePreimage movePreimage(UUID id,UUID newParent){if(newParent!=null&&wouldCycle(id,newParent))throw cycle();String sql="with recursive subtree(id) as (select id from mb_dept where id=? and deleted_at is null union all select c.id from mb_dept c join subtree s on c.parent_id=s.id where c.deleted_at is null), old_anc(id,parent_id) as (select id,parent_id from mb_dept where id=(select parent_id from mb_dept where id=?) union all select d.id,d.parent_id from mb_dept d join old_anc a on a.parent_id=d.id), new_anc(id,parent_id) as (select id,parent_id from mb_dept where id=? union all select d.id,d.parent_id from mb_dept d join new_anc a on a.parent_id=d.id), scope_users as (select distinct u.id from mb_user u join mb_user_role ur on ur.user_id=u.id join mb_role r on r.id=ur.role_id where u.deleted_at is null and r.deleted_at is null and r.status='ACTIVE' and r.data_scope_type='OWN_DEPT_AND_BELOW' and u.dept_id in (select id from old_anc union select id from new_anc)) select id from mb_user where deleted_at is null and dept_id in (select id from subtree) union select id from scope_users";return new DepartmentMovePreimage(Set.copyOf(jdbc.queryForList(sql,UUID.class,id,id,newParent)));}
 public DepartmentView patch(UUID id,DepartmentPatch p){List<String> sets=new ArrayList<>();List<Object> args=new ArrayList<>();if(p.namePresent()){sets.add("name=?");args.add(p.name());}if(p.parentPresent()){if(p.parentId()!=null&&wouldCycle(id,p.parentId()))throw cycle();sets.add("parent_id=?");args.add(p.parentId());}sets.add("updated_at=current_timestamp");args.add(id);int n;try{n=jdbc.update("update mb_dept set "+String.join(",",sets)+" where id=? and deleted_at is null",args.toArray());}catch(org.springframework.dao.DataIntegrityViolationException failure){if(isCycleViolation(failure))throw cycle();throw failure;}if(n==0)throw new com.metabuild.shared.kernel.NotFound(()->"iam.dept.not-found","Department not found");return find(id).orElseThrow();}
 private boolean wouldCycle(UUID id,UUID parent){if(id.equals(parent))return true;Boolean cycle=jdbc.queryForObject("with recursive descendants(id) as (select id from mb_dept where parent_id=? and deleted_at is null union all select child.id from mb_dept child join descendants d on child.parent_id=d.id where child.deleted_at is null) select exists(select 1 from descendants where id=?)",Boolean.class,id,parent);return Boolean.TRUE.equals(cycle);}
 private static boolean isCycleViolation(Throwable failure){for(Throwable current=failure;current!=null;current=current.getCause())if(current instanceof SQLException sql&&"23514".equals(sql.getSQLState())&&sql.getMessage()!=null&&sql.getMessage().contains("department cycle is not allowed"))return true;return false;}
 private static com.metabuild.shared.kernel.Conflict cycle(){return new com.metabuild.shared.kernel.Conflict(()->"iam.dept.cycle","Department parent would create a cycle");}
 public Set<UUID> subtree(Set<UUID> roots){check(roots);if(roots.isEmpty())return Set.of();return Set.copyOf(jdbc.queryForList("with recursive s as (select id from mb_dept where id=any(?) and deleted_at is null union all select c.id from mb_dept c join s on c.parent_id=s.id where c.deleted_at is null) select distinct id from s",UUID.class,(Object)roots.toArray(UUID[]::new)));}
 public BatchResult<UUID,DepartmentSummary> batchGet(Set<UUID> ids){check(ids);Map<UUID,DepartmentSummary> found=new LinkedHashMap<>();if(!ids.isEmpty())jdbc.query("select id,parent_id,name,status from mb_dept where id=any(?) and deleted_at is null",r->{UUID id=r.getObject(1,UUID.class);found.put(id,new DepartmentSummary(id,r.getObject(2,UUID.class),r.getString(3),"ACTIVE".equals(r.getString(4))));},(Object)ids.toArray(UUID[]::new));Set<UUID> missing=new LinkedHashSet<>(ids);missing.removeAll(found.keySet());return new BatchResult<>(found,missing);}
 private static void check(Set<UUID> ids){if(ids.size()>500)throw new IllegalArgumentException("batch size must not exceed 500");}
 private boolean exists(UUID id){Boolean found=jdbc.queryForObject("select exists(select 1 from mb_dept where id=? and deleted_at is null)",Boolean.class,id);return Boolean.TRUE.equals(found);}
}
