/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminRolesRouteImport } from './routes/_auth/admin/roles'
import { Route as AuthAdminDashboardRouteImport } from './routes/_auth/admin/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRolesRoute = AuthAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminDashboardRoute = AuthAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AuthAdminDashboardRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/admin/users': typeof AuthAdminUsersRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AuthAdminDashboardRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/admin/users': typeof AuthAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin/dashboard': typeof AuthAdminDashboardRoute
  '/_auth/admin/roles': typeof AuthAdminRolesRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/'
    | '/login'
    | '/admin/dashboard'
    | '/admin/roles'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/'
    | '/login'
    | '/admin/dashboard'
    | '/admin/roles'
    | '/admin/users'
  id:
    | '__root__'
    | '/403'
    | '/_auth'
    | '/login'
    | '/_auth/admin/dashboard'
    | '/_auth/admin/roles'
    | '/_auth/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/roles': {
      id: '/_auth/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthAdminRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/dashboard': {
      id: '/_auth/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthAdminDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminDashboardRoute: typeof AuthAdminDashboardRoute
  AuthAdminRolesRoute: typeof AuthAdminRolesRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminDashboardRoute: AuthAdminDashboardRoute,
  AuthAdminRolesRoute: AuthAdminRolesRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
