/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.lastmile.tables.records;


import com.metabuild.schema.lastmile.tables.BizSchemaProbe;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizSchemaProbeRecord extends UpdatableRecordImpl<BizSchemaProbeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.biz_schema_probe.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.biz_schema_probe.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.biz_schema_probe.owner_name</code>.
     */
    public void setOwnerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.biz_schema_probe.owner_name</code>.
     */
    public String getOwnerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.biz_schema_probe.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.biz_schema_probe.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizSchemaProbeRecord
     */
    public BizSchemaProbeRecord() {
        super(BizSchemaProbe.BIZ_SCHEMA_PROBE);
    }

    /**
     * Create a detached, initialised BizSchemaProbeRecord
     */
    public BizSchemaProbeRecord(UUID id, String ownerName, OffsetDateTime createdAt) {
        super(BizSchemaProbe.BIZ_SCHEMA_PROBE);

        setId(id);
        setOwnerName(ownerName);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
